### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kobehaha** [MyCATApache/Mycat2#105]
小建议:

1 mycat2.0的配置文件是不是太多了，这样可能用户使用起来配置相对麻烦.学习成本相对较高

2 然后建议可以增加一些文档,比如设计流程,roadmap,issues规范等等

3 可能一些脚本，快速搭建测试环境之类的.

这样可能优化新用户的使用和减少成为commitor的学习成本.有益于对整个mycat2.0的社区发展.

**Comment by hejairui** [comment]
可以看下在https://github.com/MyCATApache/tcp-proxy/tree/master/doc 中的文档,该文档会持续跟进
