### ISSUE TITLE
avg 需要保留小数

### ISSUE THREAD

**Issue by zwyqz** [MyCATApache/Mycat2#270]
mysql> select count(*) as sm , sum(id) ,avg(id)  from travelrecord1  where id >=10;
+------+-------------+----------+
| sm   | EXPR$1      | EXPR$2   |
+------+-------------+----------+
|  798 | 10020324660 | 12556797 |
+------+-------------+----------+
1 row in set (0.12 sec)

**Comment by junwen12221** [comment]
0,6开始支持avg的结果是浮点,通过修改Calcite的类型系统支持
