### ISSUE TITLE
【Future】元数据管理, 支持show语句与set语句

### ISSUE THREAD

**Issue by wangzihaogithub** [MyCATApache/Mycat2#298]
1.内置Information Schema 对应配置中心,全局统一
2.核心sql
BEGIN
COMMIT
START TRANSACTION
TRUNCATE
UPDATE
USE
ROLLBACK
SELECT
SET [NAMES|CHARACTER SET]
SET TRANSACTION
SET [GLOBAL|SESSION]
EXPLAIN
INSERT
REPLACE
DELETE
LOAD DATA
SHOW WARNINGS
SHOW DATABASES
SHOW [GLOBAL|SESSION] VARIABLES

3.表操作

CREATE DATABASE
CREATE TABLE LIKE
CREATE TABLE
CREATE USER
CREATE VIEW

ADD COLUMN
ALTER DATABASE
ALTER TABLE
ALTER USER

DESC
DESCRIBE
DROP COLUMN
DROP DATABASE
DROP INDEX
DROP TABLE
DROP USER
DROP VIEW

MODIFY COLUMN
RENAME TABLE

SHOW CHARACTER SET
SHOW COLLATION
SHOW [FULL] COLUMNS FROM
SHOW CREATE TABLE
SHOW CREATE USER

SHOW ENGINES 默认innodb
SHOW ERRORS
SHOW [FULL] FIELDS FROM
SHOW GRANTS
SHOW INDEXES [FROM|IN]
SHOW INDEX [FROM|IN]
SHOW KEYS [FROM|IN]
SHOW [FULL] PROCESSSLIST
SHOW SCHEMAS
SHOW [FULL] TABLES
SHOW TABLE REGIONS
SHOW TABLE STATUS

**Comment by wangzihaogithub** [comment]
设计如下

![image](https://user-images.githubusercontent.com/18204507/79069732-1fcb1c00-7d03-11ea-9018-c33db820f466.png)

**Comment by wangzihaogithub** [comment]
![image](https://user-images.githubusercontent.com/18204507/79069742-307b9200-7d03-11ea-8b08-4091cd95433f.png)

**Comment by junwen12221** [comment]
有三分之一已经实现,重点测试mysql workbanch,兼容性比较差,另外涉及更改schema的ddl在9066端口操作
