### ISSUE TITLE
分片表查询出错

### ISSUE THREAD

**Issue by ganzr** [MyCATApache/Mycat2#328]
版本号：mycat2 1.08-2020-6-7
mysql5.7.29
os：Windows
**配置了两个分片表，一个全局表，配置文件大致如下：**
metadata: #读写分离无需配置
  schemas: [{
              schemaName: 'db' ,targetName: 'repli',
              shadingTables: {
                tableName1: {
                  columns: [{
                              columnName: ID , #分片字段信息,显式提供,
                              shardingType: NATURE_DATABASE_TABLE , #类型:自然分片,即根据一列(支持)或者多个列(暂不支持)的值映射成一个值,再根据该值通过单维度的分片算法计算出数据分片范围
                              function: {
                                clazz: io.mycat.router.function.PartitionByLong ,
                                name: partitionByLong,
                                properties: {partitionCount: '2', partitionLength: '512'}, 
                                ranges: {}
                              }
                            }],
                  createTableSQL: "" ,
                  dataNodes: [{targetName: ds1 ,schemaName: db1, tableName: tableName1},
                              {targetName: ds2 ,schemaName: db2, tableName: tableName1}] #9999999999
                } ,
                tableName2: {
                  columns: [{
                              columnName: ID , #分片字段信息,显式提供,
                              shardingType: NATURE_DATABASE_TABLE , #类型:自然分片,即根据一列(支持)或者多个列(暂不支持)的值映射成一个值,再根据该值通过单维度的分片算法计算出数据分片范围
                              function: {
                                clazz: io.mycat.router.function.PartitionByLong ,
                                name: partitionByLong,
                                properties: {partitionCount: '2', partitionLength: '512'}, ranges: {}
                              }
                            }] ,
                  createTableSQL: "",
                  dataNodes: [{targetName: ds1 ,schemaName: db1, tableName: tableName2},
                              {targetName: ds2 ,schemaName: db2, tableName: tableName2}]
                }
              },
              globalTables: {
                tableName: {
                  createTableSQL: "",
                  dataNodes: [{targetName: ds1 ,schemaName: db1, tableName: tableName},{targetName: ds2 ,schemaName: db2, tableName: tableName}]
              }
            }
          }]
interceptors:
  [{
     user: {ip: '.', password: '123456', username: root},
     sqls:[
#     {sql: 'SELECT COUNT(1) FROM db1.travelrecord',command: distributedQuery, cache: 'initialDelay = 1s,refreshInterval = 15s'}
     ]
   }]
datasource:
  datasources: [{name: ds1, ip: 0.0.0.0,port: 3306,user: root,password: 123456,maxCon: 10000,minCon: 0,
                 maxRetryCount: 3, #连接重试次数
                 maxConnectTimeout: 10000, #连接超时时间 毫秒
                 dbType: mysql, #
                 url: 'jdbc:mysql://localhost:3306?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autocommit=false&readonly=false',
                 weight: 1, #负载均衡权重
                 initSqls: [], #建立连接后执行的sql,在此可以写上use xxx初始化默认database
                 instanceType: READ_WRITE, #READ,WRITE,READ_WRITE ,集群信息中是主节点,则默认为读写,副本则为读,此属性可以强制指定可写,
                 initSqlsGetConnection: true
                },
                {name: ds2, ip: 0.0.0.0,port: 3306,user: root,password: 123456,maxCon: 10000,minCon: 0,
                maxRetryCount: 3,
                maxConnectTimeout: 10000,
                dbType: mysql,
                url: 'jdbc:mysql://localhost:3306?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autocommit=false&readonly=false',
                weight: 1,
                initSqls: [],
                instanceType: READ_WRITE, #READ,WRITE,READ_WRITE
                initSqlsGetConnection: true
                }
  ]
  datasourceProviderClass: io.mycat.datasource.jdbc.datasourceProvider.AtomikosDatasourceProvider
  timer: {initialDelay: 10, period: 5, timeUnit: SECONDS}
cluster: #集群,数据源选择器,既可以mycat自行检查数据源可用也可以通过mycat提供的外部接口设置设置数据源可用信息影响如何使用数据源
  close: true  #关闭集群心跳,此时集群认为所有数据源都是可用的,可以通过mycat提供的外部接口设置数据源可用信息达到相同效果
  clusters: [
  {name: repli ,
   replicaType: MASTER_SLAVE , # SINGLE_NODE:单一节点 ,MASTER_SLAVE:普通主从 GARELA_CLUSTER:garela cluster
   switchType: SWITCH , #NOT_SWITCH:不进行主从切换,SWITCH:进行主从切换
   readBalanceType: BALANCE_ALL  , #对于查询请求的负载均衡类型
   readBalanceName:  , #对于查询请求的负载均衡类型
   writeBalanceName:  ,  #对于修改请求的负载均衡类型
   masters:[ds1 , ds2], #主节点列表,普通主从,当主失去连接后,依次选择列表中存活的作为主节点
   replicas:[ ds2], #从节点列表
   maxCon:, #集群最占用大连接限制
   heartbeat:{maxRetry: 3, #心跳重试次数
              minSwitchTimeInterval: 120000 , #最小主从切换间隔
              heartbeatTimeout: 100000 , #心跳超时值,毫秒
              slaveThreshold: 0 , # mysql binlog延迟值
              requestType: 'mysql' #进行心跳的方式,mysql或者jdbc两种
   }}
  ]
  timer: {initialDelay: 0, period: 1, timeUnit: SECONDS} #心跳定时器 initialDelay一般为0,mycat会在开启集群心跳,一个initialDelay+1秒之后开启服务器端口
server:
  ip: 0.0.0.0
  port: 8066
  reactorNumber: 1
  #用于多线程任务的线程池,
  worker: {close: false, #禁用多线程池,jdbc等功能将不能使用
           maxPengdingLimit: 65535, #每个线程处理任务队列的最大长度
           maxThread: 1000,
           minThread: 2,
           timeUnit: MINUTES,
           waitTaskTimeout: 5 #超时后将结束闲置的线程
  }
#负载均衡类型 BALANCE_ALL:所有数据源参与负载均衡 BALANCE_ALL_READ:所以非master数据源参与负载均衡 BALANCE_NONE:只有master(一个)参与负载
plug:
  loadBalance:
    defaultLoadBalance: balanceRandom
    loadBalances: [
    {name: BalanceRunOnMaster, clazz: io.mycat.plug.loadBalance.BalanceRunOnMaster},
    {name: BalanceLeastActive, clazz: io.mycat.plug.loadBalance.BalanceLeastActive},
    {name: BalanceRoundRobin, clazz: io.mycat.plug.loadBalance.BalanceRoundRobin},
    {name: BalanceRunOnReplica, clazz: io.mycat.plug.loadBalance.BalanceRunOnReplica},
    {name: BalanceRunOnRandomMaster, clazz: io.mycat.plug.loadBalance.BalanceRunOnRandomMaster}
    ]
  sequence:
    sequences: [
    {name: 'db1_tableName1', clazz: io.mycat.plug.sequence.SequenceMySQLGenerator ,args: "sql : SELECT db1.mycat_seq_nextval('tableName1') , targetName:ds1"},
    {name: 'db1_tableName2', clazz: io.mycat.plug.sequence.SequenceMySQLGenerator, args: "sql : SELECT db1.mycat_seq_nextval('db1_tableName2') , targetName:ds1"}
    #{name: '', clazz: io.mycat.plug.sequence.SequenceSnowflakeGenerator ,args: 'workerId:1'},
    ]

properties:
  key: value

#lib start
#lib end

**用Navicat能成功连接，在使用“select * from tableName”时，对全局表来说没问题，但是在对分片表进行该查询时，报了以下错误**：
21:13:53 T=noBindingExecutor0 [io.mycat.proxy.session.Session setLastMessage at 122]-[ERROR] 
org.apache.calcite.tools.ValidationException: java.lang.UnsupportedOperationException
	at io.mycat.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:203)
	at io.mycat.calcite.CalciteRunners.compile(CalciteRunners.java:39)
	at io.mycat.calcite.prepare.MycatSqlPlanner.<init>(MycatSqlPlanner.java:51)
	at io.mycat.calcite.prepare.FastMycatCalciteSQLPrepareObject.plan(FastMycatCalciteSQLPrepareObject.java:63)
	at io.mycat.sqlHandler.dql.SelectSQLHandler.lambda$onSelectTable$3(SelectSQLHandler.java:219)
	at io.mycat.sqlHandler.dql.SelectSQLHandler$$Lambda$427/1664972170.run(Unknown Source)
	at io.mycat.proxy.session.ServerTransactionSessionRunner$3.accept(ServerTransactionSessionRunner.java:146)
	at io.mycat.bindThread.BindThreadPool.lambda$run$3(BindThreadPool.java:144)
	at io.mycat.bindThread.BindThreadPool$$Lambda$429/1531155766.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by junwen12221** [comment]
需要提供创建表的sql,报错是sql进行类型检查的时候报错,与sql的字段类型有关系,已知1.08的版本对于枚举等类型不支持,在下一个版本统一变成字符串类型处理

**Comment by wangzihaogithub** [comment]
估计是navcat客户端发的哪条sql不支持，需要把控制台报错信息上的最后一条sql语句发出来，麻烦您了。

因为你select from table 不是只发这一条sql. 应该是客户端同时发送的别的sql不支持。
