### ISSUE TITLE
mycat 数据库连接出错

### ISSUE THREAD

**Issue by superBinLiu** [MyCATApache/Mycat2#329]
![image](https://user-images.githubusercontent.com/62001174/84104220-aa9c6e80-aa47-11ea-8163-e8ad5b6f5b28.png)

**Comment by junwen12221** [comment]
连接后端有两种方式,一种是jdbc一种是native(proxy),先用jdbc看看是否能连上

**Comment by superBinLiu** [comment]
mycat已经起来了，用的是navicat客户端工具连接的，test是通了，但是不能点开mycat链接。
![image](https://user-images.githubusercontent.com/62001174/84105411-d79e5080-aa4a-11ea-853f-bdfa2497f4b1.png)

**Comment by wangzihaogithub** [comment]
是mysql8吗？ 要改下登录验证方式。
改成mysql5.7的默认验证方式试下。在mysql的my.cnf文件里改

**Comment by junwen12221** [comment]
你这个问题是mycat连接mysql的时候报错反馈到客户端了
