### ISSUE TITLE
sql 别名无效

### ISSUE THREAD

**Issue by superBinLiu** [MyCATApache/Mycat2#363]
select d.i_customer_id as CC from dim_batch d
where d.i_customer_id= 9455748790208;

![image](https://user-images.githubusercontent.com/62001174/89517777-d00de480-d80c-11ea-8160-e8a684830df1.png)
别名CC无效！

**Comment by Tracy82** [comment]
我这边也碰到这个问题了。

**Comment by junwen12221** [comment]
这个在下一个版本发布会修复

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/pull/364/commits/c9bafa12130bd46310b0b53256d3e5f6302eba02

代码修复方案参考

**Comment by Tracy82** [comment]
你好！刚试了你的参考修复方案,返回的结果还是没有别名。

**Comment by junwen12221** [comment]
> 你好！刚试了你的参考修复方案,返回的结果还是没有别名。

 return new EnumeratorRowIterator(CalciteConvertors.getMycatRowMetaData(resultSetType != null ? resultSetType : relNode.getRowType()), enumerator,

debug查看resultSetType看看有没有别名的信息,没有的话,就从

 RelNode relNode = planner.rel(validate).project(true);
        RelDataType resultRowType = relNode.getRowType();

这里开始重新跟踪
