### ISSUE TITLE
Navicat连接mycat2.0报错

### ISSUE THREAD

**Issue by Tracy82** [MyCATApache/Mycat2#366]
在win10下,用Navicat工具连接mycat2.0数据库时,报错了！

![image](https://user-images.githubusercontent.com/7930353/90002857-d5b07200-dcc5-11ea-9a47-f10694a8c76e.png)

**Comment by junwen12221** [comment]
请用稳定的分支 https://github.com/MyCATApache/Mycat2/tree/v1.11-05-2020-7-14
