### ISSUE TITLE
shardingtable查询加上别名之后返回的查询结果没有别名

### ISSUE THREAD

**Issue by kwanhor** [MyCATApache/Mycat2#386]
![原始Sql](https://user-images.githubusercontent.com/44669704/99747398-64c6f480-2b15-11eb-93c2-e75c5c5a32f4.png)
![优化后的sql](https://user-images.githubusercontent.com/44669704/99747413-6ee8f300-2b15-11eb-8243-ef215546ae11.png)

TableHandler非空的情况下，原始sql被Calcite优化之后，重新生成了selectList,原始sql变为子查询语句,然后返回的结果找不到别名

**Comment by junwen12221** [comment]
这个问题可能要在druid语法解析器层面记录或者优化前记录别名,然后执行前给他补回去,可以告诉一下你用的版本吗,曾经修过类似的bug

**Comment by junwen12221** [comment]
或者后端数据源改成jdbc,不使用proxy也能暂时解决这个问题

**Comment by kwanhor** [comment]
我现在用的版本是2.11-05的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 下午4:07
收件人:&nbsp;"MyCATApache/Mycat2"<Mycat2@noreply.github.com&gt;;
抄送:&nbsp;"落叶"<1256683226@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] shardingtable查询加上别名之后返回的查询结果没有别名 (#386)





 
这个问题可能要在druid语法解析器层面记录或者优化前记录别名,然后执行前给他补回去,可以告诉一下你用的版本吗,曾经修过类似的bug

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/commit/c9bafa12130bd46310b0b53256d3e5f6302eba02#

CalciteRunners.java 

resultSetType 是结果集类型包含字段名

```
 return new EnumeratorRowIterator(CalciteConvertors.getMycatRowMetaData(relNode.getRowType()), enumerator,
        return new EnumeratorRowIterator(CalciteConvertors.getMycatRowMetaData(resultSetType != null ? resultSetType : relNode.getRowType()), enumerator,
                () -> {
                    recorder.addRecord(SqlRecorderType.EXECUTION_TIME, sql, TimeProvider.INSTANCE.now()-execution_start);
                    recorder.addRecord(SqlRecorderType.EXECUTION_TIME, sql, TimeProvider.INSTANCE.now() - execution_start);
                    recorder.addRecord(SqlRecorderType.AT_END, sql, TimeProvider.INSTANCE.now());
                });
    }
```
不使用代理的时候即
```
   if (plan instanceof MycatSqlPlanner) {
                    ProxyInfo proxyInfo = ((MycatSqlPlanner) plan).tryGetProxyInfo();
                    if (proxyInfo != null) {//使用代理
                        String sql = proxyInfo.getSql();
                        String targetName = proxyInfo.getTargetName();
                        receiver.proxySelect(targetName, sql);
                        return;
                    }
                }
                receiver.sendResultSet(() -> plan.run(), plan::explain);//使用结果集
```

所以只使用jdbc方式暂时没有问题,而在符号单节点透传代理情况下,会把relNode变成sql,
在2.11-05的源码下,方法有几个
1.在relNode上更改project添加别名
2.改sql重新变成sql语法树补上这个别名
3.
https://github.com/MyCATApache/Mycat2/blob/v1.11-05-2020-9-25/hbt/src/main/java/io/mycat/calcite/MycatImplementor.java
的project相关的补上这个别名,如果根节点不是project则补上project节点

**Comment by kwanhor** [comment]
去掉代理后测试OK,使用代理的改了没有效果,我再看看
