### ISSUE TITLE
mycat未来能否支持seata at分布式事务?  

### ISSUE THREAD

**Issue by xlxomg** [MyCATApache/Mycat2#391]
目前遇到的问题是执行,"SHOW FULL TABLES FROM `库名` LIKE '表名'"  语句时,库名取的是物理库名, 所以该查询没有结果, 导致后续一串的问题。

**Comment by junwen12221** [comment]
seata支持,这个是可以的,因为支持只使用jdbc连接池实现,而且有同一个线程贯穿整个请求响应的环境.

**Comment by xlxomg** [comment]
@junwen12221 抱歉,才看到自己发错地方了，我使用的是mycat，应该在mycat-server发布问题更合适。

**Comment by xlxomg** [comment]
@junwen12221 既然在这问了， 想确认下mycat1目前版本是否是不支持seata呢, 我担心万一是自己接入的姿势不对(我是用mycat1.6.7.6-test验证的)  
感谢大佬的回复~

**Comment by junwen12221** [comment]
@xlxomg seata作为客户端框架,可能有些sql不支持导致报错

**Comment by xlxomg** [comment]
@junwen12221  嗯  我测试就是这样的,   感觉遇到的问题mycat也不是不能解决的,   有点遗憾
