### ISSUE TITLE
Mycat2-1.12 配置多数据源读写分离，单库事务失败。

### ISSUE THREAD

**Issue by adu-shzz** [MyCATApache/Mycat2#403]
问题重现的操作步骤：

1. 在 mycat.yml 中，配置两个数据源 A(A-Master、A-Slave)、B(B-Master、B-Slave)，其中，A-Master、B-Master 的 instanceType=WRITE，A-Slave和B-Slave 的 instanceType=READ。
2. 在 SpringBoot 项目中，使用 @transaction 注解标记 Service 方法，该方法内部对 B 数据源进行 CRUD 操作，必定出现错误，堆栈信息如下：
Could not roll back JDBC transaction; nested exception is java.sql.SQLException: Connection is closed.

**解决办法，将 A、B两数据源的配置顺序反转，B在前，A在后，问题得以解决！！！**

另：关于错误日志， Mycat2-Server 这边并没有打印出报错信息(DEBUG模式下)，报错是在 SpringBoot 这边，可以按我的操作步骤重现出来。

**Comment by junwen12221** [comment]
在该版本中,第一个数据源与其他数据源有区别,第一个数据源在一些情况下,还作为select update delete insert语句之外sql的路由节点.
https://raw.githubusercontent.com/wiki/MyCATApache/Mycat2/img/product_arch_expand.png

贴出日志是为了查看哪些sql生产了影响,另外可能存在Mycat中日志被catch后吞掉的情况,

后面我们会加强不同应用框架的测试.

**Comment by adu-shzz** [comment]
> 在该版本中,第一个数据源与其他数据源有区别,第一个数据源在一些情况下,还作为select update delete insert语句之外sql的路由节点.
> https://raw.githubusercontent.com/wiki/MyCATApache/Mycat2/img/product_arch_expand.png
> 
> 贴出日志是为了查看哪些sql生产了影响,另外可能存在Mycat中日志被catch后吞掉的情况,
> 
> 后面我们会加强不同应用框架的测试.

感谢QQ上的热心指点！赞一个！
