### ISSUE TITLE
Mycat2-1.12 —— 函数 MycatDBs::createClient/2 有不兼容的 SQL_SELECT_LIMIT 值。

### ISSUE THREAD

**Issue by adu-shzz** [MyCATApache/Mycat2#404]
在  class io.mycat.upondb.MycatDBs::createClient/2 这个方法中，第 53 行对 SQL_SELECT_LIMIT 值的处理，始终认为是一个数值，代码如下：

dataContext.setVariable(MycatDataContextEnum.SELECT_LIMIT, Long.parseLong(value));

其中，Long.parseLong(value) 抛出异常，原因是，客户端发送了命令  `SET SQL_SELECT_LIMIT DEFAULT`。

查阅 MySQL 手册，其语法格式为 `SET SQL_SELECT_LIMIT {value | DEFAULT} `。

**Comment by junwen12221** [comment]
你好,这个参数处理比较麻烦,我们的观点是不要让它报错,不影响客户端就可以.但是不会生效.我们这边尽量注意这个问题.如果你能编译打包的话,把代码去掉就可以.或者可以加我qq:294712221
