### ISSUE TITLE
多后端数据源适配

### ISSUE THREAD

**Issue by junwen12221** [MyCATApache/Mycat2#407]
Mycat2准备支持Oracle,SQLServer,PostgreSQL,所以调查大家用的哪个数据库?

Oracle
11.2.0.1
12.1.0.1
12.2.0.1
18.1.0
19c

SQLServer
2008
2012
2014
2016
2017
2019

PostgreSQL
9.5.24
9.6.20
10.15
11.10
12.5
13.1

回复数据库缩写o,s,p加上版本号如o11

**Comment by junwen12221** [comment]
后端方言生成完成

**Comment by FletcherDD** [comment]
现在可以支持SQLServer 2016吗？
