### ISSUE TITLE
支持alter语句

### ISSUE THREAD

**Issue by junwen12221** [MyCATApache/Mycat2#437]

**Comment by junwen12221** [comment]
1.alter 语句经常sql解析提取item语法元素
2.建表语句应用建表语句生成新的建表语句
3.把alter语句根据表的dataNode修改表名生成目标需要执行的sql
4.使用jdbc向目标执行生成的alter语句
5.执行新的建表语句

**Comment by zwyqz** [comment]
当前实现版本的分表的alter语句无法正确生成.
