### ISSUE TITLE
Mac下JAR包方式启动有异常

### ISSUE THREAD

**Issue by guozhanxian** [MyCATApache/Mycat2#480]
**Describe the bug**
启动后，控制台有异常信息。

**To Reproduce**
1. Go to terminal，run jar with command ---  java -Dfile.encoding=UTF-8 -DMYCAT_HOME=myresources  -jar mycat2-1.13-release-2020-1-11.jar

**Screenshots**
![mycat_error](https://user-images.githubusercontent.com/1329731/105436468-3a6ef000-5c9a-11eb-8237-c847e6205675.png)

**Comment by junwen12221** [comment]
先用
http://dl.mycat.org.cn/2.0/1.14-release/

这个包看看

这个问题,稍后处理

**Comment by wangzihaogithub** [comment]
这个看起来是您自己打的包, 请用java8打包,  目前不支持java9及以上打包

**Comment by wangzihaogithub** [comment]
目前仅支持, java8版本,  用java8就好了
