### ISSUE TITLE
AuthPacket获取不到database

### ISSUE THREAD

**Issue by xieyue89** [MyCATApache/Mycat2#491]
![image](https://user-images.githubusercontent.com/49059066/108581018-2ab1fc80-7369-11eb-8d97-1a6f31baa6d4.png)

![image](https://user-images.githubusercontent.com/49059066/108581048-4fa66f80-7369-11eb-9143-1e774e5983dc.png)

**Comment by junwen12221** [comment]
收到

**Comment by junwen12221** [comment]
客户端可以选择不发送database,而使用其他方式实现指定database。
