### ISSUE TITLE
autommit 导致提交失败

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#493]
navicat连接mycat，在客户端执行

```
START TRANSACTION
INSERT INTO `travelrecord` (`blob`, `days`, `fee`, `traveldate`, `user_id`)
VALUES (NULL, 3, 3, timestamp('2021-02-21 12:23:42.058156'), 'tom');
COMMIT;
```
mycat会自动提交，导致出现“本地事务提交失败”异常。应该是session的autocommit=1导致。
能否默认autocommit=0，或者在datasource的连接中设置autocommit=0，如下

`"url":"jdbc:mysql://127.0.0.1:3306/mysql?autoCommit=0&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8",`
试过了，上述设置对mycat来说应该是无效的。

**Comment by junwen12221** [comment]
set autocommit = 0;
INSERT INTO `travelrecord` (`blob`, `days`, `fee`, `traveldate`, `user_id`)
VALUES (NULL, 3, 3, timestamp('2021-02-21 12:23:42.058156'), 'tom');
COMMIT;

**Comment by junwen12221** [comment]
dev分支没有这个问题，但是不能正式使用
