### ISSUE TITLE
支持timestamp类型的字段分片

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#495]
创建表，并对traveldate进行YYYYMM分片
```
CREATE TABLE `travelrecord2` (
  `id` bigint(20) NOT NULL KEY,
  `user_id` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `traveldate` datetime DEFAULT NULL,
  `fee` decimal(10,0) DEFAULT NULL,
  `days` int(11) DEFAULT NULL,
  `blob` longblob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
tbpartition by YYYYMM(traveldate) tbpartitions 12;
```
"timestamp time"这种写法是支持的，例如
```
INSERT INTO `travelrecord2`(`id`,`user_id`,`traveldate`,`fee`,`days`,`blob`)
VALUES (1,2,timestamp '2021-03-22 18:34:05.983692' ,3,4,NULL)
```
但“timestamp(time)"这种写法不支持，
```
INSERT INTO `travelrecord2`(`id`,`user_id`,`traveldate`,`fee`,`days`,`blob`)
VALUES (1,2,timestamp('2021-02-22 18:34:05.983692'),3,4,NULL)
```
报错
```
> 0 -  HY000com.alibaba.druid.FastsqlException: eval error : timestamp(?)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorUtils.eval(SQLEvalVisitorUtils.java:105)
	at com.alibaba.druid.sql.visitor.SQLEvalVisitorUtils.eval(SQLEvalVisitorUtils.java:88)
	at io.mycat.calcite.executor.MycatInsertExecutor.compute(MycatInsertExecutor.java:304)
	at io.mycat.calcite.executor.MycatInsertExecutor.runNormalParams(MycatInsertExecutor.java:155)
	at io.mycat.calcite.executor.MycatInsertExecutor.<init>(MycatInsertExecutor.
```

**Comment by junwen12221** [comment]
好的

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-23/

#495
#494
#493

三个特性已经实现,上面是新的包下载地址

**Comment by imxmj** [comment]
@junwen12221 非常感谢，1.15-dev这个版本在windows下mycat连不上

` ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
jvm 1    | java.lang.IllegalAccessError: class io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf cannot access its superclass io.netty.buffer.UnpooledUnsafeHeapByteBuf
jvm 1    |      at java.lang.ClassLoader.defineClass1(Native Method)
jvm 1    |      at java.lang.ClassLoader.defineClass(Unknown Source)
jvm 1    |      at java.security.SecureClassLoader.defineClass(Unknown Source)
jvm 1    |      at java.net.URLClassLoader.defineClass(Unknown Source)
jvm 1    |      at java.net.URLClassLoader.access$100(Unknown Source)
jvm 1    |      at java.net.URLClassLoader$1.run(Unknown Source)
jvm 1    |      at java.net.URLClassLoader$1.run(Unknown Source)
jvm 1    |      at java.security.AccessController.doPrivileged(Native Method)
jvm 1    |      at java.net.URLClassLoader.findClass(Unknown Source)
jvm 1    |      at java.lang.ClassLoader.loadClass(Unknown Source)
jvm 1    |      at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
jvm 1    |      at java.lang.ClassLoader.loadClass(Unknown Source)
jvm 1    |      at io.vertx.core.buffer.impl.VertxByteBufAllocator.<clinit>(VertxByteBufAllocator.java:20)
jvm 1    |      at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:64)
jvm 1    |      at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:60)
jvm 1    |      at io.vertx.core.buffer.impl.BufferImpl.buffer(BufferImpl.java:38)
jvm 1    |      at io.vertx.core.buffer.Buffer.buffer(Buffer.java:49)
jvm 1    |      at io.mycat.vertx.VertxMySQLAuthHandler.<init>(VertxMySQLAuthHandler.java:37)
jvm 1    |      at io.mycat.vertx.VertxMycatServer$MycatSessionManager.lambda$start$0(VertxMycatServer.java:88)
jvm 1    |      at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
jvm 1    |      at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
jvm 1    |      at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123)
jvm 1    |      at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
jvm 1    |      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jvm 1    |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jvm 1    |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
jvm 1    |      at java.lang.Thread.run(Unknown Source)`

linux下启动报错
```

 WrapperSimpleApp: Encountered an error running main: io.mycat.MycatException: ERROR-CODE: [MYCAT-3036][ERR_INIT_CONFIG] start FileMetadataStorageManager fail
INFO   | jvm 1    | 2021/02/24 09:47:12 | io.mycat.MycatException: ERROR-CODE: [MYCAT-3036][ERR_INIT_CONFIG] start FileMetadataStorageManager fail
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.beans.mycat.MycatErrorCode.createMycatException(MycatErrorCode.java:142)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:193)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.MycatCore.start(MycatCore.java:147)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.MycatCore.main(MycatCore.java:154)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2021/02/24 09:47:12 | Caused by: java.util.concurrent.ExecutionException: java.sql.SQLException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.config.FileMetadataStorageManager$1.commit(FileMetadataStorageManager.java:232)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.config.FileMetadataStorageManager.start(FileMetadataStorageManager.java:191)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	... 8 more
INFO   | jvm 1    | 2021/02/24 09:47:12 | Caused by: java.sql.SQLException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:781)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:437)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.commands.MycatMySQLManager$1$1.innerExecute(MycatMySQLManager.java:120)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at io.mycat.commands.MycatMySQLManager$1$1.lambda$null$0(MycatMySQLManager.java:105)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2021/02/24 09:47:12 | 	... 1 more
STATUS | wrapper  | 2021/02/24 09:47:14 | <-- Wrapper Stopped
```
是环境问题吗？1.14release版本都ok。

**Comment by wangzihaogithub** [comment]
用 jdk1.8

**Comment by imxmj** [comment]
@wangzihaogithub 
是1.8的
linux
```
 java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```
windows
```
java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```
linux下sudo启动mycat，能正确启动，当连接到mycat时，报错跟Windows一样。

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-24/

https://www.yuque.com/ccazhw/ml3nkf/d1bfe0bd5470fa8b109043f003008fa9

**Comment by imxmj** [comment]
@junwen12221 

> http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-24/
> 
> https://www.yuque.com/ccazhw/ml3nkf/d1bfe0bd5470fa8b109043f003008fa9

这个版本也试过了，连接mycat仍然报  java.lang.IllegalAccessError 错误，测试用的jdk版本1.8.0.281 和 14.0.2，不知道是不是vertx版本问题？
https://github.com/eclipse-vertx/vert.x/blob/9d3d481fd7e3401d7d8728c7772d122cfdf9c649/src/main/java/io/vertx/core/buffer/impl/VertxByteBufAllocator.java

**Comment by junwen12221** [comment]
是的,可能是vertx的bug
