### ISSUE TITLE
关于1.15何时发布问题

### ISSUE THREAD

**Issue by imxmj** [MyCATApache/Mycat2#502]
请问一下，1.15release版本有开发的时间表吗？没有的话，这个版本发布大概在什么时候？谢谢！

**Comment by junwen12221** [comment]
暂时只发布dev版本，每日更新,1.15release要再过一周

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.15-dev/2021-2-25/

#501
以及升级了vertx到最新版
