### ISSUE TITLE
Could not find or load main class org.tanukisoftware.wrapper.WrapperSimpleApp

### ISSUE THREAD

**Issue by wangjingang** [MyCATApache/Mycat2#507]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/1faac0f0187f3dda0acfbeeb9cc6656c 可以尝试jar执行看看
