### ISSUE TITLE
20亿数据量 四台服务器 select 时速度慢

### ISSUE THREAD

**Issue by prozyworld** [MyCATApache/Mycat2#522]
我有四台服务器 做的范围分片 其中一台10亿订单数据 有一台有时大量insert数据 都是同一个逻辑表 此时用select 一条数据 速度慢到接近一秒 请问怎么回事 是需要特殊配置什么么

**Comment by prozyworld** [comment]
我发现了一个现象 explain select id from xxx where id = 1 的时候  sql语句变成了 select id from xxx where (CAST(`id` AS decimal) = 10); 这样的语句 用原生mysql查也慢 为什么会转 怎么不让他转

**Comment by prozyworld** [comment]
不仅是查询的速度 用mycat 命令行 插入一条数据 也1秒以上

**Comment by junwen12221** [comment]
io.mycat.calcite.SqlImplementor.Context#Context(org.apache.calcite.sql.SqlDialect, int)


```
        protected Context(SqlDialect dialect, int fieldCount) {
            this(dialect, fieldCount, false);
        }
```
改为true可以禁用类型转换
```
        protected Context(SqlDialect dialect, int fieldCount) {
            this(dialect, fieldCount, true);
        }
```

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/da38c2fce9fd89d39d9d0fcb53bf5d17

http://dl.mycat.org.cn/2.0/1.17-release/2021-3-26/

最新版
"ignoreCast": false //生成的sql是否忽略类型转换,1.17支持

**Comment by prozyworld** [comment]
并发插入会很慢 我用的id范围分片 id自增 我感觉是sequnece有锁的问题 这个问题有什么好的解决方式吗

**Comment by junwen12221** [comment]
设置sequence的步长大一点

**Comment by junwen12221** [comment]
1.把xa禁用
2.设置自增序列步长为1w
3.调整连接池的连接数量

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/545074ac9eadab63edbe211a7f770f64 

其中increment是序列号自增的步伐,为1的时候严格按1递增,当1000的时候,mycat会每次批量递增1000取序列号.此时在多个mycat访问此序列号表的情况下,不能严格自增

**Comment by prozyworld** [comment]
1.xa禁用在哪里 会影响到什么
2.序列步长我改过1000 但是id序列会按1000递增 1000 2000 3000 是否禁用xa会解决这个问题
3.连接池数量是否改server.json中的corePoolSize就可以了

**Comment by junwen12221** [comment]
xa禁用在哪里
https://www.yuque.com/ccazhw/ml3nkf/5cacdea3cc9ff44e67ed2375e4cd4404

如果序长不符合你的要求,就应用端生成自增id

后端连接池数量
https://www.yuque.com/ccazhw/ml3nkf/252bba43854db5766239b8edd51a751b
"maxCon": 1000

同时mysql的连接数量也要设置
