### ISSUE TITLE
为什么使用mycat2教程的自动分片算法会提示Caused by: java.lang.NumberFormatException: For input string: "{targetIndex}"？

### ISSUE THREAD

**Issue by zbb456123vb** [MyCATApache/Mycat2#526]
我用官网下载的mycat2-install-template.zip进行配置运行
1、增加了/conf/clusters/prototype.cluster.json文件名，将其命名为c0.cluster.json
2、增加了/conf/schemas/read_test.schema.json，部分内容如下:
{
	"schemaName":"read_test",
	"shadingTables":{
		"category": {
			"function": {
				"properties": {
					"dbNum": "1",
					"tableNum": "1",
					"tableMethod": "hash(id)",
					"storeNum": 1,
					"dbMethod": "hash(id)",
					"mappingFormat": "c${targetIndex}/category_${dbIndex}/category"
				}
			},
			"dataNode":{
				"targetNames":"c${targetIndex}",
				"schemaNames":"category_${dbIndex}",
				"tableNames":"category"
			}
		},
..........
}
按照官网教程的自动分片配置，但是运行不起来，查看日志提示：
Caused by: java.lang.NumberFormatException: For input string: "{targetIndex}"？
需要解决的问题：
如何配置才能让mycat2正常运行，最好能有个实际案例配置

**Comment by junwen12221** [comment]
{
"schemaName":"read_test",
"shadingTables":{
"category": {
"function": {
"properties": {
"dbNum": "1",
"tableNum": "1",
"tableMethod": "hash(id)",
"storeNum": 1,
"dbMethod": "hash(id)",
"mappingFormat": "c${targetIndex}/category_${dbIndex}/category"
}
}
}

去掉dataNode域就可以

**Comment by zbb456123vb** [comment]
现在这个问题解决了，但是又有了新的问题，提示Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'read_test'
read_test不是逻辑库，自己取的名字么，难道需要在mysql数据库创建一个？

**Comment by junwen12221** [comment]
要在原型库里面建一个

**Comment by Frenkenstein6** [comment]
Nikkiblackstar6

**Comment by zbb456123vb** [comment]
1、可以建空的作为桥梁吗，类似mycat1一样逻辑库不需要在mysql中实际表现。
2、还是说需要在每个库建立对应表，
比如mysql数据库中有read_test1数据库下面有books和category表，和class1数据库下面有students和on_class_student表。
在schemas文件夹下创建对应的read_test.schema.json和class.schema.json，目的是映射实际表

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3
