### ISSUE TITLE
mycat2执行查询返回结果出现乱码

### ISSUE THREAD

**Issue by zbb456123vb** [MyCATApache/Mycat2#528]
直接链接mysql返回没有乱码，接入mycat2查询数据库的boolean数值返回结果为[B@7ec5500e，接入mycat1.6返回结果正常为true，该如何解决？

**Comment by junwen12221** [comment]
给出配置和查询sql

**Comment by junwen12221** [comment]
建表语句和查询sql

**Comment by zbb456123vb** [comment]
create database if not exists `read_test` default character set utf8mb4 default collate utf8mb4_general_ci;
use `read_test`;
create table reader (_id bigint not null auto_increment, account_non_expired bit, account_non_locked bit) engine=innodb;
查询语句SELECT reader.account_non_expired FROM reader WHERE reader._id='1';
用可视化工具查看后，
account_non_expired在mysql的存值为1
account_non_expired在mycat2.0中的存值为00000001

**Comment by zbb456123vb** [comment]
这是mycat2.0 datasource配置
{
	"dbType":"mysql",
	"idleTimeout":60000,
	"initSqls":[],
	"initSqlsGetConnection":true,
	"instanceType":"READ_WRITE",
	"maxCon":1000,
	"maxConnectTimeout":3000,
	"maxRetryCount":5,
	"minCon":1,
	"name":"dn0",
	"password":"123456",
	"type":"JDBC",
	"url":"jdbc:mysql://172.18.0.1:3306/mysql?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8",
	"user":"root",
	"weight":0
}

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.17-release/2021-4-7/

**Comment by zbb456123vb** [comment]
谢谢，新的jar包成功解决问题
