### ISSUE TITLE
1.17版本源码本地启动失败

### ISSUE THREAD

**Issue by 15898317421** [MyCATApache/Mycat2#529]
Connected to the target VM, address: '127.0.0.1:63615', transport: 'socket'
错误: 找不到或无法加载主类 io.mycat.MycatCore
Disconnected from the target VM, address: '127.0.0.1:63615', transport: 'socket'

Process finished with exit code 1

**Comment by junwen12221** [comment]
我们本地源码与github ci构建都正常

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/actions/runs/728086717
