### ISSUE TITLE
MyCat2 连接MySQL 8 版本以上出现错误

### ISSUE THREAD

**Issue by XPPXX** [MyCATApache/Mycat2#535]
![image](https://user-images.githubusercontent.com/59997395/116222580-4e3a5e80-a781-11eb-827b-ca03f4e8a0fc.png)
![image](https://user-images.githubusercontent.com/59997395/116222751-7033e100-a781-11eb-9557-9212f956f44e.png)
![image](https://user-images.githubusercontent.com/59997395/116222862-8a6dbf00-a781-11eb-8e85-6e7af07e5fc4.png)
![image](https://user-images.githubusercontent.com/59997395/116223008-b25d2280-a781-11eb-931a-a30acff7f9c3.png)
这些事配置信息以及报错信息，这种问题有遇到过的吗，如何解决

**Comment by junwen12221** [comment]
改了root.user.json的密码了吗

**Comment by XPPXX** [comment]
好了，谢谢
