### ISSUE TITLE
navicat连接后进行各种刷新会报空指针异常的错误

### ISSUE THREAD

**Issue by XPPXX** [MyCATApache/Mycat2#536]
![image](https://user-images.githubusercontent.com/59997395/116335160-f6473a80-a808-11eb-8b83-e0dfd6eee33c.png)

**Comment by junwen12221** [comment]
哪个版本,新手请用1.17

**Comment by XPPXX** [comment]
2.18版本

**Comment by XPPXX** [comment]
用命令执行dbsesql.sql也会报空指针异常

**Comment by XPPXX** [comment]
[vertx-mycat-221] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | [vertx-mycat-222] DEBUG io.mycat.commands.MycatdbCommand - CREATE TABLE MYCAT_SEQUENCE (  name VARCHAR(64) NOT NULL,  current_value BIGINT(20) NOT NULL,  increment INT NOT NULL DEFAULT 1, PRIMARY KEY (name) ) ENGINE=InnoDB
jvm 1    | [vertx-mycat-222] ERROR io.mycat.MycatDataContext - 
jvm 1    | io.mycat.MycatException: No database selected
jvm 1    | 	at io.mycat.commands.ReceiverImpl.sendError(ReceiverImpl.java:92)
jvm 1    | 	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.lambda$onExecute$5(CreateTableSQLHandler.java:65)
jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    | 	at io.mycat.sqlhandler.ddl.CreateTableSQLHandler.onExecute(CreateTableSQLHandler.java:48)
jvm 1    | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:52)
jvm 1    | 	at io.mycat.commands.MycatdbCommand.lambda$execute$3(MycatdbCommand.java:310)
jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:297)
jvm 1    | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:169)
jvm 1    | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:162)
jvm 1    | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
jvm 1    | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
jvm 1    | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
jvm 1    | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
jvm 1    | 	at io.vertx.core.Future.compose(Future.java:199)
jvm 1    | 	at io.vertx.core.Future.flatMap(Future.java:180)
jvm 1    | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:162)
jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:545)
jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handle0(MycatVertxMySQLHandler.java:122)
jvm 1    | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handle(MycatVertxMySQLHandler.java:87)
jvm 1    | 	at io.mycat.vertx.VertxMySQLPacketResolver.handle(VertxMySQLPacketResolver.java:98)
jvm 1    | 	at io.mycat.vertx.VertxMySQLPacketResolver.handle(VertxMySQLPacketResolver.java:26)
jvm 1    | 	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:397)
jvm 1    | 	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:90)
jvm 1    | 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
jvm 1    | 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
jvm 1    | 	at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:378)
jvm 1    | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
jvm 1    | 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
jvm 1    | 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123)
jvm 1    | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [vertx-mycat-223] DEBUG io.mycat.commands.MycatdbCommand - DROP FUNCTION IF EXISTS `mycat_seq_currval`
jvm 1    | [vertx-mycat-223] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@20340656
jvm 1    | [vertx-mycat-223] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - DROP FUNCTION IF EXISTS `mycat_seq_currval`
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@20340656 com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-224] DEBUG io.mycat.commands.MycatdbCommand - CREATE FUNCTION `mycat_seq_currval`(seq_name VARCHAR(64)) RETURNS varchar(64) CHARSET latin1
jvm 1    |     DETERMINISTIC
jvm 1    | BEGIN
jvm 1    |     DECLARE retval VARCHAR(64);
jvm 1    |     SET retval="-1,0";
jvm 1    |     SELECT concat(CAST(current_value AS CHAR),",",CAST(increment AS CHAR) ) INTO retval FROM MYCAT_SEQUENCE  WHERE name = seq_name;
jvm 1    |     RETURN retval ;
jvm 1    | END
jvm 1    | [vertx-mycat-224] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@2223759c
jvm 1    | [vertx-mycat-224] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - CREATE FUNCTION `mycat_seq_currval` (
jvm 1    | 	seq_name VARCHAR(64)
jvm 1    | )
jvm 1    | RETURNS varchar(64) CHARACTER SET latin1 DETERMINISTIC
jvm 1    | BEGIN
jvm 1    | 	DECLARE retval VARCHAR(64);
jvm 1    | 	SET retval = '-1,0';
jvm 1    | 	SELECT concat(CAST(current_value AS CHAR), ',', CAST(increment AS CHAR))
jvm 1    | 	INTO retval
jvm 1    | 	FROM MYCAT_SEQUENCE
jvm 1    | 	WHERE name = seq_name;
jvm 1    | 	RETURN retval;
jvm 1    | END
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@2223759c com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-225] DEBUG io.mycat.commands.MycatdbCommand - DROP FUNCTION IF EXISTS `mycat_seq_nextval`
jvm 1    | [vertx-mycat-225] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@59c7287b
jvm 1    | [vertx-mycat-225] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - DROP FUNCTION IF EXISTS `mycat_seq_nextval`
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@59c7287b com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-226] DEBUG io.mycat.commands.MycatdbCommand - CREATE FUNCTION `mycat_seq_nextval`(seq_name VARCHAR(64)) RETURNS varchar(64) CHARSET latin1
jvm 1    |     DETERMINISTIC
jvm 1    | BEGIN
jvm 1    |     DECLARE retval VARCHAR(64);
jvm 1    |     DECLARE val BIGINT;
jvm 1    |     DECLARE inc INT;
jvm 1    |     DECLARE seq_lock INT;
jvm 1    |     set val = -1;
jvm 1    |     set inc = 0;
jvm 1    |     SET seq_lock = -1;
jvm 1    |     SELECT GET_LOCK(seq_name, 15) into seq_lock;
jvm 1    |     if seq_lock = 1 then
jvm 1    |       SELECT current_value + increment, increment INTO val, inc FROM MYCAT_SEQUENCE WHERE name = seq_name for update;
jvm 1    |       if val != -1 then
jvm 1    |           UPDATE MYCAT_SEQUENCE SET current_value = val WHERE name = seq_name;
jvm 1    |       end if;
jvm 1    |       SELECT RELEASE_LOCK(seq_name) into seq_lock;
jvm 1    |     end if;
jvm 1    |     SELECT concat(CAST((val - inc + 1) as CHAR),",",CAST(inc as CHAR)) INTO retval;
jvm 1    |     RETURN retval;
jvm 1    | END
jvm 1    | [vertx-mycat-226] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@41bd5468
jvm 1    | [vertx-mycat-226] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - CREATE FUNCTION `mycat_seq_nextval` (
jvm 1    | 	seq_name VARCHAR(64)
jvm 1    | )
jvm 1    | RETURNS varchar(64) CHARACTER SET latin1 DETERMINISTIC
jvm 1    | BEGIN
jvm 1    | 	DECLARE retval VARCHAR(64);
jvm 1    | 	DECLARE val BIGINT;
jvm 1    | 	DECLARE inc INT;
jvm 1    | 	DECLARE seq_lock INT;
jvm 1    | 	SET val = -1;
jvm 1    | 	SET inc = 0;
jvm 1    | 	SET seq_lock = -1;
jvm 1    | 	SELECT GET_LOCK(seq_name, 15)
jvm 1    | 	INTO seq_lock;
jvm 1    | 	IF seq_lock = 1 THEN
jvm 1    | 		SELECT current_value + increment, increment
jvm 1    | 		INTO (val, inc)
jvm 1    | 		FROM MYCAT_SEQUENCE
jvm 1    | 		WHERE name = seq_name
jvm 1    | 		FOR UPDATE;
jvm 1    | 		IF val != -1 THEN
jvm 1    | 			UPDATE MYCAT_SEQUENCE
jvm 1    | 			SET current_value = val
jvm 1    | 			WHERE name = seq_name;
jvm 1    | 		END IF;
jvm 1    | 		SELECT RELEASE_LOCK(seq_name)
jvm 1    | 		INTO seq_lock;
jvm 1    | 	END IF;
jvm 1    | 	SELECT concat(CAST(val - inc + 1 AS CHAR), ',', CAST(inc AS CHAR))
jvm 1    | 	INTO retval;
jvm 1    | 	RETURN retval;
jvm 1    | END
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(val, inc)
jvm 1    | 		FROM MYCAT_SEQUENCE
jvm 1    | 		WHERE name = seq_name
jvm 1    | 		FOR UPDATE;
jvm 1    | 		IF val ' at line 17
jvm 1    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
jvm 1    | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
jvm 1    | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
jvm 1    | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
jvm 1    | 	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
jvm 1    | 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:54)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@41bd5468 com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-227] DEBUG io.mycat.commands.MycatdbCommand - DROP FUNCTION IF EXISTS `mycat_seq_nextvals`
jvm 1    | [vertx-mycat-227] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@15d53d8e
jvm 1    | [vertx-mycat-227] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - DROP FUNCTION IF EXISTS `mycat_seq_nextvals`
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@15d53d8e com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-228] DEBUG io.mycat.commands.MycatdbCommand - CREATE FUNCTION `mycat_seq_nextvals`(seq_name VARCHAR(64), count INT) RETURNS VARCHAR(64) CHARSET latin1
jvm 1    |     DETERMINISTIC
jvm 1    | BEGIN
jvm 1    |     DECLARE retval VARCHAR(64);
jvm 1    |     DECLARE val BIGINT;
jvm 1    |     DECLARE seq_lock INT;
jvm 1    |     SET val = -1;
jvm 1    |     SET seq_lock = -1;
jvm 1    |     SELECT GET_LOCK(seq_name, 15) into seq_lock;
jvm 1    |     if seq_lock = 1 then
jvm 1    |         SELECT current_value + count INTO val FROM MYCAT_SEQUENCE WHERE name = seq_name for update;
jvm 1    |         IF val != -1 THEN
jvm 1    |             UPDATE MYCAT_SEQUENCE SET current_value = val WHERE name = seq_name;
jvm 1    |         END IF;
jvm 1    |         SELECT RELEASE_LOCK(seq_name) into seq_lock;
jvm 1    |     end if;
jvm 1    |     SELECT CONCAT(CAST((val - count + 1) as CHAR), ",", CAST(val as CHAR)) INTO retval;
jvm 1    |     RETURN retval;
jvm 1    | END
jvm 1    | [vertx-mycat-228] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@8d81b61
jvm 1    | [vertx-mycat-228] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - CREATE FUNCTION `mycat_seq_nextvals` (
jvm 1    | 	seq_name VARCHAR(64), 
jvm 1    | 	count INT
jvm 1    | )
jvm 1    | RETURNS VARCHAR(64) CHARACTER SET latin1 DETERMINISTIC
jvm 1    | BEGIN
jvm 1    | 	DECLARE retval VARCHAR(64);
jvm 1    | 	DECLARE val BIGINT;
jvm 1    | 	DECLARE seq_lock INT;
jvm 1    | 	SET val = -1;
jvm 1    | 	SET seq_lock = -1;
jvm 1    | 	SELECT GET_LOCK(seq_name, 15)
jvm 1    | 	INTO seq_lock;
jvm 1    | 	IF seq_lock = 1 THEN
jvm 1    | 		SELECT current_value + count
jvm 1    | 		INTO val
jvm 1    | 		FROM MYCAT_SEQUENCE
jvm 1    | 		WHERE name = seq_name
jvm 1    | 		FOR UPDATE;
jvm 1    | 		IF val != -1 THEN
jvm 1    | 			UPDATE MYCAT_SEQUENCE
jvm 1    | 			SET current_value = val
jvm 1    | 			WHERE name = seq_name;
jvm 1    | 		END IF;
jvm 1    | 		SELECT RELEASE_LOCK(seq_name)
jvm 1    | 		INTO seq_lock;
jvm 1    | 	END IF;
jvm 1    | 	SELECT CONCAT(CAST(val - count + 1 AS CHAR), ',', CAST(val AS CHAR))
jvm 1    | 	INTO retval;
jvm 1    | 	RETURN retval;
jvm 1    | END
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@8d81b61 com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-229] DEBUG io.mycat.commands.MycatdbCommand - DROP FUNCTION IF EXISTS `mycat_seq_setval`
jvm 1    | [vertx-mycat-229] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@649e08f8
jvm 1    | [vertx-mycat-229] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - DROP FUNCTION IF EXISTS `mycat_seq_setval`
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@649e08f8 com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-230] DEBUG io.mycat.commands.MycatdbCommand - CREATE FUNCTION `mycat_seq_setval`(seq_name VARCHAR(64), value BIGINT) RETURNS varchar(64) CHARSET latin1
jvm 1    |     DETERMINISTIC
jvm 1    | BEGIN
jvm 1    |     DECLARE retval VARCHAR(64);
jvm 1    |     DECLARE inc INT;
jvm 1    |     SET inc = 0;
jvm 1    |     SELECT increment INTO inc FROM MYCAT_SEQUENCE WHERE name = seq_name;
jvm 1    |     UPDATE MYCAT_SEQUENCE SET current_value = value WHERE name = seq_name;
jvm 1    |     SELECT concat(CAST(value as CHAR),",",CAST(inc as CHAR)) INTO retval;
jvm 1    |     RETURN retval;
jvm 1    | END
jvm 1    | [vertx-mycat-230] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@71cf3464
jvm 1    | [vertx-mycat-230] DEBUG io.mycat.vertxmycat.MycatVertxPreparedStatement - CREATE FUNCTION `mycat_seq_setval` (
jvm 1    | 	seq_name VARCHAR(64), 
jvm 1    | 	value BIGINT
jvm 1    | )
jvm 1    | RETURNS varchar(64) CHARACTER SET latin1 DETERMINISTIC
jvm 1    | BEGIN
jvm 1    | 	DECLARE retval VARCHAR(64);
jvm 1    | 	DECLARE inc INT;
jvm 1    | 	SET inc = 0;
jvm 1    | 	SELECT increment
jvm 1    | 	INTO inc
jvm 1    | 	FROM MYCAT_SEQUENCE
jvm 1    | 	WHERE name = seq_name;
jvm 1    | 	UPDATE MYCAT_SEQUENCE
jvm 1    | 	SET current_value = value
jvm 1    | 	WHERE name = seq_name;
jvm 1    | 	SELECT concat(CAST(value AS CHAR), ',', CAST(inc AS CHAR))
jvm 1    | 	INTO retval;
jvm 1    | 	RETURN retval;
jvm 1    | END
jvm 1    | [pool-1-thread-10] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException
jvm 1    | 	at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.extracted(RowSetJdbcPreparedJdbcQuery.java:197)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:55)
jvm 1    | 	at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
jvm 1    | 	at io.mycat.IOExecutor.lambda$executeBlocking$0(IOExecutor.java:17)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvm 1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.DefaultConnection - close com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [pool-1-thread-10] DEBUG io.mycat.datasource.jdbc.datasource.JdbcConnectionManager - close :io.mycat.datasource.jdbc.datasource.DefaultConnection@71cf3464 com.mysql.cj.jdbc.ConnectionImpl@4b08f28c
jvm 1    | [vertx-mycat-231] DEBUG io.mycat.commands.MycatdbCommand - INSERT INTO MYCAT_SEQUENCE VALUES ('GLOBAL', 1, 1)
jvm 1    | [vertx-mycat-231] ERROR io.mycat.MycatDataContext - 
jvm 1    | java.lang.NullPointerException

**Comment by junwen12221** [comment]
暂时不支持FLUSH TABLES;函数.空指针是正常的.另外dbsesql.sql不是导进mycat2里的

**Comment by XPPXX** [comment]
行吧，我以为mycat2跟MySQL执行的命令没有什么区别

**Comment by XPPXX** [comment]
![Uploading image.png…]()
