### ISSUE TITLE
Mycat2 schemaName配置问题

### ISSUE THREAD

**Issue by jeffmxzhao** [MyCATApache/Mycat2#540]
1. 使用mycat2版本:
mycat2-1.17-release-jar-with-dependencies.jar,下载链接为:http://dl.mycat.org.cn/2.0/1.17-release/2021-4-29/mycat2-1.17-release-jar-with-dependencies.jar
2. schema配置如下：
```
{
  "schemaName": "master_data",
  "normalTables": {
    "md_dict": {
      "dataNode": {
        "schemaName": "db_md",
        "tableName": "md_dict",
        "targetName": "testCluster"
      }
    }
  }
}
```
`master_data`为逻辑库，`db_md`为物理库，`testCluster`为测试集群配置
3. 问题描述：
- mycat可以正常启动
- show databases正常显示数据库
|         Database            |
|   --------------------    |
| information_schema   |
| master_data                |
| mysql                          |
| performance_schema |
- `use master_data` `show tables`时报错：
```
java.sql.SQLSyntaxErrorException: Unknown database 'master_data'
```
问题一： 逻辑`schemaName`与物理`schemaName`一致时不会报错，两者必须一样么？这样不是失去逻辑库的意义了么？
问题二： 当逻辑库与物理库名称一致时，`show tables`会把物理库中所有的表列出，而不是根据schema的配置，有什么办法只列出schema配置里面的表么？
问题三： 之前mycat`show databases`只会列出配置的库，现在`information_schema`,`mysql`,`performance_schema`也会列出来，有什么办法只列出schema配置里面的库么？

请大神们帮忙解答，谢谢！ @junwen12221

**Comment by junwen12221** [comment]
原型库的表用于处理show语句

**Comment by junwen12221** [comment]
![image](https://user-images.githubusercontent.com/11361391/117405619-80487f00-af3e-11eb-8e2a-1e15bc2cabcd.png)

**Comment by wangzihaogithub** [comment]
之前show databases 是解析配置文件内容返回的,
现在是需要你专门配置个类型为prototype的数据库, 用于返回show database的表结构, 默认和你数据库是同一个

如果你想让表结构显示或不显示, 直接改prototype数据库的表结构就行.

**Comment by jeffmxzhao** [comment]
@junwen12221 感谢您的解答，schema中的逻辑库名`schemaName`，也是对应在原型库中的么，如果物理库和逻辑库要定义成不一样，那不是所有表结构要在`prototype`中也要对应的建立一份？
@wangzihaogithub 感谢您的解答，请问是否有更新详细的关于`prototype`数据库的介绍或表结构

**Comment by junwen12221** [comment]
是的,在mycat2里,使用sql建表会自动修改prototype中的表.
入门已经写得很清楚(Mycat2权威指南第2页)[入门Mycat2](https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3)
