### ISSUE TITLE
TimeOut问题！

### ISSUE THREAD

**Issue by coder-ds** [MyCATApache/Mycat2#554]
"maxConnectTimeout":60000,
1. 这个值我在配置文件中配置了，但是还是会TimeOut。是不是还有别的配置项？导致这个值不生效，连接用的JDBC。
2. 在真实数据库下，sql文执行才几秒钟，但是连接mycat就会偶发性的出现TimeOut。

**Comment by junwen12221** [comment]
贴一下日志

**Comment by junwen12221** [comment]
暂时jdbc数据源没有读取这个属性,确定是jdbc连接时候报的连接超时的错误吗,如果是这个问题,现在可以加上这方面的代码

**Comment by junwen12221** [comment]
另外问一下,是否开启的xa事务

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies-2021-7-13.jar

基于最新代码添加连接超时功能

**Comment by coder-ds** [comment]
事务用的是Proxy，没有用到xa

TimeOut日志：
ErrorMessage: HY000com.mysql.cj.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113) at com.mysql.cj.jdbc.StatementImpl.checkCancelTimeout(StatementImpl.java:2191) at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1028) at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075) at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497) at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery.lambda$null$0(SqlResultCollectingPrepareJdbcQuery.java:50) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Unknown Source) HY000com.mysql.cj.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113) at com.mysql.cj.jdbc.StatementImpl.checkCancelTimeout(StatementImpl.java:2191) at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1028) at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075) at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497) at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery.lambda$null$0(SqlResultCollectingPrepareJdbcQuery.java:50) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Unknown Source)

ErrorType:MySql.Data.MySqlClient.MySqlException

StackTrace: at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 116 at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391 at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62 at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 257 at BLT.Data.DbHelper.ExecuteReadeAsync(CommandType cmdType, String strSql, DbParameter[] dbParameter) in C:\SFA\ReleaseSVN\BLT.Data\BLT.Data\DbHelper.cs:line 83 at BLT.Data.EF.MySqlDatabase.FindList[T](String strSql, DbParameter[] dbParameter) in C:\SFA\ReleaseSVN\BLT.Data\BLT.Data.EF\Database\MySqlDatabase.cs:line 405 at BLT.Data.Repository.Repository.FindList[T](String strSql, DbParameter[] dbParameter) in C:\SFA\ReleaseSVN\BLT.Data\BLT.Data.Repository\Repository.cs:line 152 at BLT.Service.WorkManage.OaUriageService.GetListLimit5(String name) in C:\SFA\SFA\BLT.Business\BLT.Service\WorkManage\OaUriageService.cs:line 143 at BLT.Admin.Web.Areas.WorkManage.Controllers.GlobalSearchController.GetUriageList(String name) in C:\SFA\SFA\BLT.Web\BLT.Admin.Web\Areas\WorkManage\Controllers\GlobalSearchController.cs:line 57 at lambda_method(Closure , Object ) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by junwen12221** [comment]
{
  "dbType": "mysql",
  "idleTimeout": 60000,
  "initSqls": [],
  "initSqlsGetConnection": true,
  "instanceType": "READ_WRITE",
  "maxCon": 1000,
  "maxConnectTimeout": 3000,
  "maxRetryCount": 5,
  "minCon": 1,
  "name": "prototype",
  "password": "123456",
  "type": "JDBC",
  "url": "jdbc:mysql://127.0.0.1:3306?useUnicode=true&serverTimezone=UTC",
  "user": "root",
  "weight": 0,
  "queryTimeout":30//mills
}

今年3月26号的mycat2就有queryTimeout属性,可能某次查询超过了30毫秒,导致报错,可以设置大一点,之前提到的嵌套事务问题解决了吗

**Comment by coder-ds** [comment]
之前的嵌套事务解决了，这个timeout也解决了，万分感谢！！！
建议能不能把雀语上面的文档稍微更新下，新手看起来确实有点困难。
