### ISSUE TITLE
writeBalanceName

### ISSUE THREAD

**Issue by tenderness-yang** [MyCATApache/Mycat2#555]
请问writeBalanceName如何设置对写库的负载均衡？我在cluster中添加此"writeBalanceName":"BalanceRunOnMaster",并没有生效，使用insert语句没有分发到各个写库中

**Comment by junwen12221** [comment]
它是对集群中master的列表进行负载均衡,master的列表取决于集群的类型,需要使用多主集群才可以

**Comment by tenderness-yang** [comment]
"clusterType":"GARELA_CLUSTER"  已解决，非常感谢
