### ISSUE TITLE
搭建完mycat2，配置分表schema.json，可以访问逻辑表获取分表数据，但是insert会报空指针错误

### ISSUE THREAD

**Issue by yunyayishi** [MyCATApache/Mycat2#556]
schema配置如下
{
	"customTables":{},
	"globalTables":{},
	"normalTables":{},
	"schemaName":"drivecenter",
	"shadingTables":{
		"file_info":{
			"createTableSQL":"CREATE TABLE drivecenter.`file_info` ...",
			"function":{
				"clazz":"io.mycat.router.mycat1xfunction.PartitionByFileMap",
				"properties":{
					"mapFile":"center_city_test.txt",
					"defaultNode":0,
					"type":"Integer",
					"columnName":"city_code"
				},
				"ranges":{}
			},
			"partition":{
				"schemaNames":"drivecenter",
				"tableNames":"file_info_$0-2",
				"targetNames":"prototype"
			}
		}
	}
}
使用自定义分表，center_city_test.txt内容如下：
"130100"=0
"130200"=1
"130300"=2
现在可以通过访问逻辑表获取三个分表file_info_0，file_info_1,file_info_2的汇总数据，但是通过程序向逻辑表insert数据，提示空指针错误；
 Error updating database.  Cause: java.sql.SQLException:  HY000java.lang.NullPointerException
	at io.mycat.DrdsSqlCompiler.compileInsert(DrdsSqlCompiler.java:295)
	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:178)
	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:159)
...
; nested exception is java.sql.SQLException:  HY000java.lang.NullPointerException
	at io.mycat.DrdsSqlCompiler.compileInsert(DrdsSqlCompiler.java:295)

**Comment by junwen12221** [comment]
21:46:07.400 [main] INFO io.mycat.assemble.MycatTest - /*+ mycat:resetConfig{} */
21:46:08.220 [main] INFO io.mycat.assemble.MycatTest - DROP DATABASE `1cloud`
21:46:10.996 [main] INFO io.mycat.assemble.MycatTest - CREATE DATABASE `1cloud`
21:46:11.991 [main] INFO io.mycat.assemble.MycatTest - USE `1cloud`;
21:46:12.184 [main] INFO io.mycat.assemble.MycatTest - /*+ mycat:createTable{
	"schemaName":"1cloud",
	"shadingTable":{
		"createTableSQL":"create table sharding(\nid int(11) NOT NULL AUTO_INCREMENT,\nuser_id int(11) ,\nuser_name varchar(128), \nPRIMARY KEY (`id`) \n)ENGINE=InnoDB DEFAULT CHARSET=utf8 ",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.PartitionByFileMap",
			"properties":{
				"defaultNode":"0",
				"type":"Integer",
				"columnName":"id"
			},
			"ranges":{
				"130100":"0",
				"130200":"1",
				"130300":"2"
			}
		},
		"partition":{
			"schemaNames":"c",
			"tableNames":"file_$0-2",
			"targetNames":"prototype"
		}
	},
	"tableName":"sharding"
} */;
21:46:14.717 [main] INFO io.mycat.assemble.MycatTest - delete  from `1cloud`.sharding
21:46:15.037 [main] INFO io.mycat.assemble.MycatTest - select count(1) as `count` from `1cloud`.sharding
21:46:15.109 [main] INFO io.mycat.assemble.MycatTest - insert `1cloud`.sharding (id) values (130100)
21:46:15.469 [main] INFO io.mycat.assemble.MycatTest - select count(1) as `count` from `1cloud`.sharding

参考一下

**Comment by yunyayishi** [comment]
引发写入空指针问题已找到，file_info表中有parent_id字段，insert语句去掉该字段可正常写入，增加parent_id就会引起Error updating database. Cause: java.sql.SQLException: HY000java.lang.NullPointerException；
另外：由于分表规则中city_code的值有两百多，直接写入ranges不太方便，所以设计时，想使用center_city_test.txt，单独文件来存放，不知道如何配置能解决引入第三方文件配置mapFile问题

**Comment by yunyayishi** [comment]
引发写入空指针问题已找到，字段不匹配的原因；
另外：由于分表规则中city_code的值有两百多，直接写入ranges不太方便，所以设计时，想使用center_city_test.txt，单独文件来存放，不知道如何配置能解决引入第三方文件配置mapFile问题

**Comment by junwen12221** [comment]
字段不匹配是配置的字段与数据库的表字段不相同吗

**Comment by junwen12221** [comment]
{
    "clazz": "io.mycat.router.mycat1xfunction.PartitionByFileMap",
    "name": "PartitionByFileMap",
    "properties": {
      "type": "Integer",
      "defaultNode": -1,
      "columnName": "id",
      "mapFile":"partition-hash-int.txt"
    }
  }

http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies-2021-7-20.jar

**Comment by yunyayishi** [comment]
> 字段不匹配是配置的字段与数据库的表字段不相同吗

是的，数据库里建表字段写错了，写成了parent_Id；代码里用的parent_id

**Comment by yunyayishi** [comment]
> {
> "clazz": "io.mycat.router.mycat1xfunction.PartitionByFileMap",
> "name": "PartitionByFileMap",
> "properties": {
> "type": "Integer",
> "defaultNode": -1,
> "columnName": "id",
> "mapFile":"partition-hash-int.txt"
> }
> }
> 
> http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies-2021-7-20.jar

使用以下命令行运行，java  -DMYCAT_HOME=mycat2\src\main\resources  -jar mycat2-0.5-SNAPSHOP.jar
Mycat2\mycat2\src\main\resources 是配置文件所在文件夹；请问partition-hash-int.txt应该放在哪个目录下？resource目录、jar的根目录都试过了，mapFIle提示找不到文件

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-alpha/mycat2-1.20-jar-with-dependencies-2021-7-28.jar 

启动时候注意日志中的提示,此文件夹是partition-hash-int.txt的目录
PartitionByFileMap mapFile default path:

另外也支持配置绝对路径
