### ISSUE TITLE
group by date_format(date, '%y-%m') 报错

### ISSUE THREAD

**Issue by chen-jiang-hui** [MyCATApache/Mycat2#557]
![image](https://user-images.githubusercontent.com/32922951/126415051-c97a1653-0483-4f4b-b9ad-e53cf13ae972.png)

**Comment by chen-jiang-hui** [comment]
如果指定表，是没问题的，不指定的话，就异常提示  分组字段问题

**Comment by junwen12221** [comment]
试一下使用别名

**Comment by chen-jiang-hui** [comment]
试过了，还是异常

**Comment by junwen12221** [comment]
Expression ‘t.user_id‘ is not being grouped

SELECT t.user_id FROM db1.travelrecord t GROUP BY id;

Expression 't.user_id' is not being grouped

修改成

SELECT any_value(t.user_id) FROM db1.travelrecord t GROUP BY id;

projectItem被group by的引用的无聚合函数的字段需要使用any_value

Mycat2现在支持的语法是MySQL严格模式

sql_mode常用值
 
ONLY_FULL_GROUP_BY
对于GROUP BY聚合操作，如果在SELECT中的列，没有在GROUP BY中出现，那么这个SQL是不合法的，因为列不在GROUP BY从句中

**Comment by junwen12221** [comment]
```
CREATE TABLE `1cloud`.`1log` (
  `id` BIGINT(20) DEFAULT NULL,
  `user_id` BIGINT(20) DEFAULT NULL,
  `service_id` INT(11) DEFAULT NULL,
  `submit_time` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8  dbpartition BY YYYYDD(submit_time) dbpartitions 1 tbpartition BY MOD_HASH (id) tbpartitions 1;

```

```

select any_value(submit_time) from `1log` where submit_time between '2019-5-31' and '2019-6-21' group by DATE_FORMAT(submit_time,'%Y-%m')

```

**Comment by chen-jiang-hui** [comment]
![image](https://user-images.githubusercontent.com/32922951/126451010-0bdbe203-5305-44a1-b039-c1411075793d.png)
不行

**Comment by junwen12221** [comment]
不是,把sql的字段加上any_value就可以

**Comment by chen-jiang-hui** [comment]
都试过了没啥用，对了我用的是 mysql8




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 
不是,把sql的字段加上any_value就可以

**Comment by junwen12221** [comment]
```
/*+ mycat:createCluster{
	"clusterType":"MASTER_SLAVE",
	"heartbeat":{
		"heartbeatTimeout":1000,
		"maxRetryCount":3,
		"minSwitchTimeInterval":300,
		"slaveThreshold":0.0
	},
	"masters":[
		"prototypeDs"
	],
	"maxCon":2000,
	"name":"c0",
	"readBalanceType":"BALANCE_ALL",
	"replicas":[],
	"switchType":"SWITCH"
} */;
DROP DATABASE `1cloud`
CREATE DATABASE `1cloud`
USE `1cloud`;
CREATE TABLE `1cloud`.`1log` (
  `id` BIGINT(20) DEFAULT NULL,
  `user_id` BIGINT(20) DEFAULT NULL,
  `service_id` INT(11) DEFAULT NULL,
  `submit_time` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8  dbpartition BY YYYYDD(submit_time) dbpartitions 1 tbpartition BY MOD_HASH (id) tbpartitions 1;

select any_value(submit_time) from `1log` where submit_time between '2019-5-31' and '2019-6-21' group by DATE_FORMAT(submit_time,'%Y-%m')

```

这是我的测试例子

不行的话,要把你的完整配置给我

**Comment by chen-jiang-hui** [comment]
还需要什么配置？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 /*+ mycat:createCluster{ 	"clusterType":"MASTER_SLAVE", 	"heartbeat":{ 		"heartbeatTimeout":1000, 		"maxRetryCount":3, 		"minSwitchTimeInterval":300, 		"slaveThreshold":0.0 	}, 	"masters":[ 		"prototypeDs" 	], 	"maxCon":2000, 	"name":"c0", 	"readBalanceType":"BALANCE_ALL", 	"replicas":[], 	"switchType":"SWITCH" } */; DROP DATABASE `1cloud` CREATE DATABASE `1cloud` USE `1cloud`; CREATE TABLE `1cloud`.`1log` (   `id` BIGINT(20) DEFAULT NULL,   `user_id` BIGINT(20) DEFAULT NULL,   `service_id` INT(11) DEFAULT NULL,   `submit_time` DATETIME DEFAULT NULL ) ENGINE=INNODB DEFAULT CHARSET=utf8  dbpartition BY YYYYDD(submit_time) dbpartitions 1 tbpartition BY MOD_HASH (id) tbpartitions 1; select any_value(submit_time) from `1log` where submit_time between '2019-5-31' and '2019-6-21' group by DATE_FORMAT(submit_time,'%Y-%m')  
这是我的测试例子
 
不行的话,要把你的完整配置给我

**Comment by junwen12221** [comment]
可以复现你的错误的建表语句与分片配置

**Comment by junwen12221** [comment]
以及mycat2的版本 日期

**Comment by chen-jiang-hui** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 
以及mycat2的版本 日期

**Comment by chen-jiang-hui** [comment]
有办法解决 ？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 
以及mycat2的版本 日期

**Comment by zwyqz** [comment]
最新版本验证确实是可以,您可以试下最新版本,如果还不行,提供一下配置以及建表语句,以及查询语句以便我们可以复现

**Comment by chen-jiang-hui** [comment]
这是我的mycat版本，以及部分配置
看看还有没有什么其他需要提供的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 
最新版本验证确实是可以,您可以试下最新版本,如果还不行,提供一下配置以及建表语句,以及查询语句以便我们可以复现

**Comment by zwyqz** [comment]
> 这是我的mycat版本，以及部分配置 看看还有没有什么其他需要提供的 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MyCATApache/Mycat2" ***@***.***&gt;; 发送时间:&nbsp;2021年7月22日(星期四) 上午10:35 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557) 最新版本验证确实是可以,您可以试下最新版本,如果还不行,提供一下配置以及建表语句,以及查询语句以便我们可以复现 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边看不到您提供的版本号以及建表sql

**Comment by chen-jiang-hui** [comment]
CREATE TABLE `stat_ad_sdk` (
  `ad_id` int unsigned DEFAULT NULL COMMENT '广告位id',
  `ad_uuid` varchar(50) DEFAULT NULL COMMENT '渠道广告位id',
  `ad_name` varchar(500) DEFAULT NULL COMMENT '广告位名称',
  `ad_type` varchar(50) DEFAULT NULL COMMENT '广告位类型',
  `uid` int unsigned DEFAULT NULL COMMENT '开发者id',
  `user_name` varchar(500) DEFAULT NULL COMMENT '开发者名',
  `app_id` int unsigned DEFAULT NULL COMMENT '应用id',
  `app_name` varchar(500) DEFAULT NULL COMMENT '应用名',
  `channel_id` int unsigned DEFAULT NULL COMMENT '渠道id',
  `date` date DEFAULT NULL COMMENT '日期',
  `req` int unsigned NOT NULL DEFAULT '0' COMMENT '请求量',
  `fill_rate` varchar(20) DEFAULT NULL COMMENT '填充率',
  `show` int unsigned NOT NULL DEFAULT '0' COMMENT '展示量',
  `click` int unsigned NOT NULL DEFAULT '0' COMMENT '点击量',
  `video_error` int unsigned NOT NULL DEFAULT '0' COMMENT '视频播放错误量',
  `video_not_complete` int unsigned NOT NULL DEFAULT '0' COMMENT '视频未完整播放量',
  `version` varchar(50) DEFAULT NULL COMMENT 'sdk版本',
  UNIQUE KEY `dateAdIdVer` (`date`,`ad_uuid`,`version`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='广告sdk日统计数据';


{
    "customTables":{},
    "globalTables":{},
    "normalTables":{},
    "schemaName":"test_mycat2",
    "shadingTables":{
        "stat_ad_sdk":{
            "createTableSQL":"CREATE TABLE test_mycat2.`stat_ad_sdk` (\n\t`ad_id` int(11) unsigned DEFAULT NULL COMMENT '广告位id',\n\t`ad_uuid` varchar(50) DEFAULT NULL COMMENT '渠道广告位id',\n\t`ad_name` varchar(500) DEFAULT NULL COMMENT '广告位名称',\n\t`ad_type` varchar(50) DEFAULT NULL COMMENT '广告位类型',\n\t`uid` int(11) unsigned DEFAULT NULL COMMENT '开发者id',\n\t`user_name` varchar(500) DEFAULT NULL COMMENT '开发者名',\n\t`app_id` int(10) unsigned DEFAULT NULL COMMENT '应用id',\n\t`app_name` varchar(500) DEFAULT NULL COMMENT '应用名',\n\t`channel_id` int(10) unsigned DEFAULT NULL COMMENT '渠道id',\n\t`date` date DEFAULT NULL COMMENT '日期',\n\t`req` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '请求量',\n\t`fill_rate` varchar(20) DEFAULT NULL COMMENT '填充率',\n\t`show` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '展示量',\n\t`click` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '点击量',\n\t`video_error` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '视频播放错误量',\n\t`video_not_complete` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '视频未完整播放量',\n\t`version` varchar(50) DEFAULT NULL COMMENT 'sdk版本',\n\tUNIQUE KEY `dateAdIdVer` (`date`,`ad_uuid`,`version`) USING BTREE\n\t) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告sdk日统计数据';",
            "dataNode":{
                "schemaNames":"test_mycat2",
                "tableNames":"stat_ad_sdk_$0-11",
                "targetNames":"db3308"
             },
            "function":{
                "clazz": "io.mycat.router.mycat1xfunction.PartitionByMonth",
                "name": "PartitionByMonth",
                "properties":{
                    "beginDate":"2019-01-01",
                    "endDate":"2099-12-01",
                    "dateFormat":"yyyy-MM-dd",
                    "columnName":"date"
                },
                "ranges":{}
            },
            "partition":{
                "schemaNames":"test_mycat2",
                "tableNames":"stat_ad_sdk_$0-11",
                "targetNames":"db3308"
            }
        }
    },
    "targetName":"db3308"
}


mycat version:

    BuildTime  2021-03-04 16:28:33
    GitVersion   4cf6b658c3f5a4e2d0402de5f8f8fb682fb30455
    MavenVersion 1.15-dev
    GitUrl https://github.com/MyCATApache/Mycat2.git
    MyCatSite http://www.mycat.io/
    QQGroup 332702697

**Comment by junwen12221** [comment]
最新版本没有复现这个问题
```
USE `1cloud`;
/*+ mycat:createTable{
	"schemaName":"1cloud",
	"shadingTable":{
		"createTableSQL":"CREATE TABLE stat_ad_sdk (\nad_id int unsigned DEFAULT NULL COMMENT '广告位id',\nad_uuid varchar(50) DEFAULT NULL COMMENT '渠道广告位id',\nad_name varchar(500) DEFAULT NULL COMMENT '广告位名称',\nad_type varchar(50) DEFAULT NULL COMMENT '广告位类型',\nuid int unsigned DEFAULT NULL COMMENT '开发者id',\nuser_name varchar(500) DEFAULT NULL COMMENT '开发者名',\napp_id int unsigned DEFAULT NULL COMMENT '应用id',\napp_name varchar(500) DEFAULT NULL COMMENT '应用名',\nchannel_id int unsigned DEFAULT NULL COMMENT '渠道id',\ndate date DEFAULT NULL COMMENT '日期',\nreq int unsigned NOT NULL DEFAULT '0' COMMENT '请求量',\nfill_rate varchar(20) DEFAULT NULL COMMENT '填充率',\n`show` int unsigned NOT NULL DEFAULT '0' COMMENT '展示量',\nclick int unsigned NOT NULL DEFAULT '0' COMMENT '点击量',\nvideo_error int unsigned NOT NULL DEFAULT '0' COMMENT '视频播放错误量',\nvideo_not_complete int unsigned NOT NULL DEFAULT '0' COMMENT '视频未完整播放量',\nversion varchar(50) DEFAULT NULL COMMENT 'sdk版本',\nUNIQUE KEY dateAdIdVer (date,ad_uuid,version) USING BTREE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='广告sdk日统计数据';",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.PartitionByMonth",
			"properties":{
				"beginDate":"2019-01-01",
				"endDate":"2099-12-01",
				"dateFormat":"yyyy-MM-dd",
				"columnName":"date"
			}
		},
		"partition":{
			"schemaNames":"c",
			"tableNames":"stat_ad_sdk_$0-11",
			"targetNames":"prototype"
		}
	},
	"tableName":"stat_ad_sdk"
} */;
select any_value(date) from `stat_ad_sdk` where date between '2019-5-01' and '2019-05-31' group by DATE_FORMAT(date,'%Y-%m')

```


![image](https://user-images.githubusercontent.com/11361391/126596574-bfbfa202-fe4d-4810-9825-24e12606ad12.png)

这是最新的包
http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies-2021-7-22.jar

**Comment by chen-jiang-hui** [comment]
最新版本 确实没出现那个异常


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 
最新版本没有复现这个问题
 USE `1cloud`; /*+ mycat:createTable{ 	"schemaName":"1cloud", 	"shadingTable":{ 		"createTableSQL":"CREATE TABLE stat_ad_sdk (\nad_id int unsigned DEFAULT NULL COMMENT '广告位id',\nad_uuid varchar(50) DEFAULT NULL COMMENT '渠道广告位id',\nad_name varchar(500) DEFAULT NULL COMMENT '广告位名称',\nad_type varchar(50) DEFAULT NULL COMMENT '广告位类型',\nuid int unsigned DEFAULT NULL COMMENT '开发者id',\nuser_name varchar(500) DEFAULT NULL COMMENT '开发者名',\napp_id int unsigned DEFAULT NULL COMMENT '应用id',\napp_name varchar(500) DEFAULT NULL COMMENT '应用名',\nchannel_id int unsigned DEFAULT NULL COMMENT '渠道id',\ndate date DEFAULT NULL COMMENT '日期',\nreq int unsigned NOT NULL DEFAULT '0' COMMENT '请求量',\nfill_rate varchar(20) DEFAULT NULL COMMENT '填充率',\n`show` int unsigned NOT NULL DEFAULT '0' COMMENT '展示量',\nclick int unsigned NOT NULL DEFAULT '0' COMMENT '点击量',\nvideo_error int unsigned NOT NULL DEFAULT '0' COMMENT '视频播放错误量',\nvideo_not_complete int unsigned NOT NULL DEFAULT '0' COMMENT '视频未完整播放量',\nversion varchar(50) DEFAULT NULL COMMENT 'sdk版本',\nUNIQUE KEY dateAdIdVer (date,ad_uuid,version) USING BTREE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='广告sdk日统计数据';", 		"function":{ 			"clazz":"io.mycat.router.mycat1xfunction.PartitionByMonth", 			"properties":{ 				"beginDate":"2019-01-01", 				"endDate":"2099-12-01", 				"dateFormat":"yyyy-MM-dd", 				"columnName":"date" 			} 		}, 		"partition":{ 			"schemaNames":"c", 			"tableNames":"stat_ad_sdk_$0-11", 			"targetNames":"prototype" 		} 	}, 	"tableName":"stat_ad_sdk" } */; select any_value(date) from `stat_ad_sdk` where date between '2019-5-01' and '2019-05-31' group by DATE_FORMAT(date,'%Y-%m')  

 
这是最新的包
 http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies-2021-7-22.jar

**Comment by chen-jiang-hui** [comment]
mycat2 按月分片之后，批量写入数据效率好像不是很高


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MyCATApache/Mycat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MyCATApache/Mycat2] group by date_format(date, '%y-%m') 报错 (#557)





 
最新版本没有复现这个问题
 USE `1cloud`; /*+ mycat:createTable{ 	"schemaName":"1cloud", 	"shadingTable":{ 		"createTableSQL":"CREATE TABLE stat_ad_sdk (\nad_id int unsigned DEFAULT NULL COMMENT '广告位id',\nad_uuid varchar(50) DEFAULT NULL COMMENT '渠道广告位id',\nad_name varchar(500) DEFAULT NULL COMMENT '广告位名称',\nad_type varchar(50) DEFAULT NULL COMMENT '广告位类型',\nuid int unsigned DEFAULT NULL COMMENT '开发者id',\nuser_name varchar(500) DEFAULT NULL COMMENT '开发者名',\napp_id int unsigned DEFAULT NULL COMMENT '应用id',\napp_name varchar(500) DEFAULT NULL COMMENT '应用名',\nchannel_id int unsigned DEFAULT NULL COMMENT '渠道id',\ndate date DEFAULT NULL COMMENT '日期',\nreq int unsigned NOT NULL DEFAULT '0' COMMENT '请求量',\nfill_rate varchar(20) DEFAULT NULL COMMENT '填充率',\n`show` int unsigned NOT NULL DEFAULT '0' COMMENT '展示量',\nclick int unsigned NOT NULL DEFAULT '0' COMMENT '点击量',\nvideo_error int unsigned NOT NULL DEFAULT '0' COMMENT '视频播放错误量',\nvideo_not_complete int unsigned NOT NULL DEFAULT '0' COMMENT '视频未完整播放量',\nversion varchar(50) DEFAULT NULL COMMENT 'sdk版本',\nUNIQUE KEY dateAdIdVer (date,ad_uuid,version) USING BTREE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='广告sdk日统计数据';", 		"function":{ 			"clazz":"io.mycat.router.mycat1xfunction.PartitionByMonth", 			"properties":{ 				"beginDate":"2019-01-01", 				"endDate":"2099-12-01", 				"dateFormat":"yyyy-MM-dd", 				"columnName":"date" 			} 		}, 		"partition":{ 			"schemaNames":"c", 			"tableNames":"stat_ad_sdk_$0-11", 			"targetNames":"prototype" 		} 	}, 	"tableName":"stat_ad_sdk" } */; select any_value(date) from `stat_ad_sdk` where date between '2019-5-01' and '2019-05-31' group by DATE_FORMAT(date,'%Y-%m')  

 
这是最新的包
 http://dl.mycat.org.cn/2.0/1.19-release/mycat2-1.19-jar-with-dependencies-2021-7-22.jar

**Comment by junwen12221** [comment]
后面版本会优化性能

**Comment by junwen12221** [comment]
要插入快,要使用多个存储节点,才有并行插入,只使用一个存储节点无法并行
