### ISSUE TITLE
执行安装包错误，在线等回复谢谢

### ISSUE THREAD

**Issue by realchencom** [MyCATApache/Mycat2#560]
java -Dfile.encoding=UTF-8 -DMYCAT_HOME=d:/mycat -jar mycat2-1.19-jar-with-dependencies.jar
错误: 找不到或无法加载主类 .encoding=UTF-8

在线等解决谢谢

**Comment by junwen12221** [comment]
java  -DMYCAT_HOME=d:/mycat -jar  mycat2-1.19-jar-with-dependencies.jar

**Comment by realchencom** [comment]
现在有两个问题：
问题一、下载源代码，使用idea创建build jar包，需要选择入口函数，是mycat2项目下的MycatCore吗？
问题二、使用咱们下载的 mycat2-1.19-jar-with-dependencies.jar这个包按照以上的指令执行了，但是执行到一半，需要连接mysql库，提示mysql连接错误，我是不是少看了哪些步骤？
--------------------------------------------------------------------谢谢回复！

**Comment by junwen12221** [comment]
1.是的
2.
https://www.yuque.com/ccazhw/ml3nkf/1faac0f0187f3dda0acfbeeb9cc6656c  

![image](https://user-images.githubusercontent.com/11361391/126892623-358dee7e-237f-409b-9511-a33702b2cd3a.png)

https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3

**Comment by realchencom** [comment]
对于现在mycat2 1.19是不是已经比mycat-server 第一版在性能上、功能上、兼容性上已经超越了，是不是可以直接使用mycat2了？

**Comment by junwen12221** [comment]
不是,暂时mycat2性能比1.x系列差一点,而且1.x不稳定的功能在mycat2中是没有的.

**Comment by realchencom** [comment]
@junwen12221 你好，我这两天mycat1使用 没有问题。
mycat2启动起来了，创建了一系列空的目录，和一个jar执行文件，在那里配置怎么修改配置，有些云里雾里的感觉。
![Snipaste_2021-07-26_14-30-15](https://user-images.githubusercontent.com/16587663/126943212-efea52bf-27b2-4032-85f0-d21bf44973b7.png)
还望给予指导，谢谢

**Comment by junwen12221** [comment]
按入门操作一遍

https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3
