### ISSUE TITLE
count统计居然执行union

### ISSUE THREAD

**Issue by 457775987** [MyCATApache/Mycat2#562]
很简单的一个SELECT COUNT(1) FROM medical_mycat.`scen_psn_cum_d`；一看cpu飙升，执行计划：Each(targetName=c0, sql=SELECT * FROM medical_mycat_0.scen_psn_cum_d_0 AS `scen_psn_cum_d` union all SELECT * FROM medical_mycat_0.scen_psn_cum_d_1 AS `scen_psn_cum_d` union all SELECT * FROM medical_mycat_0.scen_psn_cum_d_2 AS `scen_psn_cum_d` union all SELECT * FROM medical_mycat_0.scen_psn_cum_d_3 AS `scen_psn_cum_d` union all SELECT * FROM medical_mycat_0.scen_psn_cum_d_4 AS `scen_psn_cum_d` union all SELECT * FROM medical_mycat_0.scen_psn_cum_d_5 AS `scen_psn_cum_d`)；为什么不是32张表每个表下推而要拆分这union all，这样会出来几百万在mycat处理吧

**Comment by junwen12221** [comment]
贴一下版本,日期.

看起来是有一个优化规则失效了.是bug

**Comment by junwen12221** [comment]
看看是不是偶然失效还是一直失效

**Comment by 457775987** [comment]
一直都是这样的，刷新了很多次，版本是选的最新的，我试了一下Min 和 Max 函数都是这样，mycat2-1.19-jar-with-dependencies-2021-7-12.jar，，，，mycat2-1.20-jar-with-dependencies-2021-7-25.jar

**Comment by 457775987** [comment]
> 
> 
> 看看是不是偶然失效还是一直失效

一直都是这样的，刷新了很多次，版本是选的最新的，我试了一下Min 和 Max 函数都是这样，mycat2-1.19-jar-with-dependencies-2021-7-12.jar，，，，mycat2-1.20-jar-with-dependencies-2021-7-25.jar

**Comment by junwen12221** [comment]
看看1.18的

**Comment by junwen12221** [comment]
main分支修复了

**Comment by 457775987** [comment]
> 
> 
> main分支修复了

我试了一下1.18也有这个问题，这个分支修复是哪个版本？还是我要从源码打包

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-alpha/mycat2-1.20-jar-with-dependencies-2021-7-27-562.jar

用这个

**Comment by 457775987** [comment]
> 
> 
> http://dl.mycat.org.cn/2.0/1.20-alpha/mycat2-1.20-jar-with-dependencies-2024-7-27-562.jar
> 
> 用这个

是这个问题，解决了，不过这个jar的日期是不是错了2024年...-__-

**Comment by junwen12221** [comment]
改了
