### ISSUE TITLE
基于limit查询报错

### ISSUE THREAD

**Issue by xudanwto** [MyCATApache/Mycat2#564]
**Describe the bug**

报错信息
INFO   | jvm 1    | 2021/08/06 17:50:01 | java.sql.SQLException: Parameter index out of range (4 > number of parameters, which is 3).
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1372)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1385)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.mysql.cj.jdbc.ClientPreparedStatement.setObject(ClientPreparedStatement.java:1669)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at com.alibaba.druid.pool.DruidPooledPreparedStatement.setObject(DruidPooledPreparedStatement.java:480)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at io.mycat.calcite.executor.MycatPreparedStatementUtil.setParams(MycatPreparedStatementUtil.java:264)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at io.mycat.vertxmycat.RowSetJdbcPreparedJdbcQuery.setParams(RowSetJdbcPreparedJdbcQuery.java:132)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:52)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at io.mycat.vertxmycat.SqlResultCollectingPrepareJdbcQuery$1.handle(SqlResultCollectingPrepareJdbcQuery.java:47)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at io.mycat.IOExecutor$1VertxIOExecutor.lambda$executeBlocking$0(IOExecutor.java:54)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2021/08/06 17:50:01 |       at java.lang.Thread.run(Thread.java:748)

mycat建表语句参见附件
[conf.tar.gz](https://github.com/MyCATApache/Mycat2/files/6944798/conf.tar.gz)

**Comment by xudanwto** [comment]
执行的sql是JPA自动生成的：SELECT
 componentv0_.c_id AS c_id1_3_,
 componentv0_.alarm_num AS alarm_nu2_3_,
 componentv0_.c_camera_id AS c_camer32_3_,
 componentv0_.check_level AS check_le3_3_,
 componentv0_.check_type AS check_ty4_3_,
 componentv0_.c_component_id AS c_compo33_3_,
 componentv0_.c_content AS c_conten5_3_,
 componentv0_.d_create_time AS d_create6_3_,
 componentv0_.c_distinguish_type_id AS c_distin7_3_,
 componentv0_.c_error AS c_error8_3_,
 componentv0_.fault_content AS fault_co9_3_,
 componentv0_.c_fault_level AS c_fault10_3_,
 componentv0_.c_file_name_path AS c_file_11_3_,
 componentv0_.c_file_path AS c_file_12_3_,
 componentv0_.c_ftp_path AS c_ftp_p13_3_,
 componentv0_.c_ir_hot_image_path AS c_ir_ho14_3_,
 componentv0_.c_ir_video_image_path AS c_ir_vi15_3_,
 componentv0_.c_is_upload AS c_is_up16_3_,
 componentv0_.c_json_value AS c_json_17_3_,
 componentv0_.c_order_id AS c_order18_3_,
 componentv0_.c_org_id AS c_org_i34_3_,
 componentv0_.parameter_json AS paramet19_3_,
 componentv0_.c_patrol_id AS c_patro35_3_,
 componentv0_.c_pending_state AS c_pendi20_3_,
 componentv0_.recogn_state AS recogn_21_3_,
 componentv0_.c_ref_id AS c_ref_i22_3_,
 componentv0_.review_state AS review_23_3_,
 componentv0_.review_time AS review_24_3_,
 componentv0_.review_value AS review_25_3_,
 componentv0_.c_state AS c_state26_3_,
 componentv0_.c_tv_image_path AS c_tv_im27_3_,
 componentv0_.d_upload_time AS d_uploa28_3_,
 componentv0_.c_value AS c_value29_3_,
 componentv0_.c_value_json AS c_value30_3_,
 componentv0_.c_value_show AS c_value31_3_
FROM
 cm_component_value componentv0_
WHERE
 componentv0_.c_component_id = 'ff80808179e57c5a0179e61ccfc70c16'
AND componentv0_.d_create_time >'2021-08-04 00:00:00'
and componentv0_.d_create_time <'2021-08-05 23:59:59'
ORDER BY
 componentv0_.d_create_time DESC
LIMIT 1,100


如果改成*查询时没问题,
SELECT
 *
FROM
 cm_component_value componentv0_
WHERE
 componentv0_.c_component_id = 'ff80808179e57c5a0179e61ccfc70c16'
AND componentv0_.d_create_time >'2021-08-04 00:00:00'
and componentv0_.d_create_time <'2021-08-05 23:59:59'
ORDER BY
 componentv0_.d_create_time DESC
LIMIT 1,100

**Comment by junwen12221** [comment]
这个bug已经修复,

http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-8-6.jar

这个版本修正了配置中的拼写错误,所以配置不兼容

"shadingTables":{
		"cm_component_value":{
=>
"shardingTables":{
		"cm_component_value":{

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-8-7.jar
