### ISSUE TITLE
如何记录对数据库的所有操作？

### ISSUE THREAD

**Issue by Ji4n1ng** [MyCATApache/Mycat2#570]
如文档介绍，Mycat2会拦截了用户发送过来的SQL语句，对语句进行分析之后再发往后端的真实数据库。

那么怎么把这些语句或者操作记录下来？我尝试将log level调到debug，发现并没有记录相关信息。

或者说，我想对sql语句进行安全审计再决定是否发送给真实的数据库，那么怎么做到这一点？

感谢解答！

**Comment by junwen12221** [comment]
设置输出日志
simplelogger.properties
org.slf4j.simpleLogger.defaultLogLevel=debug
遇上配置目录不生效的情况,修改jar内的simplelogger.properties文件

自定义监控
https://www.yuque.com/ccazhw/ml3nkf/gwx15x

最后一种办法是改源码
io.mycat.commands.MycatdbCommand#execute
