### ISSUE TITLE
从mycat2更新、插入数据，数据不会同步的mysql从节点

### ISSUE THREAD

**Issue by andryzhu** [MyCATApache/Mycat2#573]
后端mysql集群构架是普通一主多从结构，使用mycat2的默认配置搭建普通主从的读写分离，不做分库分表。
集群配置如下：
'''json
{
        "clusterType":"MASTER_SLAVE",
        "heartbeat":{
                "heartbeatTimeout":1000,
                "maxRetry":3,
                "minSwitchTimeInterval":300,
                "slaveThreshold":0
        },
        "masters":[
                "prototypeDs"
        ],
        "maxCon":200,
        "name":"prototype",
        "readBalanceType":"BALANCE_ALL",
        "switchType":"SWITCH"
}
'''
数据源配置如下：
'''json
{
        "dbType":"mysql",
        "idleTimeout":60000,
        "initSqls":[],
        "initSqlsGetConnection":true,
        "instanceType":"READ_WRITE",
        "maxCon":1000,
        "maxConnectTimeout":3000,
        "maxRetryCount":5,
        "minCon":1,
        "name":"prototypeDs",
        "password":"******************",
        "type":"JDBC",
        "url":"jdbc:mysql://192.168.0.38:3307/mysql?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8",
        "user":"root",
        "weight":0
}
'''
schema配置如下：
'''json
{
        "customTables":{},
        "globalTables":{},
        "normalTables":{
                "a110":{
                        "createTableSQL":"CREATE TABLE db_test.a110 (\n\t`id` bigint NOT NULL AUTO_INCREMENT,\n\t`user_id` varchar(100) DEFAULT NULL,\n\t`traveldate` date DEFAULT NULL,\n\t`fee` decimal(10, 0)
 DEFAULT NULL,\n\t`days` int DEFAULT NULL,\n\t`blob` longblob,\n\tPRIMARY KEY (`id`),\n\tKEY `id` (`id`)\n) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARSET = utf8",
                        "locality":{
                                "schemaName":"db_test",
                                "tableName":"a110",
                                "targetName":"prototype"
                        }
                }
        },
        "schemaName":"db_test",
        "shardingTables":{},
        "targetName":"prototype",
        "views":{}
}
'''
现在问题是客户端连接到mycat2，创建表和插入数据都不会同步到mysql从库中，但通过客户端连接到mysql的主库中进行创建表和插入数据是可以同步到从库中，说明mysql的主从同步是没问题的。
请问mycat2是否有其它什么限制？

**Comment by andryzhu** [comment]
使用环境是：
mycat2: mycat2-install-template-1.20 + mycat2-1.20-jar-with-dependencies-2021-9-14.jar
 java version "1.8.0_301"
后端mysql：8.0.23

**Comment by junwen12221** [comment]
看配置,mycat中只配置了主库.可以通过explain语句,比如explain select *  from ... 查看mycat有没有改写sql,导致不同步.估计还是mysql的主从配置导致不同步的可能性大一点

**Comment by andryzhu** [comment]
> 看配置,mycat中只配置了主库.可以通过explain语句,比如explain select * from ... 查看mycat有没有改写sql,导致不同步.估计还是mysql的主从配置导致不同步的可能性大一点

我把从库配置了，使用mycat进行数据插入同样不会同步到从库中，直接在主库上进行数据插入是会同步到从库。explain INSERT into a111(user_id) VALUES(3)语句输出如下：
'''
targetName: prototype   sql: INSERT INTO `db_test`.`a111` (user_id) VALUES (3)
'''
新修改的cluster配置如下：
'''json
{
        "clusterType":"MASTER_SLAVE",
        "heartbeat":{
                "heartbeatTimeout":1000,
                "maxRetryCount":3,
                "minSwitchTimeInterval":300,
                "slaveThreshold":0.0
        },
        "masters":[
                "prototypeDs"
        ],
        "maxCon":2000,
        "name":"prototype",
        "readBalanceType":"BALANCE_ALL",
        "replicas":[
                "dr0",
                "dr1"
        ],
        "switchType":"SWITCH"
}
'''
请问mycat默认有什么规则限制吗？
