### ISSUE TITLE
在宿主主机上直接跑mycat2没有 错，放到docker中后就报错了。

### ISSUE THREAD

**Issue by dualven** [MyCATApache/Mycat2#580]
**Describe the bug**
做了一个docker，就是把mycat2的环境放到docker里。 
没有搞懂到底哪儿错了呢？

**Screenshots**
Sep 28, 2021 2:20:57 AM com.alibaba.druid.pool.DruidDataSource error
INFO   | jvm 1    | 2021/09/28 10:20:57 | SEVERE: create connection SQLException, url: jdbc:mysql://172.30.0.4:3340/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true, errorCode 0, state 08001
INFO   | jvm 1    | 2021/09/28 10:20:57 | java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2801)
INFO   | jvm 1    | 2021/09/28 10:20:57 | Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
INFO   | jvm 1    | 2021/09/28 10:20:57 |
INFO   | jvm 1    | 2021/09/28 10:20:57 | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:340)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:167)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       ... 7 more
INFO   | jvm 1    | 2021/09/28 10:20:57 | Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:428)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:317)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
INFO   | jvm 1    | 2021/09/28 10:20:57 |       at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97)
**Additional context**

**Comment by junwen12221** [comment]
创建E: create connection SQLException, url: jdbc:mysql://172.30.0.4:3340/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
失败

**Comment by zwyqz** [comment]
参考docker创建 https://www.yuque.com/ccazhw/ml3nkf/umywii

**Comment by dualven** [comment]
url":"jdbc:mysql://172.30.0.4:3340/mesh?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false",
&useSSL=false 在docker里，关键要加上这句，原理不了解。
