### ISSUE TITLE
2.0 linux.tar.gz从哪下载

### ISSUE THREAD

**Issue by oldRabbitForz** [MyCATApache/Mycat2#581]
如题

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/gnqwyv

**Comment by oldRabbitForz** [comment]
> https://www.yuque.com/ccazhw/ml3nkf/gnqwyv

![image](https://user-images.githubusercontent.com/38576501/135051525-3390f4fa-b14a-4e56-be0d-197cfb4eaf64.png)

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by junwen12221** [comment]
配置的数据源与集群配置关系不对

**Comment by oldRabbitForz** [comment]
![image](https://user-images.githubusercontent.com/38576501/135063315-17ae7bf2-0d5d-411c-8e6c-73f23a461623.png)

**Comment by oldRabbitForz** [comment]
![image](https://user-images.githubusercontent.com/38576501/135063374-4bc871ff-263b-43b0-9c16-089d0ed2cdc6.png)

**Comment by oldRabbitForz** [comment]
@junwen12221 看不出来哪不对

**Comment by oldRabbitForz** [comment]
参照文档搞的

**Comment by oldRabbitForz** [comment]
说实话，文档写的有点糙，连个实例都没有。。。。

**Comment by oldRabbitForz** [comment]
单库分表怎么配置啊

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by junwen12221** [comment]
按入门操作一遍
https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3

**Comment by oldRabbitForz** [comment]
好的，感谢

**Comment by oldRabbitForz** [comment]
现在启动了，但是navicat连不上。文档里说会默认创建一个root用户，密码是123456。如果当前库，我已经创建了root用户，且密码也设定了，不是123456。

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by zwyqz** [comment]
有默认用户root,密码123456 看看端口是否开启

**Comment by oldRabbitForz** [comment]
@zwyqz 连不上啊

**Comment by junwen12221** [comment]
换个客户端看看,或者jdbc等客户端连接

**Comment by junwen12221** [comment]
估计没有启动成功的可能性大一点

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/issues/583
