### ISSUE TITLE
springboot项目中的数据库链接给的数据库名应该是啥

### ISSUE THREAD

**Issue by oldRabbitForz** [MyCATApache/Mycat2#583]
![image](https://user-images.githubusercontent.com/38576501/135218888-751e9fbc-4752-41ed-a19d-a939b2dabdff.png)

**Comment by oldRabbitForz** [comment]
是原先的库还是要把原先的库在mycat2上再生成一遍？

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by zwyqz** [comment]
您好,建议您这边先通过入门文档操作一遍;
https://www.yuque.com/ccazhw/ml3nkf/fb2285b811138a442eb850f0127d7ea3
这样您就会知道数据库的名称应该是逻辑库名称;

**Comment by oldRabbitForz** [comment]
@zwyqz 关键文档写的我看不懂，你知道看不懂啥感觉吗

**Comment by zwyqz** [comment]
你不是部署好,跟着一步步操作就好了;不一定需要看懂;

**Comment by zwyqz** [comment]
部署好,把mycat当成mysql就好;

**Comment by zwyqz** [comment]
http://www.mycat.org.cn/document/mycat-definitive-guide 相关基本概念理解一下;

**Comment by oldRabbitForz** [comment]
@zwyqz 您辛苦了。我在新贴子态度不太好，给您道歉。但是文档里有些地方表述的稍显简单了。麻烦您再给补充补充
