### ISSUE TITLE
文档看不懂还不允许提问啊

### ISSUE THREAD

**Issue by oldRabbitForz** [MyCATApache/Mycat2#584]
文档看不懂还不允许提问啊,老关我的帖子干啥，我要是能看懂文档，我就不提问了。
@zwyqz 
@junwen12221

**Comment by oldRabbitForz** [comment]
![image](https://user-images.githubusercontent.com/38576501/135221062-c113592d-af3c-4e4b-afd4-df92c4257d24.png)

**Comment by oldRabbitForz** [comment]
密码是否可以改没说，创建db1的意图是啥，如果现有的库应该怎么对接，总不能让我再跑一遍把。逻辑库名怎么确定，怎么配置？从文档看全是疑问，你让我怎么看文档？

**Comment by oldRabbitForz** [comment]
上来就关帖子，欺负人啊

**Comment by oldRabbitForz** [comment]
我的理解是我还得把已经创建好的表在mycat的console上再执行一遍，但是没有任何东西告诉我，我应该怎么做？

**Comment by oldRabbitForz** [comment]
如果你要求创建db1,那么我是不是可以理解，我原先的库名就相当于db1?是不是可以这么理解？

**Comment by oldRabbitForz** [comment]
但是实际情况却是我连上了mycat以后，在管理工具上压根没看到我原先的库

**Comment by junwen12221** [comment]
这个入门的文档描述的是像数据库一样使用mycat2的,所以通过mycat2执行建库建表语句能自动创建物理库物理表.如果在物理库物理表已经有表的话,可以通过改配置文件让mycat知道有哪些库哪些表,可以参考下面文档

https://www.yuque.com/ccazhw/ml3nkf/00d1d4fc145edf34b2d13fcd95908722

如果遇到新的问题建议新建一个issue,而不是在一个已经解决的issue下面描述另一个问题

**Comment by oldRabbitForz** [comment]
我新建的issue，直接被zwyqz给我关了

**Comment by junwen12221** [comment]
那确实是他不对,可能是他认为这个不是问题,就把它关闭了,描述问题尽量不要带入自己的情绪

**Comment by oldRabbitForz** [comment]
抱歉，带情绪是我的不对。我新建的issue直接给我关了，文档又看不懂，却是很恼火

**Comment by junwen12221** [comment]
如果你觉得文档还不够好,可以给你权限改下
这是邀请链接

邀你加入「Mycat2权威指南」知识库: https://www.yuque.com/g/ccazhw/ml3nkf/collaborator/join?token=Lk6fEE5OTUmKi8xg# (成员)

**Comment by oldRabbitForz** [comment]
@junwen12221 谢您抬爱，我对mycat2的理解比较浅陋，等我对项目了解多一些，我会主动找您申请的。
