### ISSUE TITLE
单库分表的配置(麻烦大家帮忙看下我的配置，参照文档搞的)

### ISSUE THREAD

**Issue by oldRabbitForz** [MyCATApache/Mycat2#585]
"customTables":{},
        "globalTables":{},
        "normalTables":{
        },
        "schemaName":"xxx_log",
        "shadingTables":{
           "sxrcu_antivirus_scan": {
              "function": {
                 "properties": {
                         "dbNum": "1",//分库数量
                         "tableNum": "10",//分表数量
                         "tableMethod": "hash(id)",//分表分片函数
                         "storeNum": 1,//实际存储节点数量
                         "mappingFormat": "xx_xx_${tableIndex}"
                 }
              }
            }

        },
      "targetName":"prototype"
}
这样配置目前不起作用

**Comment by oldRabbitForz** [comment]
@zwyqz 
@junwen12221

**Comment by junwen12221** [comment]
shadingTables写错了,正确写法是shardingTables

**Comment by oldRabbitForz** [comment]
![image](https://user-images.githubusercontent.com/38576501/135233246-a49b2a57-5eb2-4dd6-994b-6d6fdf0552a5.png)
{
        "customTables":{},
        "globalTables":{},
        "normalTables":{
        },
        "schemaName":"xx_log",
        "shardingTables":{
           "xx_xx_xxx": {
             "function": {
                "properties": {
                     "tableNum": "10",//分表数量
                     "tableMethod": "hash(id)",//分表分片函数
                     "storeNum": 1,//实际存储节点数量
                     "mappingFormat": "xx_xx_xx_${tableIndex}"
                }
             }
          }
        },
      "targetName":"prototype"
}
![image](https://user-images.githubusercontent.com/38576501/135233478-bc10413d-d006-497a-991e-c1ec44e75ec1.png)

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by junwen12221** [comment]
```
{
  "customTables": {},
  "globalTables": {},
  "normalTables": {},
  "schemaName": "db1",
  "shardingTables": {
    "travelrecord": {
      "function": {
        "properties": {
          "dbNum": "1",
          "tableNum": "10",
          "tableMethod": "hash(id)",
          "storeNum": 1,
          "dbMethod": "hash(id)",
          "mappingFormat": "prototype/db1/travelrecord_${tableIndex}"
        }
      }
    }
  }
}
```

```
/*+ mycat:showTopology{
  "schemaName":"db1",
  "tableName":"travelrecord"
} */;

```

![image](https://user-images.githubusercontent.com/11361391/135235359-b654ccaa-6c4e-4026-8c6d-cb4ecc88af09.png)

把对应表名改了

**Comment by oldRabbitForz** [comment]
感谢大佬
