### ISSUE TITLE
mycat2 mongodb 不支持 转化为mongodb api

### ISSUE THREAD

**Issue by 5dprince** [MyCATApache/Mycat2#588]
mycat2 mongodb 不支持 转化为mongodb api

**Comment by junwen12221** [comment]
暂时没有这个计划,有兴趣可以贡献这个模块

**Comment by 5dprince** [comment]
https://www.modb.pro/db/60083  好像之前1.x版本是支持的 

![image](https://user-images.githubusercontent.com/8513521/136904580-0cd6b026-7ad6-48fa-8e51-0f526188f8ac.png)

**Comment by 5dprince** [comment]
> 暂时没有这个计划,有兴趣可以贡献这个模块

是mycat2 舍弃这个功能了吗

**Comment by junwen12221** [comment]
支持mongodb并不难,只是暂时开发重点不在这块,以后有时间,同时这个功能很多人需要,就会实现.
