### ISSUE TITLE
ERROR io.mycat.vertx.VertxMycatServer - Mycat Vertx server exit. because: Cannot assign requested address

### ISSUE THREAD

**Issue by HeartsK** [MyCATApache/Mycat2#592]
mycat2 start report this ERROR io.mycat.vertx.VertxMycatServer - Mycat Vertx server exit. because: Cannot assign requested address,anyone know how to deal this error ,thank you.

**Comment by junwen12221** [comment]
Is an error reported when Mycat2 starts?

Maybe the Linux port has been exhausted.

try changing the configuration

```
# vi /etc/sysctl.conf
net.ipv4.ip_local_port_range = 1024     65535
```

**Comment by HeartsK** [comment]
is still report error, logs like this
[vert.x-acceptor-thread-0] ERROR io.vertx.core.impl.future.FutureImpl - 
INFO   | jvm 1    | 2021/10/22 14:33:37 | java.net.BindException: Cannot assign requested address
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at sun.nio.ch.Net.bind(Net.java:433)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at sun.nio.ch.Net.bind(Net.java:425)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:428)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:377)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:488)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
INFO   | jvm 1    | 2021/10/22 14:33:37 | 	at java.lang.Thread.run(Thread.java:748)

**Comment by junwen12221** [comment]
The IP has been occupied. Please kill the old mycat or change the IP

```
{
  "loadBalance":{
    "defaultLoadBalance":"BalanceRandom",
    "loadBalances":[]
  },
  "mode":"local",
  "properties":{},
  "server":{
    "bufferPool":{

    },
    "idleTimer":{
      "initialDelay":3,
      "period":60000,
      "timeUnit":"SECONDS"
    },
    "ip":"0.0.0.0",
    "mycatId":1,
    "port":8066,
```

 "ip":"0.0.0.0",
    "port":8066,

**Comment by HeartsK** [comment]
thank you, it's ok to start,but i can't find the database which i set, the link just has three databases  mysql, information_schema, performance_schema, what i need do to deal this question.

**Comment by HeartsK** [comment]
thank you i have deal with it
