### ISSUE TITLE
is mycat2 can't support sql grammar like this SELECT REPLACE(UUID(),'-','')

### ISSUE THREAD

**Issue by HeartsK** [MyCATApache/Mycat2#596]
Error selecting key or setting result to parameter object. Cause: java.sql.SQLException:  HY000java.lang.IllegalStateException: Unable to implement MycatProject(REPLACE(UUID(),?,?)=[REPLACE(UUID(), ?0, ?1)]): rowcount = 1.0, cumulative cost = {2.0 rows, 2.0 cpu, 0.0 io}, id = 124

**Comment by junwen12221** [comment]
I guess is that the UUID function is not supported, temporarily

**Comment by junwen12221** [comment]
Can you give the  SQL?

**Comment by HeartsK** [comment]
use sql like this insert into xxx (id,xx) values ((REPLACE(UUID(),'-',''),xx)

**Comment by junwen12221** [comment]
id is a sharding key?

**Comment by junwen12221** [comment]
sharding(partition) key does not support calculate.

**Comment by HeartsK** [comment]
no, i didn't use the sharding function

**Comment by HeartsK** [comment]
Is mycat2 whether default user primary key to sharding?

**Comment by junwen12221** [comment]
Do you use  ORM frameworks?
It does not behave like an insert statement.

**Comment by junwen12221** [comment]
I guess the sql is 

`select  (REPLACE(UUID(),'-','')`

**Comment by junwen12221** [comment]
If you confirm that the SQL is this, I can fix this problem.

**Comment by HeartsK** [comment]
< selectKey keyProperty="Id" order="BEFORE" resultType="java.lang.String" >
      SELECT REPLACE(UUID(),'-','')
    </ selectKey >
insert into xxx
< trim prefix="(" suffix=")" suffixOverrides="," >
Id,<if ......>
</ trim >
< trim prefix="(" suffix=")" suffixOverrides="," >
#{ Id },< if ...... >
</ trim >

**Comment by HeartsK** [comment]
sql like the last

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-10-26.jar

https://github.com/MyCATApache/Mycat2/commit/68b2181d8319ba31376a777cb9faec8ff7ecad5e
