### ISSUE TITLE
DATE_SUB报错

### ISSUE THREAD

**Issue by oldRabbitForz** [MyCATApache/Mycat2#599]
Future{cause=while converting DATE_SUB(`NOW`(), INTERVAL '1' MONTH)}"}

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by oldRabbitForz** [comment]
里面的1在代码里是数字

**Comment by junwen12221** [comment]
https://github.com/MyCATApache/Mycat2/commit/3337f5ea2f0416fa1e05a2818cd9daecb960abde

http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-11-2.jar

遇上启动不了把这个文件放在conf文件夹下
http://dl.mycat.org.cn/2.0/install-template/logback.xml

**Comment by oldRabbitForz** [comment]
Cause: java.sql.SQLException: Future{cause=Line 103, Column 137: No applicable constructor/method found for actual parameters \"io.reactivex.rxjava3.core.Observable\"; candidates are: \"public org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.DefaultEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\", \"public abstract org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.ExtendedEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\", \"public abstract org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.ExtendedEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\"}\n; uncategorized SQLException; SQL state [HY000]; error code [0]; Future{cause=Line 103, Column 137: No applicable constructor/method found for actual parameters \"io.reactivex.rxjava3.core.Observable\"; candidates are: \"public org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.DefaultEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\", \"public abstract org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.ExtendedEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\", \"public abstract org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.ExtendedEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\"}; nested exception is java.sql.SQLException: Future{cause=Line 103, Column 137: No applicable constructor/method found for actual parameters \"io.reactivex.rxjava3.core.Observable\"; candidates are: \"public org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.DefaultEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\", \"public abstract org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.ExtendedEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\", \"public abstract org.apache.calcite.linq4j.Enumerable org.apache.calcite.linq4j.ExtendedEnumerable.concat(org.apache.calcite.linq4j.Enumerable)\"}"

**Comment by oldRabbitForz** [comment]
.sql.SQLException: Future{cause=java.sql.SQLException: Can not read response from server. Expected to read 238 bytes, read 12 bytes before connection was unexpectedly lost.

**Comment by oldRabbitForz** [comment]
uncategorized SQLException; SQL state [HY000]; error code [0]; Future{cause=Self-suppression not permitted}; nested exception is java.sql.SQLException: Future{cause=Self-suppression not permitted}"

**Comment by oldRabbitForz** [comment]
@junwen12221

**Comment by oldRabbitForz** [comment]
老哥，你的线程锁似乎影响到我其他线程池里的线程了

**Comment by oldRabbitForz** [comment]
如果某个慢sql不返回直接给我定时任务的线程给干停了

**Comment by oldRabbitForz** [comment]
怎么禁用啊，不然我这业务彻底凉凉了

**Comment by oldRabbitForz** [comment]
老哥，这是我的微信，我们直接微信沟通把，415572600

**Comment by oldRabbitForz** [comment]
还有group by语句是不是可以根据一个字段去group by ,不用把查询的字段全列上去

**Comment by oldRabbitForz** [comment]
我又测试了下，我的定时任务在没有慢sql的情况下运行一段时间会自动停掉。线程池处理还是有问题

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-11-2.jar
http://dl.mycat.org.cn/2.0/1.21-alpha/mycat2-1.21-aplha-jar-with-dependencies-2021-11-2.jar

这两个都有解决union all支持的问题

还有group by语句是不是可以根据一个字段去group by ,不用把查询的字段全列上去
group by的键一般要在select里写清楚
