### ISSUE TITLE
期望Mycat2支持/*+mycat:schema=ds2*/select* from test;

### ISSUE THREAD

**Issue by LiXueCai** [MyCATApache/Mycat2#604]

**Comment by junwen12221** [comment]
可以

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.20-release/mycat2-1.20-jar-with-dependencies-2021-11-21.jar

http://dl.mycat.org.cn/2.0/1.21-alpha/mycat2-1.21-aplha-jar-with-dependencies-2021-11-21.jar
