### ISSUE TITLE
每次启动都会初始化配置文件

### ISSUE THREAD

**Issue by mark420524** [MyCATApache/Mycat2#610]
**Describe the bug**
每次启动都会初始化配置文件
第一次为空初始化成功，修改了配置，第二次还是会初始化
**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="580" alt="bug" src="https://user-images.githubusercontent.com/7982108/144354381-38312a9d-01be-48b2-81e7-96708aaa6b9f.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by junwen12221** [comment]
好的
