### ISSUE TITLE
设置"clusterType":"MGR" 心跳不会根据read_only状态来切换主从

### ISSUE THREAD

**Issue by anson88616425** [MyCATApache/Mycat2#612]
设置"clusterType":"MGR" 心跳不会根据read_only状态来切换主从
![1639475204(1)](https://user-images.githubusercontent.com/11780232/145974129-06480bb5-9a70-483a-bd0f-966debe69570.jpg)

**Comment by junwen12221** [comment]
下个小版本修复

**Comment by junwen12221** [comment]
```
SELECT (SELECT MEMBER_STATE FROM performance_schema.replication_group_members WHERE member_id=@@server_uuid) AS `MEMBER_STATE`,
(SELECT TRUE FROM performance_schema.global_variables WHERE variable_name IN ('read_only', 'super_read_only') AND VARIABLE_VALUE = 'ON' LIMIT 1) AS `READ_ONLY`,
(SELECT (Received_transaction_set-@@gtid_executed) FROM performance_schema.replication_connection_status WHERE Channel_name = 'group_replication_applier') AS `BEHIND`

```
可否提供一下,MGR 主从执行这个sql的结果

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies.jar

**Comment by anson88616425** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies.jar
设置"readBalanceType":"BALANCE_ALL_READ"不会把查询平均到每个从库。
![image](https://user-images.githubusercontent.com/11780232/146182552-b280b7b5-e85a-43b6-adf4-8f21dea22df2.png)

**Comment by junwen12221** [comment]
更新文档
https://www.yuque.com/ccazhw/ml3nkf/6fcb04592f6c08423f0041efb188963c
看看readBalanceName此处是否能调整

是完全不能路由到从库还是从库负载不均匀?
