### ISSUE TITLE
navicat编辑表结构报错

### ISSUE THREAD

**Issue by anson88616425** [MyCATApache/Mycat2#621]
背景：
我用mycat2连接mysqlrouter
![image](https://user-images.githubusercontent.com/11780232/146909384-eac0f677-dd38-4a79-b120-25eb0f9dc3ea.png)

**Comment by junwen12221** [comment]
打开jar把里面的logback的info改成debug,再复现这个错误,查看日志,把错误的sql贴到这里

**Comment by anson88616425** [comment]
> 打开jar把里面的logback的info改成debug,再复现这个错误,查看日志,把错误的sql贴到这里

INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.SqlCall.unparse(SqlCall.java:104)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.calcite.sqlfunction.stringfunction.BinaryFunction.unparse(BinaryFunction.java:46)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 2021-12-22 08:56:54,476[ERROR]io.mycat.DrdsSqlCompiler.getRelRoot:402sqlStatement:SELECT ACTION_ORDER AS ACTION_ORDER, EVENT_OBJECT_TABLE AS EVENT_OBJECT_TABLE, TRIGGER_NAME AS TRIGGER_NAME, EVENT_MANIPULATION AS EVENT_MANIPULATION, EVENT_OBJECT_TABLE AS EVENT_OBJECT_TABLE
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	, DEFINER AS DEFINER, ACTION_STATEMENT AS ACTION_STATEMENT, ACTION_TIMING AS ACTION_TIMING
INFO   | jvm 1    | 2021/12/22 08:56:54 | FROM information_schema.triggers
INFO   | jvm 1    | 2021/12/22 08:56:54 | WHERE BINARY event_object_schema = ?
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	AND BINARY event_object_table = ?
INFO   | jvm 1    | 2021/12/22 08:56:54 | ORDER BY event_object_table sqlNode:[FAILED toString()] validated:null root:null newRelNode:null
INFO   | jvm 1    | 2021/12/22 08:56:54 | 2021-12-22 08:56:54,500[ERROR]io.mycat.sqlhandler.ShardingSQLHandler.onExecute:56SELECT ACTION_ORDER, EVENT_OBJECT_TABLE, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	, DEFINER, ACTION_STATEMENT, ACTION_TIMING
INFO   | jvm 1    | 2021/12/22 08:56:54 | FROM information_schema.triggers
INFO   | jvm 1    | 2021/12/22 08:56:54 | WHERE BINARY event_object_schema = 'test1'
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	AND BINARY event_object_table = 'test1'
INFO   | jvm 1    | 2021/12/22 08:56:54 | ORDER BY event_object_table
INFO   | jvm 1    | 2021/12/22 08:56:54 | org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: Column 'event_object_table' is ambiguous
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:886)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:871)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5004)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.OrderByScope.fullyQualify(OrderByScope.java:84)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5900)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5885)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:320)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.expand(SqlValidatorImpl.java:5494)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateOrderList(SqlValidatorImpl.java:3915)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3441)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1064)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1038)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1013)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:721)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.DrdsSqlCompiler.getRelRoot(DrdsSqlCompiler.java:396)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.DrdsSqlCompiler.compileQuery(DrdsSqlCompiler.java:330)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:219)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:211)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.calcite.spm.MemPlanCache.add(MemPlanCache.java:182)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.calcite.spm.QueryPlanner.getAcceptedMycatRelList(QueryPlanner.java:69)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.calcite.spm.QueryPlanner.innerComputeMinCostCodeExecuterContext(QueryPlanner.java:28)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.calcite.DrdsRunnerHelper.getPlan(DrdsRunnerHelper.java:351)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.calcite.DrdsRunnerHelper.runOnDrds(DrdsRunnerHelper.java:339)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.sqlhandler.ShardingSQLHandler.onExecute(ShardingSQLHandler.java:53)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:456)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:424)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:190)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:186)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:186)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:574)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:136)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:33)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2021/12/22 08:56:54 | Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Column 'event_object_table' is ambiguous
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:560)
INFO   | jvm 1    | 2021/12/22 08:56:54 | 	... 52 common frames omitted

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2021-12-22.jar
已经修复

```
SELECT ACTION_ORDER, EVENT_OBJECT_TABLE, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE
 , DEFINER, ACTION_STATEMENT, ACTION_TIMING
 FROM information_schema.triggers
 WHERE BINARY event_object_schema = 'test1'
 AND BINARY event_object_table = 'test1'
 ORDER BY event_object_table

问题的原因是sql不规范,EVENT_OBJECT_TABLE出现了两次,不知道该排序哪个

```
