### ISSUE TITLE
mysql maxAllowedPacket配置不生效

### ISSUE THREAD

**Issue by wangsenyan** [MyCATApache/Mycat2#622]
直连的时候，不会报错
使用mycat2时候，会提示
```sh
### Error querying database. Cause: com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (6,190,132 > 4,194,304)
```

**Comment by junwen12221** [comment]
这个是哪个mysql驱动版本,你是在mysql驱动上面设置了maxAllowedPacket参数吗,为什么要设置这个参数

**Comment by wangsenyan** [comment]
在application.properties中配置的
mysql上参数足够大
需要批量保存数据

**Comment by junwen12221** [comment]
业务需要是需要保存的数据大于16mb吗

**Comment by junwen12221** [comment]
![image](https://user-images.githubusercontent.com/11361391/147827949-def6e31b-ff53-46cc-845b-8f506db653e0.png)

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-networking.html

`
	"url":"jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&maxAllowedPacket=666666",
`

在mycat2的数据源jdbc字符串添加maxAllowedPacket属性可以避免这个问题

**Comment by wangsenyan** [comment]
谢谢
