### ISSUE TITLE
范围分区不生效

### ISSUE THREAD

**Issue by hongshenghome** [MyCATApache/Mycat2#633]
1.过程描述
 /*+ mycat:createTable{
	"schemaName":"db3",
	"shardingTable":{
		"createTableSQL":"create table address3(\nid int(11) NOT NULL AUTO_INCREMENT,\nuser_id int(11) ,\nuser_name varchar(128), \nPRIMARY KEY (`id`) \n)ENGINE=InnoDB DEFAULT CHARSET=utf8 ",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.AutoPartitionByLong",
			  "properties": {
                             "type":"Long",
      	"defaultNode": 1,
     	 "columnName": "id",
  "mapFile":"/usr/local/mycat2/conf/partition-range-int.txt"
    }
		},
		"partition":{
			"schemaNames":"db3",
			"tableNames":"addr3_$0-2",
			"targetNames":"prototype"
		}
	},
	"tableName":"address3"
} */;

cat /usr/local/mycat2/conf/partition-range-int.txt
0-1000=0
1001-2000=1
2001-3000=2

 insert into address3(id,user_id,user_name) values(1,1,'aaa');
insert into address3(id,user_id,user_name) values(1000,5,'ddd');
insert into address3(id,user_id,user_name) values(1001,1,'aaa');
insert into address3(id,user_id,user_name) values(2000,1,'aaa');
insert into address3(id,user_id,user_name) values(2001,3,'bbb');
insert into address3(id,user_id,user_name) values(3000,5,'ccc');
insert into address3(id,user_id,user_name) values(3001,1,'aaa');

2.错误描述：
如下查询，数据都插入到了默认节点1上，其他节点没数据
mysql> select * from addr3_0;
Empty set (0.00 sec)

mysql> select * from addr3_1;
+------+---------+-----------+
| id   | user_id | user_name |
+------+---------+-----------+
|    1 |       1 | aaa       |
| 1000 |       5 | ddd       |
| 1001 |       1 | aaa       |
| 2000 |       1 | aaa       |
| 2001 |       3 | bbb       |
| 3000 |       5 | ccc       |
| 3001 |       1 | aaa       |
+------+---------+-----------+
7 rows in set (0.00 sec)

mysql> select * from addr3_2;
Empty set (0.00 sec)

3.mycat版本
mycat2 版本1.21

**Comment by junwen12221** [comment]
```
/*+ mycat:createTable{
"schemaName":"db1",
"shardingTable":{
"createTableSQL":"create table address3(\nid int(11) NOT NULL AUTO_INCREMENT,\nuser_id int(11) ,\nuser_name varchar(128), \nPRIMARY KEY (id) \n)ENGINE=InnoDB DEFAULT CHARSET=utf8 ",
"function":{
"clazz":"io.mycat.router.mycat1xfunction.AutoPartitionByLong",
"properties": {
"type":"Long",
"defaultNode": 1,
"columnName": "id",
},
 "ranges": {
      "0-1000":0,
      "1001-2000":1,
	"2001-3000":2
    }
},
"partition":{
"schemaNames":"db3",
"tableNames":"addr3_$0-2",
"targetNames":"prototype"
}
},
"tableName":"address3"
} */;
```

**Comment by hongshenghome** [comment]
已解决，非常感谢！
