### ISSUE TITLE
取模范围分片，数据无法插入

### ISSUE THREAD

**Issue by hongshenghome** [MyCATApache/Mycat2#634]
/*+ mycat:createTable{
	"schemaName":"db3",
	"shardingTable":{
		"createTableSQL":"create table address4(\nid int(11) NOT NULL AUTO_INCREMENT,\nuser_id int(11) ,\nuser_name varchar(128), \nPRIMARY KEY (`id`) \n)ENGINE=InnoDB DEFAULT CHARSET=utf8 ",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.PartitionByPattern",
			"properties":{
                                "type":"Integer",
    "patternValue": 256,
      "defaultNode": 1,
      "columnName": "id"
			}
		},
 "ranges": {
      "1-32": 0,
      "33-64": 1,
      "65-72": 2
    },
		"partition":{
			"schemaNames":"db3",
			"tableNames":"addr4_$0-2",
			"targetNames":"prototype",

		}
	},
	"tableName":"address4"
} */;

建表成功后，插入数据报错：
insert into address4(id,user_id,user_name) values(257,3,'bbb')
> 0 - Future{cause=路由计算返回结果个数为3}
> 时间: 0.001s

INFO   | jvm 1    | 2022/01/05 13:27:41 | java.lang.IllegalArgumentException: 路由计算返回结果个数为3
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.router.CustomRuleFunction.calculateOne(CustomRuleFunction.java:45)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.vertx.VertxExecuter.lambda$explainInsert$12(VertxExecuter.java:435)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.Collections$2.tryAdvance(Collections.java:4717)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.Collections$2.forEachRemaining(Collections.java:4725)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.vertx.VertxExecuter.explainInsert(VertxExecuter.java:465)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.calcite.plan.ObservablePlanImplementorImpl.executeInsert(ObservablePlanImplementorImpl.java:66)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.calcite.DrdsRunnerHelper.impl(DrdsRunnerHelper.java:341)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.sqlhandler.dml.UpdateSQLHandler.executeUpdate(UpdateSQLHandler.java:160)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:140)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:457)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:425)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:190)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:186)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:186)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:574)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$1(MycatVertxMySQLHandler.java:136)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:33)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/01/05 13:27:41 |       at java.lang.Thread.run(Thread.java:748)

**Comment by junwen12221** [comment]
原sql中的json格式有问题导致配置读取失败

```
/*+ mycat:createTable{
	"schemaName":"db1",
	"shardingTable":{
		"createTableSQL":"create table address4(\nid int(11) NOT NULL AUTO_INCREMENT,\nuser_id int(11) ,\nuser_name varchar(128), \nPRIMARY KEY (`id`) \n)ENGINE=InnoDB DEFAULT CHARSET=utf8 ",
		"function":{
			"clazz":"io.mycat.router.mycat1xfunction.PartitionByPattern",
			"properties":{
                                "type":"Integer",
    "patternValue": 256,
      "defaultNode": 1,
      "columnName": "id"
		
		},
 "ranges": {
      "1-32": 0,
      "33-64": 1,
      "65-72": 2
    }
    },
		"partition":{
			"schemaNames":"db3",
			"tableNames":"addr4_$0-2",
			"targetNames":"prototype",

		}
	},
	"tableName":"address4"
} */;
```

**Comment by hongshenghome** [comment]
已解决，谢谢
