### ISSUE TITLE
maycat2 not start

### ISSUE THREAD

**Issue by wangze-TIM** [MyCATApache/Mycat2#638]
centos7 
jdk:
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

STATUS | wrapper  | 2022/01/13 19:16:54 | Launching a JVM...
INFO   | jvm 3    | 2022/01/13 19:16:54 | Error: Could not find or load main class 
ERROR  | wrapper  | 2022/01/13 19:16:54 | JVM exited while loading the application.
STATUS | wrapper  | 2022/01/13 19:16:56 | INT trapped.  Shutting down.
STATUS | wrapper  | 2022/01/13 19:16:56 | <-- Wrapper Stopped
STATUS | wrapper  | 2022/01/13 19:19:21 | --> Wrapper Started as Daemon
WARN   | wrapper  | 2022/01/13 19:19:21 | The value of property 'wrapper.java.additional.10', './conf/logback.xml' is not a valid argument to the jvm.  Skipping.
STATUS | wrapper  | 2022/01/13 19:19:21 | Launching a JVM...
INFO   | jvm 1    | 2022/01/13 19:19:21 | Error: Could not find or load main class 
ERROR  | wrapper  | 2022/01/13 19:19:22 | JVM exited while loading the application.
WARN   | wrapper  | 2022/01/13 19:19:26 | The value of property 'wrapper.java.additional.10', './conf/logback.xml' is not a valid argument to the jvm.  Skipping.
STATUS | wrapper  | 2022/01/13 19:19:26 | Launching a JVM...
INFO   | jvm 2    | 2022/01/13 19:19:26 | Error: Could not find or load main class 
ERROR  | wrapper  | 2022/01/13 19:19:26 | JVM exited while loading the application.
WARN   | wrapper  | 2022/01/13 19:19:30 | The value of property 'wrapper.java.additional.10', './conf/logback.xml' is not a valid argument to the jvm.  Skipping.
STATUS | wrapper  | 2022/01/13 19:19:30 | Launching a JVM...
INFO   | jvm 3    | 2022/01/13 19:19:30 | Error: Could not find or load main class 
ERROR  | wrapper  | 2022/01/13 19:19:31 | JVM exited while loading the application.
WARN   | wrapper  | 2022/01/13 19:19:35 | The value of property 'wrapper.java.additional.10', './conf/logback.xml' is not a valid argument to the jvm.  Skipping.
STATUS | wrapper  | 2022/01/13 19:19:35 | Launching a JVM...
INFO   | jvm 4    | 2022/01/13 19:19:35 | Error: Could not find or load main class 
ERROR  | wrapper  | 2022/01/13 19:19:35 | JVM exited while loading the application.
WARN   | wrapper  | 2022/01/13 19:19:39 | The value of property 'wrapper.java.additional.10', './conf/logback.xml' is not a valid argument to the jvm.  Skipping.
STATUS | wrapper  | 2022/01/13 19:19:39 | Launching a JVM...
INFO   | jvm 5    | 2022/01/13 19:19:40 | Error: Could not find or load main class 
ERROR  | wrapper  | 2022/01/13 19:19:40 | JVM exited while loading the application.
FATAL  | wrapper  | 2022/01/13 19:19:40 | There were 5 failed launches in a row, each lasting less than 300 seconds.  Giving up.
FATAL  | wrapper  | 2022/01/13 19:19:40 |   There may be a configuration problem: please check the logs.
STATUS | wrapper  | 2022/01/13 19:19:40 | <-- Wrapper Stopped

**Comment by junwen12221** [comment]
open wrapper.conf and remove  wrapper.java.additional.10=./conf/logback.xml

**Comment by wangze-TIM** [comment]
ok
