### ISSUE TITLE
mycat官网打不开了吗？

### ISSUE THREAD

**Issue by zwb0619** [MyCATApache/Mycat2#643]
www.mycat.org.cn
mycat.io
都打不开是怎么回事？
要下载安装包去哪里下？

全部都是dns错误，没法解析

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/1faac0f0187f3dda0acfbeeb9cc6656c

**Comment by tianxing-ovo** [comment]
停止维护了
