### ISSUE TITLE
mycat2 多租户模式切换数据库如何处理？

### ISSUE THREAD

**Issue by dengxixian008** [MyCATApache/Mycat2#644]
请问下在mycat2中多租户模式要如何处理？
在1.6版本中是在mybatis拦截器中使用 /*!mycat:schema= XXX */ SQL 来进行选择具体租户对应的数据库；
在2.0版本中使用该 注释 已经不能使用了，在Navicat中执行sql会报错，报错如下：
![image](https://user-images.githubusercontent.com/38934189/153156863-d970d682-1c9e-4f07-8749-4c3c8eb01a90.png)

在2.0版本中应该如何处理呢？

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/won7av

/*+mycat:schema=ds2*/是语句作用的注释,实现不通过use schema临时修改当前的schema

select DATABASE();//mysql库
/*+mycat:schema=ds2*/select DATABASE()");//ds2
select DATABASE();//恢复到mysql库

1.6没有遇到问题,不需要换mycat2
