### ISSUE TITLE
关于全局序列号自增id,是否有指定插入自增id后更新全局序列自增id的功能

### ISSUE THREAD

**Issue by Degree-21** [MyCATApache/Mycat2#651]
当设置全局序列自增id,
![image](https://user-images.githubusercontent.com/48709222/159405464-cc358c05-460e-4f76-9d40-661c1f9f9d20.png)
插入时可以进行id 自增 
![image](https://user-images.githubusercontent.com/48709222/159405561-23345104-deb2-4d29-8931-b54dd424c0e1.png)
当我使用sql 语句进行设置id时, 指定id为7000 ，全局序列表是否能够更新为7000
![image](https://user-images.githubusercontent.com/48709222/159405614-24e6e322-3a63-41d7-9c24-fef47685c939.png)

**Comment by zwyqz** [comment]
需要同事修改全局序列的current_value；然后重启所有的mycat；

**Comment by Degree-21** [comment]
我是不是可以理解成，把 current_value 设置为超过数据迁移最大的自增id，就不需要重启。

**Comment by zwyqz** [comment]
可以

**Comment by junwen12221** [comment]
注意批量获取序列号有缓存

**Comment by Degree-21** [comment]
批量获取是否可以通过
/*+mycat:loadConfigFromFile{} */ 
刷新缓存

**Comment by junwen12221** [comment]
你设置序列号步长为1就没有缓存,或者自己写一个序列号类,加载,自己控制
