### ISSUE TITLE
连接MySQL执行UTC_DATE()、UTC_TIME()、UTC_TIMESTAMP()函数报错

### ISSUE THREAD

**Issue by nicecodeclub** [MyCATApache/Mycat2#653]
**Describe the bug**
连接MySQL执行UTC_DATE()、UTC_TIME()、UTC_TIMESTAMP()函数，在不传参数的情况会报错，传参则正常执行，MySQL本身是支持无参数执行这几个时间函数的。

**Screenshots**
![image](https://user-images.githubusercontent.com/12929071/160239609-1348106a-1c30-44da-bb35-d1f5cecf5ba4.png)

**Comment by junwen12221** [comment]
https://www.yuque.com/ccazhw/ml3nkf/da38c2fce9fd89d39d9d0fcb53bf5d17 

配置
`"pushDownSelectDual":"hackRouter",`

**Comment by junwen12221** [comment]
你换个新版本的mycat2就行

**Comment by nicecodeclub** [comment]
谢谢，我试一下最新版

**Comment by nicecodeclub** [comment]
新版本已修复
