### ISSUE TITLE
mycat2 是否支持json类型的数据查询

### ISSUE THREAD

**Issue by DerrickRoseCode** [MyCATApache/Mycat2#655]

**Comment by junwen12221** [comment]
支持的,会变成varchar类型

**Comment by DerrickRoseCode** [comment]
![image](https://user-images.githubusercontent.com/46275542/161176629-d6f143de-d240-4600-bc78-478e633c065d.png)
这样的json查询也是可以的吗

**Comment by junwen12221** [comment]
只有单表,全局表支持,分片表暂时不支持

**Comment by junwen12221** [comment]
分片表命中一个分区的时候也可以执行json函数的

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-1.jar

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-1.jar

**Comment by DerrickRoseCode** [comment]
您好, 这个包要咋用呢

**Comment by DerrickRoseCode** [comment]
您好, 这个包使用后还是报错

**Comment by DerrickRoseCode** [comment]
报错信息为:  FUNCTION SubGt does not exist

**Comment by junwen12221** [comment]
把旧的包删掉了吗

**Comment by DerrickRoseCode** [comment]
非常感谢, 已经好了
