### ISSUE TITLE
配置物理库（schema）报错

### ISSUE THREAD

**Issue by 1995liuwei** [MyCATApache/Mycat2#664]
配置物理库（schema）时如下：
{
    "schemaName": "mekoom-v3",
    "targetName": "mekoom-v3",
    "normalTables": {}
}
即schemaName的value带有-的话就会报错，错误如下：
io.mycat.MycatException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-v3' at line 1
at io.mycat.datasource.jdbc.datasource.DefaultConnection.executeQuery(DefaultConnection.java:93)
at io.mycat.prototypeserver.mysql.PrototypeService.getDefaultNormalTable(PrototypeService.java:2222)
Iat io.mycat.MetadataManager.addSchema(MetadataManager.java:214)
at io.mycat.MysqlMetadataManager.<init>(MysqlMetadataManager.java:646)
at io.mycat.MetadataManager$1.<init>(MetadataManager.java:136)
at io.mycat.MetadataManager.createMetadataManager(MetadataManager.java:136)
at io.mycat.config.MycatRouterConfigOps.getMetadataManager(MycatRouterConfigOps.java:714)
at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:554)
at io.mycat.sqlhandler.ConfigUpdater.load(ConfigUpdater.java:60)
at io.mycat.sqlhandler.ConfigUpdater.loadConfigFromFile(ConfigUpdater.java:41)
at io.mycat.MycatCore.startServer(MycatCore.java:225)
at io.mycat.MycatCore.main(MycatCore.java:244)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
at java.lang.Thread.run(Unknown Source)
 Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-v3' at line 1
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1202)
	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296)
	at io.mycat.datasource.jdbc.datasource.DefaultConnection.executeQuery(DefaultConnection.java:84)
	... 17 common frames omitted

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-8.jar

**Comment by 1995liuwei** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-8.jar
解决了，很感谢

**Comment by 1995liuwei** [comment]
换成了mycat2-1.21-release-jar-with-dependencies-2022-4-8.jar后，在mycat中进行任意表insert插入时出错了
以下是异常信息
INFO   | jvm 1    | 2022/04/08 14:31:12 | 2022-04-08 14:31:12,284[ERROR]io.mycat.commands.MycatdbCommand.lambda$execute$7:492
INFO   | jvm 1    | 2022/04/08 14:31:12 | com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'insert into mekoom-v3.`actiontypeconfig` (, pos 19, line 1, column 19, token -
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:113)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at com.alibaba.druid.sql.SQLUtils.parseSingleStatement(SQLUtils.java:592)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at com.alibaba.druid.sql.SQLUtils.parseSingleMysqlStatement(SQLUtils.java:623)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.DrdsSql.getParameterizedStatement(DrdsSql.java:83)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:125)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:34)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:481)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:524)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:94)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2022/04/08 14:31:12 | 	at java.lang.Thread.run(Unknown Source)

**Comment by 1995liuwei** [comment]
更新也出现了异常，如执行下面sql
UPDATE `mekoom-v3`.`test_408` SET `id` = 2 WHERE `id` = 1
出现异常：
com.alibaba.druid.sql.parser.ParserException: Invalid from clause : mekoom - v3.`test_408`
删除也是相同

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-8.jar

**Comment by 1995liuwei** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-8.jar

您好，已经解决了无法插入更新与删除的问题了，但是在启动的时候wrapper.log出现许多类似下文的异常，我不知道是否会对生产使用有什么影响，请问可以解惑一下吗？
INFO   | jvm 1    | 2022/04/11 10:56:02 | com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CREATE TABLE mekoom-v3.system_profile_bak (, pos 20, line 1, column 20, token -
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:113)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at com.alibaba.druid.sql.SQLUtils.parseSingleStatement(SQLUtils.java:592)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at com.alibaba.druid.sql.SQLUtils.parseSingleMysqlStatement(SQLUtils.java:623)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.MysqlMetadataManager$2.get(MysqlMetadataManager.java:72)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.MysqlMetadataManager$2.get(MysqlMetadataManager.java:62)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.prototypeserver.mysql.VisualTableHandler$1.scanAll(VisualTableHandler.java:37)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.AsyncMycatDataContextImpl.getTableObservable(AsyncMycatDataContextImpl.java:408)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at Baz.bindObservable(Unknown Source)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.calcite.PrepareExecutor.lambda$getMysqlPayloadObjectObservable$7(PrepareExecutor.java:75)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.commands.ReceiverImpl.lambda$sendResultSet$0(ReceiverImpl.java:128)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2022/04/11 10:56:02 | 	at java.lang.Thread.run(Unknown Source)

**Comment by junwen12221** [comment]
这个错误是执行show tables类似的sql时候的报错,因为

CREATE TABLE mekoom-v3.system_profile_bak 缺了``导致不支持-

在生产上如果没有查询information.tables/columns不会有影响
图形化客户端的表导航会看到少了一些表,但是少了的表通过sql执行是可以访问的

这个是修复好的

http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-11.jar

**Comment by 1995liuwei** [comment]
> 这个错误是执行show tables类似的sql时候的报错,因为
> 
> CREATE TABLE mekoom-v3.system_profile_bak 缺了``导致不支持-
> 
> 在生产上如果没有查询information.tables/columns不会有影响 图形化客户端的表导航会看到少了一些表,但是少了的表通过sql执行是可以访问的
> 
> 这个是修复好的
> 
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-11.jar

感谢俊文12221，问题已解决
