### ISSUE TITLE
通过注释配置，不会自动写到原型库？

### ISSUE THREAD

**Issue by GiftLee** [MyCATApache/Mycat2#665]
1：通过注释配置，不会自动写到原型库？
目前看到的没有自动同步，需要执行/*+mycat:syncConfigFromFileToDb{} */

2：启动不是从原型库拉取配置？
启动时候没有拉取，是配置问题？

```

**Comment by junwen12221** [comment]
都不会的,启动时候总是从本地文件读取

**Comment by GiftLee** [comment]
mycat集群模式下，注释配置只会单节点生成，其他节点配置同步成问题了
有实现配置中心的规划吗？

**Comment by junwen12221** [comment]
自己写个程序补上这个逻辑,注释配置后提交到原型库,然后通知其他mycat从原型库更新配置
