### ISSUE TITLE
分片表insert数据报错

### ISSUE THREAD

**Issue by warcraft007** [MyCATApache/Mycat2#676]
mysql-8.0.21，mycat2-1.16
以YYYYMM进行分片表，在逻辑库中新增表数据报错，在物理库中能正常新增
TBPARTITION BY YYYYMM(`CreationTime`) TBPARTITIONS 12
![微信截图_20220422094132](https://user-images.githubusercontent.com/45378612/164580376-3c9aaecb-9762-4dc0-8343-87e4271a90f1.png)

![微信截图_20220422094306](https://user-images.githubusercontent.com/45378612/164580391-60325b46-557c-43fd-9e9a-321efc81e427.png)

![微信截图_20220422094322](https://user-images.githubusercontent.com/45378612/164580409-1c73c709-59ca-4b69-97ec-050f27eb951f.png)

INFO   | jvm 1    | 2022/04/22 09:07:29 | [vertx-mycat-28] ERROR io.mycat.MycatDataContext - 
INFO   | jvm 1    | 2022/04/22 09:07:29 | java.lang.NullPointerException
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.compileInsert(DrdsRunner.java:381)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.dispatch(DrdsRunner.java:279)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.convertToMycatRel(DrdsRunner.java:254)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.convertToMycatRel(DrdsRunner.java:203)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.convertToExecuter(DrdsRunner.java:615)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.getPlan(DrdsRunner.java:862)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.DrdsRunner.runOnDrds(DrdsRunner.java:836)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.sqlhandler.dml.UpdateSQLHandler.updateHandler(UpdateSQLHandler.java:77)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.sqlhandler.dml.InsertSQLHandler.onExecute(InsertSQLHandler.java:20)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:38)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.commands.MycatdbCommand.lambda$execute$0(MycatdbCommand.java:182)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:169)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:142)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:135)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:105)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.Future.compose(Future.java:199)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.Future.flatMap(Future.java:180)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:135)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.mycatmysql.MycatMySQLHandler.handleQuery(MycatMySQLHandler.java:545)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.mycatmysql.MycatMySQLHandler.handle0(MycatMySQLHandler.java:122)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.mycatmysql.MycatMySQLHandler.handle(MycatMySQLHandler.java:87)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.vertx.VertxMySQLPacketResolver.handle(VertxMySQLPacketResolver.java:84)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.mycat.vertx.VertxMySQLPacketResolver.handle(VertxMySQLPacketResolver.java:12)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:397)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:90)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:378)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:78)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:123)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
INFO   | jvm 1    | 2022/04/22 09:07:29 | 	at java.lang.Thread.run(Thread.java:748)

**Comment by warcraft007** [comment]
SQL：INSERT INTO `financial` (`Id`,`Amount`, `Balance`, `BusinessType`, `Code`, `CreationTime`, `ErrMsg`, `RelateTradeNo`, `Remark`, `ServiceBusiness`, `ServiceCode`, `TradeNo`)
VALUES ('ce2822a6-743e-4ed5-449f-3a035e41dc06',100, 1000, 1, 'hcd00029', '2022-04-21T20:24:47', '', '', '', 0, 3, '20220421202447242251');

**Comment by zwyqz** [comment]
建表语句，麻烦详细给下；

**Comment by warcraft007** [comment]
"createTableSQL":"CREATE TABLE clientconfig.`financial` (\n\t`Id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,\n\t`Code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,\n\t`BusinessType` int NOT NULL,\n\t`ServiceCode` int NOT NULL,\n\t`ServiceBusiness` int NOT NULL,\n\t`Amount` decimal(18, 2) NOT NULL,\n\t`Balance` decimal(18, 2) NOT NULL,\n\t`Remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,\n\t`CreationTime` datetime(2) NOT NULL,\n\t`RelateTradeNo` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,\n\t`TradeNo` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,\n\t`ErrMsg` longtext,\n\tPRIMARY KEY USING BTREE (`Id`),\n\tKEY `financialsms_index_createtime_code` (`CreationTime`, `Code`)\n) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci\nDBPARTITION BY YYYYMM(CreationTime) DBPARTITIONS 1\nTBPARTITION BY YYYYMM(CreationTime) TBPARTITIONS 12"

**Comment by zwyqz** [comment]
試了下是少了use clientconfig;
沒有指定schema導致的；
