### ISSUE TITLE
如何怎么把已经存在的物理表加载到mycat中?

### ISSUE THREAD

**Issue by zhaozw1984** [MyCATApache/Mycat2#677]
![image](https://user-images.githubusercontent.com/40883231/164591359-8a047c21-9cf5-40a4-b94c-8bfffe8d7505.png)
第二条说的问题是什么版本支持的？为什么我如下配置不行？
![image](https://user-images.githubusercontent.com/40883231/164591584-1e06ecc9-983c-4f9a-8945-e147e327b10e.png)

**Comment by junwen12221** [comment]
1.20,1.21都支持,加载不了的表,在日志里有相关错误的

**Comment by zhaozw1984** [comment]
可以了，是因为数据库名称有特殊字符的原因。

**Comment by qifengzhang007** [comment]
@junwen12221   
作者你好，
我也通过这种方式进行了加载，一切正常。

接下来继续在对应的同名逻辑库创建了分片表，然后重启mycat2，不幸的是，会把物理库的分片表一起显示出来。

同时测试了一切从0开始创建的库和表，发现在重启mycat2之后，在逻辑库没有把分片表显示出来。

**Comment by qifengzhang007** [comment]
![bug1](https://www.ginskeleton.com/images/bug1.png)

重启mycat2之后，逻辑表和分片表一起都显示出来了

![bug2](https://www.ginskeleton.com/images/bug2.png)
