### ISSUE TITLE
PartitionByHotDate分库分表

### ISSUE THREAD

**Issue by hanchikang** [MyCATApache/Mycat2#684]
PartitionByHotDate支持分冷热库吗？
1.如果支持，应该怎么配置？
2.不支持，有什么替代方法？

需求：
1.通过指定时间字段，实现冷热分库，
2.通过指定id字段，以取模方式分表

**Comment by junwen12221** [comment]
这个分片算法,一般系统用不到的,它要每日进行数据迁移配合的

**Comment by hanchikang** [comment]
> 这个分片算法,一般系统用不到的,它要每日进行数据迁移配合的

对数据进行迁移的问题，是明白的。那支持冷热分库吗？

**Comment by zwyqz** [comment]
可以自行验证，如果不满足，可以自行写路由算法支持；

**Comment by hanchikang** [comment]
好吧。。。
