### ISSUE TITLE
mycat 1 里面如果关闭堆外内存合并，返回结果集会重复，等于结果*物理表个数

### ISSUE THREAD

**Issue by xiaoliu10** [MyCATApache/Mycat2#686]
**Describe the bug**
目前一时之间还不能换 所以先看能不能解决，开启堆外内存合并会导致cpu 爆满 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoliu10** [comment]
方便的话 加个联系方式 沟通一下

**Comment by junwen12221** [comment]
qq:294712221 你这个问题下载最新的1.6就可以解决http://dl.mycat.org.cn/1.6.7.6/20220419132943/Mycat-server-1.6.7.6-release-20220419132943-linux.tar.gz

**Comment by xiaoliu10** [comment]
好的  我试一下

**Comment by xiaoliu10** [comment]
分支应该是1.6.7.6-2020-11-2这个吧？ 我们自己有一些扩展要合并一下

**Comment by xiaoliu10** [comment]
我测试了还是一样的 用1.6.7.6-2020-11-2分支代码 @junwen12221

**Comment by xiaoliu10** [comment]
可以了 是我jar包没有清理干净
