### ISSUE TITLE
请问如何使用一个逻辑库映射管理多个数据源的同名物理库

### ISSUE THREAD

**Issue by xiuluogu** [MyCATApache/Mycat2#687]
如题，现有多个数据源相互独立，存在相同的物理库表结构。1.6创建schema能够设置数据源列表，mycat2如何实现呢？

**Comment by junwen12221** [comment]
多个数据源上的表有相同名字,一个逻辑库映射多个数据源,怎样区分这些同名的表

**Comment by xiuluogu** [comment]
> 多个数据源上的表有相同名字,一个逻辑库映射多个数据源,怎样区分这些同名的表

你好，实际场景是因为分租户独立部署，库表结构完全一致，希望通过中间件来实现跨库union 甚至是join查询，不知道能否支持呢？

**Comment by junwen12221** [comment]
功能上没有问题的配置一个逻辑库的逻辑表在不同数据源上是可以的,每个逻辑表都一个配置就行,,第二个就是跨库join在数据量大的时候,有性能问题,要用explain看一下执行计划如何

**Comment by xiuluogu** [comment]
> 
再请教下，具体如何配置呢？我先创建了一个逻辑库
```
/*+ mycat:createSchema{
	"schemaName":"db1",
	"targetName":""
} */;
```
再尝试建立逻辑表
```
/*+ mycat:createTable{
  "normalTable":{
    "locality":{
      "schemaName":"db1", 
      "tableName":"t_user", 
      "targetName":"c0" 
    },
  },
  "schemaName":"db1",
  "tableName":"t_user" 
} */;
```
当尝试使用 数据源 c1再次建立一个t_user 的逻辑表映射时，发现db1.schema.json文件会覆盖前一次操作生成的映射表。直接复制扩展normalTable内容，貌似也未能生效，而且发现无法在查询的sql中添加where条件。
```
/*+ mycat:createTable{
  "normalTable":{
    "locality":{
      "schemaName":"db1", 
      "tableName":"t_user", 
      "targetName":"c1" 
    },
  },
  "schemaName":"db1",
  "tableName":"t_user" 
} */;
```

**Comment by xiuluogu** [comment]
> 

感谢解答
