### ISSUE TITLE
求助一下：只想分表不想分库

### ISSUE THREAD

**Issue by qifengzhang007** [MyCATApache/Mycat2#688]
我只想单库分表不分库，为什么使用分表sql创建以后，自动创建了分片数据库？
在以下语法中，DBPARTITIONS  我设置为 1 或者不设置，都会自动创建一个 db_test_0  ，然后在这个新数据库创建 tb_users_0、tb_users_1 。
我只想在 逻辑库 db_test  对应的物理库 db_test 中分表，不要创建新的数据库，我该怎么办？

```code

CREATE TABLE db_test.`tb_users` (
  `id` bigint(20) primary key  NOT NULL AUTO_INCREMENT,
  `user_id` varchar(32) NOT NULL COMMENT '用户唯一标识',
  `user_name` varchar(32) NOT NULL COMMENT '登录账号）'  
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户账号表'
DBPARTITION BY MOD_HASH(user_id) DBPARTITIONS 1
TBPARTITION BY MOD_HASH(user_id) TBPARTITIONS 2;

```

**Comment by junwen12221** [comment]
打开对应的表配置,把mappingFormat改成需要的    集群/物理库名/物理表名
```
{
  "customTables": {},
  "globalTables": {},
  "normalTables": {},
  "schemaName": "db1",
  "shardingTables": {
    "travelrecord": {
      "function": {
        "properties": {
          "dbNum": "1",
          "tableNum": "10",
          "tableMethod": "hash(id)",
          "storeNum": 1,
          "dbMethod": "hash(id)",
          "mappingFormat": "prototype/db1/travelrecord_${index}"
        }
      }
    }
  }
}
```

**Comment by qifengzhang007** [comment]
多谢了，按照你给出的语法对数据库部分删除变量，使用固定的数据库名。
重启了mycat2，发现还是不生效。
在群里管理员的指导下，执行了以下语法，终于达成我的目标了。

```code

/*+ mycat:repairPhysicalTable{} */;

```

//  后续补充一下
修改了这个配置文件，发现必须重启 mycat2 + 执行上述  repair 命令才能生效。

**Comment by qifengzhang007** [comment]
我希望类似这种情况，官方可以通过设置：

`DBPARTITION BY MOD_HASH(user_id) DBPARTITIONS 0`

直接达成上述目标。
不然太麻烦了。

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-29.jar

DBPARTITIONS<2 ,不分物理库名

**Comment by qifengzhang007** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-29.jar
> 
> DBPARTITIONS<2 ,不分物理库名


非常感谢作者快速更新、处理。
经过测试，目前已经正常了，DBPARTITIONS 设置为1 没有产生分片数据库，只对表进行了分片。

**Comment by zhanxp** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-29.jar
> 
> DBPARTITIONS<2 ,不分物理库名

有个类似的问题，求助大佬如何解决；
现在是需要只分库不分表，目前发现：
TBPARTITION BY mod_hash(id) TBPARTITIONS 0;  如果设置为0，无法完成分库；
不设置或者设置成1，则会强制在表名后面加一个 _0;
有没有可能 TBPARTITION  能和题主的 DBPARTITIONS 一样，<2时使用原来的表名呢。
