### ISSUE TITLE
BUG 上报： 关于表分片语法必然会产生一个数据库分片

### ISSUE THREAD

**Issue by qifengzhang007** [MyCATApache/Mycat2#689]
### BUG 描述

使用表分片语法，必定会产生一个分片数据库,
在以下语法中， DBPARTITION  不管设置为1 还是直接不使用该语法，都会产生一个分片数据库。

这里有个issue有整个过程的详细描述： https://github.com/MyCATApache/Mycat2/issues/688

```code 

CREATE TABLE `db_ginskeleton`.`tb_order` (
  `id` BIGINT(20) PRIMARY  KEY NOT NULL AUTO_INCREMENT,
  `order_id` VARCHAR(30) NOT NULL COMMENT '订单id',
  `remark` VARCHAR(32) NOT NULL COMMENT '备注信息'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户账号表'
DBPARTITION BY MOD_HASH(id) DBPARTITIONS 1   // 删除这行也会产生一个数据库分片
TBPARTITION BY MOD_HASH(id) TBPARTITIONS 4;

```
### 我期望什么

希望作者能够支持在  DBPARTITION 设置为0 的、或者不设置的时候，不对数据库进行分片，只对表进行分片。

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-29.jar
DBPARTITION  <2 视为不分物理库名

**Comment by qifengzhang007** [comment]
> http://dl.mycat.org.cn/2.0/1.21-release/mycat2-1.21-release-jar-with-dependencies-2022-4-29.jar DBPARTITION <2 视为不分物理库名

非常感谢作者快速更新、处理。
经过测试，目前已经正常了，DBPARTITIONS 设置为1 没有产生分片数据库，只对表进行了分片。
