### ISSUE TITLE
咨询一下：将已经存在的物理数据库加载到mycat2之后发生的怪异现象

### ISSUE THREAD

**Issue by qifengzhang007** [MyCATApache/Mycat2#690]
### 问题描述
我是按照这个 [帖子](https://github.com/MyCATApache/Mycat2/issues/677)   将已经存在的数据库加载到mycat2，
然后我用数据表的分片命令创建了分片表：

![bug1](https://www.ginskeleton.com/images/bug1.png)

但是重启mycat2之后，在mycat2连接的客户端把物理表的分片数据表也显示出来了，不知道怎么回事？

![bug1](https://www.ginskeleton.com/images/bug2.png)

**Comment by junwen12221** [comment]
因为分表也是物理表,物理表会被自动加载

**Comment by qifengzhang007** [comment]
> 

分片表是在加载了已有的老数据库之后使用 mycat2提供的语法生成的，
按理说，需要mycat2记录，下一次不要显示出来分片物理表。
这个问题后续版本应该能更新解决吧？

**Comment by junwen12221** [comment]
不是的,这个两个独立的功能,物理分表被自动加载物理库的所有表的功能加载了.你只需把配置中的物理分表去掉,然后去掉自动加载的targetName就行

**Comment by qifengzhang007** [comment]
> 不是的,这个两个独立的功能,物理分表被自动加载物理库的所有表的功能加载了.你只需把配置中的物理分表去掉,然后去掉自动加载的targetName就行


多谢作者指点。
首次加载完成物理数据库以后，在相关的 xxx.scheme.json 配置文件，手动删除  targetName 以后，再创建分片表就不会自动加载了。
