### ISSUE TITLE
删除mycat2中的逻辑表后物理数据库对应的分片表并没有删除

### ISSUE THREAD

**Issue by qifengzhang007** [MyCATApache/Mycat2#691]
**BUG 描述**
1. 我的数据库是通过  targetName 加载的。
2. 加载以后我通过如下命令创建了分片表, 在mycat2背后连接的物理数据库也同步创建了3张表。
```code

CREATE TABLE db_ginskeleton.`tb_test_users` (
  `id` BIGINT(20) PRIMARY KEY  NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(32) NOT NULL COMMENT '用户唯一标识',
  `user_name` VARCHAR(32) NOT NULL COMMENT '登录账号'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户账号表'
DBPARTITION BY MOD_HASH(user_id) DBPARTITIONS 1
TBPARTITION BY MOD_HASH(user_id) TBPARTITIONS 3;

```
3. 接下来我删除了 mycat2 中的逻辑表： tb_test_users ，然后去mycta2背后的物理数据库检查，发现该表在物理数据库中的分片表没有删除, tb_test_users_0 、tb_test_users_1、tb_test_users_2 仍然存在。

**Comment by junwen12221** [comment]
正常的，mycat在删除逻辑表的时候不会删除数据的，或者只删除原型库的表。删除逻辑表数据的功能可能通过注释来实现。

**Comment by qifengzhang007** [comment]
好的，如果是这么设计的，那就说明程序没有bug。
手动删除分片表，也没啥大问题。
