### ISSUE TITLE
查询单表分片表 使用 select * 报错

### ISSUE THREAD

**Issue by xtcuiyd** [MyCATApache/Mycat2#701]
- 环境:
  - mycat2 版本 1.22 (mycat2-1.22-release-jar-with-dependencies-5-12.jar)
  - mysql 版本 8.0
- 分片配置:
  -  `"orders": {
			"createTableSQL": "",
			"function": {
				"clazz": "io.mycat.router.mycat1xfunction.PartitionByDateEx",
				"properties":{
					"beginDate":"2021-01-01 00:00:00",
					"dateFormat":"yyyy-MM-dd HH:mm:ss",
					"partionDay":30,
					"columnName":"created_at",
					"naturalDay":"0"
				},
				"ranges": {}
			},
			"partition": {
				"schemaNames": "yunding",
				"tableNames": "orders_$0-71",
				"targetNames": "prototype"
			},
			"shardingIndexTables": {}
		},`
- sql: select * from orders;
- 返回结果: java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0

- log: `INFO   | jvm 1    | 2022/05/16 05:42:30 | 2022-05-16 13:42:30,937[ERROR]io.mycat.vertx.VertxExecuter.onRow:734
INFO   | jvm 1    | 2022/05/16 05:42:30 | java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.vertx.BaseRowObservable.getObjects(BaseRowObservable.java:331)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.vertx.VertxExecuter$5.onRow(VertxExecuter.java:732)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:123)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:104)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:53)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 2022-05-16 13:42:30,962[ERROR]io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0:151
INFO   | jvm 1    | 2022/05/16 05:42:30 | java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.vertx.BaseRowObservable.getObjects(BaseRowObservable.java:331)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.vertx.VertxExecuter$5.onRow(VertxExecuter.java:732)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:123)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:104)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:53)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/05/16 05:42:30 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2022/05/16 05:42:31 | io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.AsyncMycatDataContextImpl.lambda$null$12(AsyncMycatDataContextImpl.java:177)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl$2.onFailure(FutureImpl.java:112)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:243)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:205)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.AsyncMycatDataContextImpl.lambda$null$5(AsyncMycatDataContextImpl.java:156)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:94)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl.onSuccess(FutureImpl.java:91)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.AsyncMycatDataContextImpl.lambda$null$7(AsyncMycatDataContextImpl.java:153)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:84)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.vertx.VertxExecuter$5.onError(VertxExecuter.java:746)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:152)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:104)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:53)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2022/05/16 05:42:31 | Caused by: java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.vertx.BaseRowObservable.getObjects(BaseRowObservable.java:331)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.vertx.VertxExecuter$5.onRow(VertxExecuter.java:732)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:123)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	... 11 more
INFO   | jvm 1    | 2022/05/16 05:42:31 | Exception in thread "pool-1-thread-53" io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.AsyncMycatDataContextImpl.lambda$null$12(AsyncMycatDataContextImpl.java:177)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl$2.onFailure(FutureImpl.java:112)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:243)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:205)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.AsyncMycatDataContextImpl.lambda$null$5(AsyncMycatDataContextImpl.java:156)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:94)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureImpl.onSuccess(FutureImpl.java:91)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.AsyncMycatDataContextImpl.lambda$null$7(AsyncMycatDataContextImpl.java:153)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:84)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.vertx.VertxExecuter$5.onError(VertxExecuter.java:746)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:152)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:39)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.FutureBase.transform(FutureBase.java:92)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.vertx.core.impl.future.SucceededFuture.transform(SucceededFuture.java:27)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.newquery.NewMycatConnectionImpl.prepareQuery(NewMycatConnectionImpl.java:104)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.monitor.ThreadMycatConnectionImplWrapper.lambda$prepareQuery$1(ThreadMycatConnectionImplWrapper.java:53)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2022/05/16 05:42:31 | Caused by: java.lang.UnsupportedOperationException: 2022-04-14 10:00:38.0
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.vertx.BaseRowObservable.getObjects(BaseRowObservable.java:331)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.vertx.VertxExecuter$5.onRow(VertxExecuter.java:732)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	at io.mycat.newquery.NewMycatConnectionImpl.lambda$prepareQuery$0(NewMycatConnectionImpl.java:123)
INFO   | jvm 1    | 2022/05/16 05:42:31 | 	... 11 more
`

**Comment by junwen12221** [comment]
createTableSQL应为null

**Comment by xtcuiyd** [comment]
ok,已解决
