### ISSUE TITLE
in 慢查询问题

### ISSUE THREAD

**Issue by bs7729** [MyCATApache/Mycat2#703]
CREATE TABLE IF NOT EXISTS `node`.`travelrecord_qq` (
	`id` bigint NOT NULL AUTO_INCREMENT,
	`user_id` varchar(100) DEFAULT NULL,
	`traveldate` date DEFAULT NULL,
	`fee` decimal(10, 0) DEFAULT NULL,
	`days` int DEFAULT NULL,
	`blob` longblob,
	PRIMARY KEY (`id`),
	KEY `id` (`id`),
	KEY `dex_user_id` (`user_id`)
) ENGINE = InnoDB CHARSET = utf8
DBPARTITION BY mod_hash(user_id) DBPARTITIONS 10
TBPARTITION BY mod_hash(id) TBPARTITIONS 2;

用user_id做为分库

SELECT COUNT(1) from travelrecord_qq WHERE user_id in(28)
SELECT COUNT(1) from travelrecord_qq WHERE user_id in(18);
方式查询快

SELECT COUNT(1) from travelrecord_qq WHERE user_id in(18,28);
in里多个值后查询很慢

查询对比如下：
![Q0~2E`)~L~F}RH@ U7X{LUH](https://user-images.githubusercontent.com/64937539/169200400-fd515c45-e4e7-4d2e-8644-3cf148e0acb7.jpg)

in有多个值时，用explain查看，把所有库与所有库都用union all 连接了

![image](https://user-images.githubusercontent.com/64937539/169200558-f3f963fd-6ec8-4185-987d-0093552b955c.png)

**Comment by junwen12221** [comment]
http://dl.mycat.org.cn/2.0/1.22-release/mycat2-1.22-release-jar-with-dependencies-2022-5-19.jar

**Comment by elon62094-ship-it** [comment]
Hello 👋

**Comment by elon62094-ship-it** [comment]
> http://dl.mycat.org.cn/2.0/1.22-release/mycat2-1.22-release-jar-with-dependencies-2022-5-19.jar

 Hello 👋
