### ISSUE TITLE
关于分布式事务的解决方案的疑问

### ISSUE THREAD

**Issue by ghost** [MyCATApache/Mycat2#710]
抱歉，我看都用中文就先用中文描述了，如果需要使用英文，被告知后我会立刻改为英文描述

背景：之前基于Mycat1.6.7.x版本实现了多租户功能，当时基于某开源分布式事务组件，自己开发了一套分布式事务的实现，但是效果并不好。现在打算修改为使用seata，但是seata的主版本并没有提供对于hint的支持，也无相关扩展方案，导致无法进行下去。自己在mycat社区寻找解决方案时，看到了官网文档中包含下述说明：

事务框架
● 支持单个本地事务和多个本地事务
● 支持基于Proxy的事务
● 理论上基于JDBC的事务框架的多线程事务框架容易支持
● JTA方案的分布式事务方案由于性能太差被移除
● 没有准备支持分布式事务,请通过架构层面解决这个问题
● Mycat2走上了自研事务框架的道路

疑问：关于“没有准备支持分布式事务,请通过架构层面解决这个问题”，以及“Mycat2走上了自研事务框架的道路”，是否可以理解为Mycat2当前并不支持分布式事务，未来是否支持待定。

**Comment by junwen12221** [comment]
Mycat2现在支持XA事务
