### ISSUE TITLE
您好, 查询不会报错, 使用navicate客户端进行查询时显示没有数据, 使用线上的接口查询能够查询到数据, 下面是navicate客户端查询后的日志, 请问一下是什么原因呢

### ISSUE THREAD

**Issue by DerrickRoseCode** [MyCATApache/Mycat2#711]
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:26,945[DEBUG]io.mycat.datasource.jdbc.datasource.DefaultConnection.close:107close com.mysql.cj.jdbc.ConnectionImpl@651431c4
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:26,946[DEBUG]io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.closeConnection:157close :io.mycat.datasource.jdbc.datasource.DefaultConnection@1cd31215 com.mysql.cj.jdbc.ConnectionImpl@651431c4
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,036[DEBUG]io.mycat.commands.MycatdbCommand.executeQuery:163SHOW STATUS
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,037[DEBUG]io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection:132get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@1acfe847
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,037[DEBUG]io.mycat.vertxmycat.MycatVertxPreparedStatement.query:38SHOW STATUS
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,041[DEBUG]io.mycat.datasource.jdbc.datasource.DefaultConnection.close:107close com.mysql.cj.jdbc.ConnectionImpl@330d83
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,041[DEBUG]io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.closeConnection:157close :io.mycat.datasource.jdbc.datasource.DefaultConnection@1acfe847 com.mysql.cj.jdbc.ConnectionImpl@330d83
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,255[DEBUG]oshi.util.FileUtil.readFile:86Reading file /proc/cpuinfo
INFO   | jvm 1    | 2022/06/03 11:16:27 | 2022-06-03 11:16:27,256[DEBUG]oshi.util.FileUtil.readFile:86Reading file /proc/stat
INFO   | jvm 1    | 2022/06/03 11:16:28 | 2022-06-03 11:16:28,587[DEBUG]io.mycat.commands.MycatdbCommand.executeQuery:163 SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION FROM INFORMATION_SCHEMA.PROFILING GROUP BY QUERY_ID
INFO   | jvm 1    | 2022/06/03 11:16:28 | 2022-06-03 11:16:28,589[DEBUG]io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.getConnection:132get connection:prototypeDs io.mycat.datasource.jdbc.datasource.DefaultConnection@38e25efa
INFO   | jvm 1    | 2022/06/03 11:16:28 | 2022-06-03 11:16:28,589[DEBUG]io.mycat.vertxmycat.MycatVertxPreparedStatement.query:38SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION
INFO   | jvm 1    | 2022/06/03 11:16:28 | FROM `information_schema`.`PROFILING`
INFO   | jvm 1    | 2022/06/03 11:16:28 | GROUP BY QUERY_ID
INFO   | jvm 1    | 2022/06/03 11:16:28 | 2022-06-03 11:16:28,591[DEBUG]io.mycat.datasource.jdbc.datasource.DefaultConnection.close:107close com.mysql.cj.jdbc.ConnectionImpl@330d83
INFO   | jvm 1    | 2022/06/03 11:16:28 | 2022-06-03 11:16:28,591[DEBUG]io.mycat.datasource.jdbc.datasource.JdbcConnectionManager.closeConnection:157close :io.mycat.datasource.jdbc.datasource.DefaultConnection@38e25efa com.mysql.cj.jdbc.ConnectionImpl@330d83

**Comment by DerrickRoseCode** [comment]
使用线上接口查询不会有这一段日志

**Comment by junwen12221** [comment]
Navicat发送了
` SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION FROM INFORMATION_SCHEMA.PROFILING GROUP BY QUERY_ID`
这个sql,mycat会返回空结果集,影响了Navicat后续的查询

你可以把 INFORMATION_SCHEMA.PROFILING配置成单表,使这个sql能够正常执行

https://www.yuque.com/ccazhw/ml3nkf/trcenv
