### ISSUE TITLE
mycat2 sql having不支持

### ISSUE THREAD

**Issue by wenxincao** [MyCATApache/Mycat2#720]
version  1.21release  mysql 5.6.20

sql:

SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, CASE WHEN TABLE_TYPE='BASE TABLE' THEN CASE WHEN TABLE_SCHEMA = 'mysql' 
OR TABLE_SCHEMA = 'performance_schema' THEN 'SYSTEM TABLE' ELSE 'TABLE' END WHEN TABLE_TYPE='TEMPORARY' THEN 'LOCAL_TEMPORARY' ELSE TABLE_TYPE 
END AS TABLE_TYPE, TABLE_COMMENT AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME, NULL AS SELF_REFERENCING_COL_NAME, 
NULL AS REF_GENERATION 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'yx_nev' AND TABLE_NAME 
LIKE 'ACT_RU_EXECUTION' 
HAVING TABLE_TYPE IN ('TABLE',NULL,NULL,NULL,NULL) 
ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME

error:

[ERROR]io.mycat.sqlhandler.ShardingSQLHandler.onExecute:61SELECTTABLE_SCHEMAASTABLE_CAT,NULLASTABLE_SCHEM,TABLE_NAME
|||,CASE
|||WHENTABLE_TYPE='BASETABLE'THEN
|||CASE
|||WHENTABLE_SCHEMA='mysql'
|||ORTABLE_SCHEMA='performance_schema'
|||THEN'SYSTEMTABLE'
|||ELSE'TABLE'
|||END
|||WHENTABLE_TYPE='TEMPORARY'THEN'LOCAL_TEMPORARY'
|||ELSETABLE_TYPE
|||ENDASTABLE_TYPE,TABLE_COMMENTASREMARKS,NULLASTYPE_CAT,NULLASTYPE_SCHEM,NULLASTYPE_NAME
|||,NULLASSELF_REFERENCING_COL_NAME,NULLASREF_GENERATION
|||FROMINFORMATION_SCHEMA.TABLES
|||WHERETABLE_SCHEMA='yx_nev'
|||ANDTABLE_NAMELIKE'ACT_RU_EXECUTION'
|||
|||HAVINGTABLE_TYPEIN('TABLE',NULL,NULL,NULL,NULL)
|||ORDERBYTABLE_TYPE,TABLE_SCHEMA,TABLE_NAME
|||LIMIT0,1000
|||org.apache.calcite.runtime.CalciteContextException:Atline0,column0:Expression'TABLE_TYPE'isnotbeinggrouped
|||atsun.reflect.GeneratedConstructorAccessor29.newInstance(UnknownSource)
|||atsun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
|||atjava.lang.reflect.Constructor.newInstance(Constructor.java:423)
|||atorg.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
|||atorg.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:886)
|||atorg.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:871)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5006)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:113)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:40)
|||atorg.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:320)
|||atorg.apache.calcite.sql.util.SqlBasicVisitor$ArgHandlerImpl.visitChild(SqlBasicVisitor.java:123)
|||atorg.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:879)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:212)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:40)
|||atorg.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
|||atorg.apache.calcite.sql.util.SqlBasicVisitor.visit(SqlBasicVisitor.java:52)
|||atorg.apache.calcite.sql.SqlNodeList.accept(SqlNodeList.java:147)
|||atorg.apache.calcite.sql.util.SqlBasicVisitor$ArgHandlerImpl.visitChild(SqlBasicVisitor.java:123)
|||atorg.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:879)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:212)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:40)
|||atorg.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
|||atorg.apache.calcite.sql.util.SqlBasicVisitor$ArgHandlerImpl.visitChild(SqlBasicVisitor.java:123)
|||atorg.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:879)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:212)
|||atorg.apache.calcite.sql.validate.AggChecker.visit(AggChecker.java:40)
|||atorg.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
|||atorg.apache.calcite.sql.validate.AggregatingSelectScope.checkAggregateExpr(AggregatingSelectScope.java:209)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.validateHavingClause(SqlValidatorImpl.java:4126)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3429)
|||atorg.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
|||atorg.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1066)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1040)
|||atorg.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:232)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1015)
|||atorg.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:723)
|||atio.mycat.DrdsSqlCompiler.getRelRoot(DrdsSqlCompiler.java:396)
|||atio.mycat.DrdsSqlCompiler.compileQuery(DrdsSqlCompiler.java:330)
|||atio.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:219)
|||atio.mycat.DrdsSqlCompiler.dispatch(DrdsSqlCompiler.java:211)
|||atio.mycat.calcite.spm.MemPlanCache.add(MemPlanCache.java:182)
|||atio.mycat.calcite.spm.QueryPlanner.getAcceptedMycatRelList(QueryPlanner.java:69)
|||atio.mycat.calcite.spm.QueryPlanner.innerComputeMinCostCodeExecuterContext(QueryPlanner.java:28)
|||atio.mycat.calcite.DrdsRunnerHelper.getPlan(DrdsRunnerHelper.java:370)
|||atio.mycat.calcite.DrdsRunnerHelper.runOnDrds(DrdsRunnerHelper.java:358)
|||atio.mycat.sqlhandler.ShardingSQLHandler.onExecute(ShardingSQLHandler.java:58)
|||atio.mycat.sqlhandler.AbstractSQLHandler.execute(AbstractSQLHandler.java:64)
|||atio.mycat.commands.MycatdbCommand.lambda$execute$7(MycatdbCommand.java:491)
|||atio.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
|||atio.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
|||atio.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:168)
|||atio.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
|||atio.vertx.core.Future.compose(Future.java:199)
|||atio.vertx.core.Future.flatMap(Future.java:180)
|||atio.mycat.commands.MycatdbCommand.execute(MycatdbCommand.java:446)
|||atio.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:200)
|||atio.mycat.commands.MycatdbCommand$1.apply(MycatdbCommand.java:196)
|||atio.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
|||atio.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
|||atio.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
|||atio.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
|||atio.vertx.core.impl.future.SucceededFuture.compose(SucceededFuture.java:27)
|||atio.vertx.core.Future.compose(Future.java:199)
|||atio.vertx.core.Future.flatMap(Future.java:180)
|||atio.mycat.commands.MycatdbCommand.executeQuery(MycatdbCommand.java:196)
|||atio.mycat.mycatmysql.MycatVertxMySQLHandler.handleQuery(MycatVertxMySQLHandler.java:525)
|||atio.mycat.mycatmysql.MycatVertxMySQLHandler.lambda$handle0$2(MycatVertxMySQLHandler.java:95)
|||atio.mycat.IOExecutor$1.lambda$executeBlocking$0(IOExecutor.java:75)
|||atjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
|||atjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
|||atjava.lang.Thread.run(Thread.java:748)
|||Causedby:org.apache.calcite.sql.validate.SqlValidatorException:Expression'TABLE_TYPE'isnotbeinggrouped
|||atsun.reflect.GeneratedConstructorAccessor28.newInstance(UnknownSource)
|||atsun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
|||atjava.lang.reflect.Constructor.newInstance(Constructor.java:423)
|||atorg.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467)
|||atorg.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:560)
|||...68commonframesomitted

**Comment by junwen12221** [comment]
把INFORMATION_SCHEMA.TABLES配置成单表
