### ISSUE TITLE
表分片后 增加 查询 更改 正常  删除时候报错

### ISSUE THREAD

**Issue by balabalabiu-csg** [MyCATApache/Mycat2#721]
表分片后 增加 查询 更改 正常    实体库也是分片存储，但是， 删除时候报错。 mysql 8.0.29  mycat 1.22
  
mycat控制台操作如下

mysql> update labor_plot_enviromental  set plot_sensor_id=4  where id=3;
Query OK, 1 row affected (0.00 sec)

mysql> select id    from  labor_plot_enviromental;
+----+
| id |
+----+
|  3 |
|  7 |
|  8 |
|  9 |
| 13 |
| 14 |
|  4 |
|  5 |
|  6 |
| 10 |
| 11 |
| 12 |
+----+
12 rows in set (0.11 sec)

mysql> delete from labor_plot_enviromental where id =3;
ERROR 1046 (HY000): No database selected
mysql> 

配置如下 
"schemaName":"profile2",
        "shardingTables":{
                "labor_plot_enviromental":{
                        "createTableSQL":"CREATE TABLE IF NOT EXISTS `profile2`.`labor_plot_enviromental`***TBPARTITIONS 1",
                        "function":{
                                "properties":{
                                        "dbNum":"2",
                                        "mappingFormat":"c${targetIndex}/profile2_${dbIndex}/labor_plot_enviromental_${index}",
                                        "tableNum":"1",
                                        "tableMethod":"mod_hash(plot_sensor_id)",
                                        "storeNum":2,
                                        "dbMethod":"mod_hash(plot_sensor_id)"
                                },
                                "ranges":{}
                        },
                        "partition":{

                        },
                        "shardingIndexTables":{}
                }
        },

**Comment by balabalabiu-csg** [comment]
数据源没加名称

**Comment by lhsaq2009** [comment]
> 数据源没加名称

没懂这是怎么解决的，
