### ISSUE TITLE
是否支持master与slave自动切换？

### ISSUE THREAD

**Issue by broccolik** [MyCATApache/Mycat2#736]
背景：mysql主从同步集群，一个master（读写），一个slave（只读）。
目标：一个mysql节点挂了之后能够自动转换至另一台节点。比如master挂了之后，仍然能够连接slave并提供只读功能。

目前已经测试过mycat2代理时，任意节点挂了之后mycat2不能正常工作。配置了 "switchType":"SWITCH"。
以上，谢谢。

**Comment by wangjianme** [comment]
我正想测试此功能，看你这么一说，直接放弃了。
另：MyCat2配置原型库，你是怎么处理的？如果原型库宕机了，MyCat2还能工作吗？如果不能，这也是设计的一大失误。

**Comment by broccolik** [comment]
> 

这种情况不能正常工作

**Comment by zwyqz** [comment]
https://www.yuque.com/ccazhw/ml3nkf/6fcb04592f6c08423f0041efb188963c
我测试了可以自动剔除，自动切换
