### ISSUE TITLE
prototypeDS定义的数据源运行中宕机如何处理？

### ISSUE THREAD

**Issue by wangjianme** [MyCATApache/Mycat2#744]
问题:如果在运行过程中prototypeDS所配置数据源宕机了，对mycat2有什么影响？
mycat2为了保存自己的源数据，必须要连接其中一个mysql主机，做为prototypeDS数据源。

不理解：
本来mycat2做为数据库中间件，用于管理和连接mysql集群的，为什么非要在启动时，先连接其中一个mysql数据库呢？这种严重的依赖下，如果prototypeDS宕机，以mycat2会产生多重的影响？难道为了这个prototypeDS我还需要再配置一个haproxy后面接入多个mysql数据源？
认为这个地方是mycat2最糟糕的设计。

**Comment by zwyqz** [comment]
mycat2暂不支持pg。
