### ISSUE TITLE
配置读写分离后，INSERT或删除数据后的【第一次查询】，总是从写库进行查询，后续仅从读库

### ISSUE THREAD

**Issue by Michael-Zuo** [MyCATApache/Mycat2#745]
想实现读库只读，写库只写。
配置
（1）
`"readBalanceType":"BALANCE_ALL_READ",`
`"switchType":"NOT_SWITCH"`
（2）主库(数据源)的`instanceType`设置`WRITE`, 从库设置为`replicas`后变为`READ`

向数据库插入`INSERT`一条数据，或删除数据后，
请问为什么SELECT数据时，第一次查询总是在主库进行查询？ 从第二次开始，后续均为从库中查询。
`SELECT * FROM mydb1.mytbl`

**Comment by zwyqz** [comment]
如果在事务中，删除之后查询会在主库中查询。
