### ISSUE TITLE
数据库名带有减号"-"时 做分表会报错

### ISSUE THREAD

**Issue by huo-huo** [MyCATApache/Mycat2#746]
**Describe the bug**
数据库名带有减号"-"时 做分表会报错

**Expected behavior**
数据库名带有减号"-"时 能正常分表

**Screenshots**
![image](https://user-images.githubusercontent.com/26914566/186556635-816181f7-61ea-464b-a81b-a14392f6561a.png)

**Desktop (please complete the following information):**
mycat2-1.22-release-jar-with-dependencies-2022-4-21.jar

**Additional context**

**Comment by zwyqz** [comment]
需要用引号引起来试试看，类似如下
select * from 'myTest-b'.mySharding
