### ISSUE TITLE
两主两从数据同步正常,使用mycat2后,数据同步断开,请问这是怎么回事呢?

### ISSUE THREAD

**Issue by weiwenqiang** [MyCATApache/Mycat2#748]
两主两从(一主一备,互为主备,两从)配置号数据同步后,使用正常,
在使用Mycat2后,数据不在同步
具体使用:数据源4个,集群c0,c1两个

测试表
CREATE TABLE `dev_mqtt_data_my` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `device_id` CHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备ID',
  `device_state` INT DEFAULT NULL COMMENT '设备状态',
  `device_data` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备返回数据',
  `data_time` CHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '时间戳',
  `data1` INT DEFAULT NULL COMMENT '数据1',
  `data2` INT DEFAULT NULL COMMENT '数据2',
  `data3` INT DEFAULT NULL COMMENT '数据3',
  `data4` INT DEFAULT NULL COMMENT '数据4',
  `data5` INT DEFAULT NULL COMMENT '数据5',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=22691 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='设备MQTT数据' 
dbpartition BY mod_hash(device_id) tbpartition BY mod_hash(device_id) tbpartitions 1 dbpartitions 2;

mycat可以正常分库分表,插入数据也可以正常插入到两个库中,但是查询报Unknown database 'mydb1_1'
![图片](https://user-images.githubusercontent.com/16027666/187411679-986a313d-f113-4c21-97fe-05058ba160ac.png)

但是插入还是正常
![图片](https://user-images.githubusercontent.com/16027666/187411810-bf112a26-639f-441f-b354-b776859be1d4.png)

主要一旦使用mycat2,数据同步就断开了,请问这是怎么回事呢?

具体文件:
{
	"dbType":"mysql",
	"idleTimeout":60000,
	"initSqls":[],
	"initSqlsGetConnection":true,
	"instanceType":"READ_WRITE",
	"logAbandoned":true,
	"maxCon":1000,
	"maxConnectTimeout":30000,
	"maxRetryCount":5,
	"minCon":1,
	"name":"rwSepr1",
	"password":"123456",
	"queryTimeout":0,
	"removeAbandoned":false,
	"removeAbandonedTimeoutSecond":180,
	"type":"JDBC",
	"url":"jdbc:mysql://192.168.0.100:3309/mydb1?serverTimezone=Asia/Shanghai&useUnicode=false&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&autoReconnect=true",
	"user":"reader",
	"weight":0
}
{
	"dbType":"mysql",
	"idleTimeout":60000,
	"initSqls":[],
	"initSqlsGetConnection":true,
	"instanceType":"READ_WRITE",
	"logAbandoned":true,
	"maxCon":1000,
	"maxConnectTimeout":30000,
	"maxRetryCount":5,
	"minCon":1,
	"name":"rwSepr2",
	"password":"123456",
	"queryTimeout":0,
	"removeAbandoned":false,
	"removeAbandonedTimeoutSecond":180,
	"type":"JDBC",
	"url":"jdbc:mysql://192.168.0.97:3309/mydb1?serverTimezone=Asia/Shanghai&useUnicode=false&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&autoReconnect=true",
	"user":"reader",
	"weight":0
}
{
	"dbType":"mysql",
	"idleTimeout":60000,
	"initSqls":[],
	"initSqlsGetConnection":true,
	"instanceType":"READ_WRITE",
	"logAbandoned":true,
	"maxCon":1000,
	"maxConnectTimeout":30000,
	"maxRetryCount":5,
	"minCon":1,
	"name":"rwSepw1",
	"password":"123456",
	"queryTimeout":0,
	"removeAbandoned":false,
	"removeAbandonedTimeoutSecond":180,
	"type":"JDBC",
	"url":"jdbc:mysql://192.168.0.100:3308/mydb1?serverTimezone=Asia/Shanghai&useUnicode=false&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&autoReconnect=true",
	"user":"reader",
	"weight":0
}
{
	"dbType":"mysql",
	"idleTimeout":60000,
	"initSqls":[],
	"initSqlsGetConnection":true,
	"instanceType":"READ_WRITE",
	"logAbandoned":true,
	"maxCon":1000,
	"maxConnectTimeout":30000,
	"maxRetryCount":5,
	"minCon":1,
	"name":"rwSepw2",
	"password":"123456",
	"queryTimeout":0,
	"removeAbandoned":false,
	"removeAbandonedTimeoutSecond":180,
	"type":"JDBC",
	"url":"jdbc:mysql://192.168.0.97:3308/mydb1?serverTimezone=Asia/Shanghai&useUnicode=false&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&autoReconnect=true",
	"user":"reader",
	"weight":0
}
c0
{
	"clusterType":"MASTER_SLAVE",
	"heartbeat":{
		"heartbeatTimeout":1000,
		"maxRetryCount":3,
		"minSwitchTimeInterval":300,
		"showLog":false,
		"slaveThreshold":0.0
	},
	"masters":[
		"rwSepw1"
	],
	"maxCon":2000,
	"name":"c0",
	"readBalanceType":"BALANCE_ALL",
	"replicas":[
		"rwSepr1"
	],
	"switchType":"SWITCH"
}
c1
{
	"clusterType":"MASTER_SLAVE",
	"heartbeat":{
		"heartbeatTimeout":1000,
		"maxRetryCount":3,
		"minSwitchTimeInterval":300,
		"showLog":false,
		"slaveThreshold":0.0
	},
	"masters":[
		"rwSepw2"
	],
	"maxCon":2000,
	"name":"c1",
	"readBalanceType":"BALANCE_ALL",
	"replicas":[
		"rwSepr2"
	],
	"switchType":"SWITCH"
}

**Comment by zwyqz** [comment]
可以通过show slave status 具体查看原因，主从配置哪里没配置好；
