### ISSUE TITLE
如何配置salve节点的故障自动剔除？

### ISSUE THREAD

**Issue by hillbun** [MyCATApache/Mycat2#752]
我配置了3个slave节点

        "replicas":[
                "slave01",
                "slave02",
                "slave03"
        ]

当salve03 连接不上的时候，提示连接失败，节点没有自动剔除

ERROR 1105 (HY000): com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 3000, active 0, maxActive 1000, creating 1, createElapseMillis 2719, createErrorCount 3411

请问应该如何配置？

**Comment by zwyqz** [comment]
https://www.yuque.com/ccazhw/ml3nkf/6fcb04592f6c08423f0041efb188963c
