### ISSUE TITLE
启动报错 [ERROR]io.mycat.replica.ReplicaSelectorRuntime.registerDatasource:268ignored master

### ISSUE THREAD

**Issue by pusamm1314** [MyCATApache/Mycat2#753]
Running mycat2...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | path:/home/mycat/./conf
jvm 1    | 2022-09-08 17:31:49,259[ERROR]io.mycat.replica.ReplicaSelectorRuntime.registerDatasource:268ignored master
jvm 1    | 2022-09-08 17:31:49,271[INFO]com.alibaba.druid.pool.DruidDataSource.close:2043{dataSource-0} closing ...
jvm 1    | 
jvm 1    | WrapperSimpleApp: Encountered an error running main: java.lang.IllegalArgumentException: ignored master
jvm 1    | java.lang.IllegalArgumentException: ignored master
jvm 1    | 	at io.mycat.replica.ReplicaSelectorRuntime.registerDatasource(ReplicaSelectorRuntime.java:269)
jvm 1    | 	at io.mycat.replica.ReplicaSelectorRuntime.addCluster(ReplicaSelectorRuntime.java:247)
jvm 1    | 	at io.mycat.replica.ReplicaSelectorRuntime.<init>(ReplicaSelectorRuntime.java:83)
jvm 1    | 	at io.mycat.config.MycatRouterConfigOps.getReplicaSelectorManager(MycatRouterConfigOps.java:752)
jvm 1    | 	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:521)
jvm 1    | 	at io.mycat.sqlhandler.ConfigUpdater.load(ConfigUpdater.java:60)
jvm 1    | 	at io.mycat.sqlhandler.ConfigUpdater.loadConfigFromFile(ConfigUpdater.java:41)
jvm 1    | 	at io.mycat.MycatCore.startServer(MycatCore.java:218)
jvm 1    | 	at io.mycat.MycatCore.main(MycatCore.java:237)
jvm 1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
jvm 1    | 	at java.lang.Thread.run(Thread.java:748)
wrapper  | <-- Wrapper Stopped

**Comment by sincebyte** [comment]
这个问题我也遇到了

**Comment by sincebyte** [comment]
STATUS | wrapper  | 2022/09/19 21:21:24 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2022/09/19 21:21:24 | Launching a JVM...
INFO   | jvm 1    | 2022/09/19 21:21:24 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2022/09/19 21:21:24 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2022/09/19 21:21:24 | 
INFO   | jvm 1    | 2022/09/19 21:21:25 | path:/Users/van/soft/mycat/mycat/./conf
INFO   | jvm 1    | 2022/09/19 21:21:25 | 2022-09-19 21:21:25,385[WARN]io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>:70Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
INFO   | jvm 1    | 2022/09/19 21:21:25 | 2022-09-19 21:21:25,562[ERROR]io.mycat.replica.ReplicaSelectorRuntime.registerDatasource:268ignored prototypeDs
INFO   | jvm 1    | 2022/09/19 21:21:25 | 2022-09-19 21:21:25,576[INFO]com.alibaba.druid.pool.DruidDataSource.close:2043{dataSource-0} closing ...
INFO   | jvm 1    | 2022/09/19 21:21:25 | 2022-09-19 21:21:25,576[INFO]io.mycat.datasource.jdbc.datasource.JdbcDataSource.lambda$close$0:150JdbcDataSource:root closed
INFO   | jvm 1    | 2022/09/19 21:21:25 | 
INFO   | jvm 1    | 2022/09/19 21:21:25 | WrapperSimpleApp: Encountered an error running main: java.lang.IllegalArgumentException: ignored prototypeDs
INFO   | jvm 1    | 2022/09/19 21:21:25 | java.lang.IllegalArgumentException: ignored prototypeDs
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.replica.ReplicaSelectorRuntime.registerDatasource(ReplicaSelectorRuntime.java:269)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.replica.ReplicaSelectorRuntime.addCluster(ReplicaSelectorRuntime.java:247)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.replica.ReplicaSelectorRuntime.<init>(ReplicaSelectorRuntime.java:83)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.config.MycatRouterConfigOps.getReplicaSelectorManager(MycatRouterConfigOps.java:753)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.config.MycatRouterConfigOps.commit(MycatRouterConfigOps.java:522)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.sqlhandler.ConfigUpdater.load(ConfigUpdater.java:60)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.sqlhandler.ConfigUpdater.loadConfigFromFile(ConfigUpdater.java:41)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.MycatCore.startServer(MycatCore.java:219)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at io.mycat.MycatCore.main(MycatCore.java:238)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2022/09/19 21:21:25 | 	at java.lang.Thread.run(Thread.java:748)
STATUS | wrapper  | 2022/09/19 21:21:27 | <-- Wrapper Stopped

**Comment by zwyqz** [comment]
检查配置DataSource中有无配置当前数据源；
