### ISSUE TITLE
datagrip连接失败,navicat可以正常连接

### ISSUE THREAD

**Issue by bigtian99** [MyCATApache/Mycat2#757]
错误信息如下
`[HY000] java.lang.IllegalStateException: Unable to implement MycatMemSort(sort0=[$2], sort1=[$0], dir0=[ASC], dir1=[ASC]): rowcount = 1.0, cumulative cost = {3.0 rows, 16.0 cpu, 0.0 io}, id = 639 MycatProject(schema_name=[$1], default_collation_name=[$3], EXPR$2=[IF(=(DATABASE(), $1), ?0, ?1)]): rowcount = 1.0, cumulative cost = {2.0 rows, 4.0 cpu, 0.0 io}, id = 638 MycatTableScan(relNode=[LogicalTableScan.NONE.[](table=[information_schema, schemata])]): rowcount = 1.0, cumulative cost = {1.0 rows, 1.0 cpu, 0.0 io}, id = 620.`

**Comment by mytxoo** [comment]
同问

**Comment by zwyqz** [comment]
界面部分不兼容，可以直接連接查詢；
