### ISSUE TITLE
枚举分片异常

### ISSUE THREAD

**Issue by kk0413** [MyCATApache/Mycat2#761]
尝试配置枚举分片后insert异常，尝试过修改各种配置都是一样的错误，请问是哪里出了问题？
schemas下对应数据库json文件分片配置如下：
`"shardingbyenum":{
			"createTableSQL":"CREATE TABLE `shardingbyenum` (`id` bigint NOT NULL AUTO_INCREMENT,`user_id` varchar(100) DEFAULT NULL,PRIMARY KEY `id` (`id`)) ENGINE=InnoDB  DEFAULT CHARSET=utf8",
			"function":{
				"clazz":"io.mycat.router.mycat1xfunction.PartitionByFileMap",
				"properties":{
					"defaultNode":0,
					"type":"String",
					"columnName":"user_id"
				},
				"ranges":{
					"KDY":"0",
					"CY":"1"
				}
			},
			"partition":{},
			"shardingIndexTables":{}
		}`
mycat启动后通过mycat驱动链接数据库可以看到自动建表成功shardingbyenum
insert 语句：
`EXPLAIN insert into shadingbyenum (user_id) VALUES ('KDY')`
报错如下：
io.mycat.MycatException: 1cloud.shadingbyenum 分片算法越界 分片值:{4}

**Comment by zwyqz** [comment]
參考https://www.yuque.com/ccazhw/ml3nkf/518d1c41faf01cca8f4544f0c6ee5d6e
