### ISSUE TITLE
官网下载链接失效了

### ISSUE THREAD

**Issue by Solomon-888** [MyCATApache/Mycat2#767]
http://dl.mycat.org.cn/2.0/
这个链接不能正常访问

**Comment by Ponyo1234** [comment]
同问

**Comment by zwyqz** [comment]
dns污染，加以下信息到hosts文件内即可打开网站
# mycat
210.51.26.184 mycat.org.cn www.mycat.org.cn dl.mycat.org.cn

**Comment by zhongyushi-git** [comment]
加了也没有用啊，这个ip 210.51.26.184也访问不了啊
