### ISSUE TITLE
Releases能放编译好的包吗？

### ISSUE THREAD

**Issue by zwb0619** [MyCATApache/Mycat2#768]
210.51.26.184 mycat.org.cn www.mycat.org.cn dl.mycat.org.cn
改了host，也没法打开这几个页面。想下载mycat2，都没法下载。
ping 210.51.26.184这个ip也是ping不通。我ssh到搬瓦工的主机上ping这个ip也不行。

**Comment by X-Mars** [comment]
楼主找到下载地址了吗

**Comment by zwyqz** [comment]
dns污染，加以下信息到hosts文件内即可打开网站
# mycat
210.51.26.184 mycat.org.cn www.mycat.org.cn dl.mycat.org.cn

**Comment by zwb0619** [comment]
还是那个地址，昨天突然又可以访问了。刚试了下也可以访问

火星小刘 ***@***.***> 于 2022年11月24日周四 13:23写道：

**Comment by X-Mars** [comment]
@zwyqz @zwb0619  感谢  改了host 解决了
