### ISSUE TITLE
官网访问不了了 www.mycat.org.cn | Can't access the official website

### ISSUE THREAD

**Issue by dazer007** [MyCATApache/Mycat2#769]
**Describe the bug**

官网访问不了了 www.mycat.org.cn | Can't access the official website，如果有新的官网，请在Github上进行替换；

**Comment by dazer007** [comment]
mycat.io和mycat.org.cn这两个看起来这么正的域名，都访问不了。

**Comment by ebzeueg** [comment]
请参考解决办法：https://github.com/MyCATApache/Mycat2/issues/767

**Comment by zhongyushi-git** [comment]
现在主要这个ip 210.51.26.184也访问不了啊，一整个访问不了 文件无法下载
