### ISSUE TITLE
Mysql读写分离，主库创建表，从库也同步了，但在mycat中找不到该表

### ISSUE THREAD

**Issue by ryuunami** [MyCATApache/Mycat2#794]
Mysql读写分离，主库创建表，从库也同步了，但在mycat中找不到该表

**Comment by ryuunami** [comment]
重启mycat，代理表就出来了，有没有自动的方式？

**Comment by zwyqz** [comment]
直接通过mycat建表试试看。

**Comment by ryuunami** [comment]
通过mycat建表是可以。

**Comment by Commy2020** [comment]
@ryuunami 我也遇到了这个问题，直连数据库创建的表，不会同步到mycat，重启mycat或者重载mycat服务，mycat逻辑库中的表就出来了，目前我是打算定时重载mycat，这种方式不会影响业务，也不用重启mycat；或者就是直接通过mycat建表，能从根本解决这个问题。你们现在有更好的解决方案了吗？
