### ISSUE TITLE
官网无法访问，ip也是

### ISSUE THREAD

**Issue by zhongyushi-git** [MyCATApache/Mycat2#814]
官网无法访问，试了ip也不通
![image](https://github.com/MyCATApache/Mycat2/assets/57444364/f4824860-7094-43b9-83bf-3dde74b618df)

**Comment by zwyqz** [comment]
进官网扣扣群，看看有没有的资料，先应应急

**Comment by zhongyushi-git** [comment]
进群了，但发了消息没人回复｡°(°¯᷄◠¯᷅°)°｡



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月22日(周三) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MyCATApache/Mycat2] 官网无法访问，ip也是 (Issue #814)




 
进官网扣扣群，看看有没有的资料，先应应急

**Comment by zwyqz** [comment]
http://mycatone.top/  我已经再群里面临时上传了写文件，看看你有没有需要的

**Comment by zhongyushi-git** [comment]
刚刚上传的吗？我在群里没有看到，群号332702697，文件的话就是安装的文件，template 压缩包和 dependencies jar



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月22日(周三) 上午9:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MyCATApache/Mycat2] 官网无法访问，ip也是 (Issue #814)




 
http://mycatone.top/  我已经再群里面临时上传了写文件，看看你有没有需要的

**Comment by onlycp** [comment]
同样不行，申请加群了，还没通过

**Comment by makeuuu** [comment]
这个项目是黄了吗？官方下载链接都是错的

**Comment by superxiongzai** [comment]
> http://mycatone.top/ 我已经再群里面临时上传了写文件，看看你有没有需要的

大佬，我也下载不了，进群也一直没通过，能帮忙发我下吗
